// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type AddAgentConversationMessageRequest struct {
	AgentKey       string `pathParam:"style=simple,explode=false,name=agentKey"`
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// The follow-up question, with optional scope, model and tool overrides.
	Body components.AgentAddMessageRequest `request:"mediaType=application/json"`
}

func (a *AddAgentConversationMessageRequest) GetAgentKey() string {
	if a == nil {
		return ""
	}
	return a.AgentKey
}

func (a *AddAgentConversationMessageRequest) GetConversationID() string {
	if a == nil {
		return ""
	}
	return a.ConversationID
}

func (a *AddAgentConversationMessageRequest) GetBody() components.AgentAddMessageRequest {
	if a == nil {
		return components.AgentAddMessageRequest{}
	}
	return a.Body
}

type AddAgentConversationMessageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The conversation with the new question and answer.
	AddMessageResponse *components.AddMessageResponse
	Headers            map[string][]string
}

func (a AddAgentConversationMessageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddAgentConversationMessageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddAgentConversationMessageResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddAgentConversationMessageResponse) GetAddMessageResponse() *components.AddMessageResponse {
	if a == nil {
		return nil
	}
	return a.AddMessageResponse
}

func (a *AddAgentConversationMessageResponse) GetHeaders() map[string][]string {
	if a == nil {
		return map[string][]string{}
	}
	return a.Headers
}
