// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ArchiveProjectRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
}

func (a *ArchiveProjectRequest) GetProjectID() string {
	if a == nil {
		return ""
	}
	return a.ProjectID
}

// ArchiveProjectResponseBody - Project archived
type ArchiveProjectResponseBody struct {
	// A workspace that groups related assistant and agent conversations
	// under a shared name, instructions, knowledge scope, tool
	// selection, and its own hidden Collection of uploaded files. See
	// the `Projects` tag description for the sharing model.
	//
	Project *components.Project `json:"project,omitzero"`
}

func (a ArchiveProjectResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ArchiveProjectResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ArchiveProjectResponseBody) GetProject() *components.Project {
	if a == nil {
		return nil
	}
	return a.Project
}

type ArchiveProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Project archived
	Object *ArchiveProjectResponseBody
}

func (a ArchiveProjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ArchiveProjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ArchiveProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *ArchiveProjectResponse) GetObject() *ArchiveProjectResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}
