// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type CancelAgentConversationStreamRequestBody struct {
	// The `runId` sent when the stream was started.
	RunID string `json:"runId"`
}

func (c *CancelAgentConversationStreamRequestBody) GetRunID() string {
	if c == nil {
		return ""
	}
	return c.RunID
}

type CancelAgentConversationStreamRequest struct {
	// Stable key identifying the agent that owns this conversation.
	AgentKey string `pathParam:"style=simple,explode=false,name=agentKey"`
	// ID of the agent conversation to cancel a run for.
	ConversationID string                                   `pathParam:"style=simple,explode=false,name=conversationId"`
	Body           CancelAgentConversationStreamRequestBody `request:"mediaType=application/json"`
}

func (c *CancelAgentConversationStreamRequest) GetAgentKey() string {
	if c == nil {
		return ""
	}
	return c.AgentKey
}

func (c *CancelAgentConversationStreamRequest) GetConversationID() string {
	if c == nil {
		return ""
	}
	return c.ConversationID
}

func (c *CancelAgentConversationStreamRequest) GetBody() CancelAgentConversationStreamRequestBody {
	if c == nil {
		return CancelAgentConversationStreamRequestBody{}
	}
	return c.Body
}

// CancelAgentConversationStreamResponseBody - Cancellation requested, or the run had already finished.
type CancelAgentConversationStreamResponseBody struct {
	Cancelled *bool `json:"cancelled,omitzero"`
}

func (c *CancelAgentConversationStreamResponseBody) GetCancelled() *bool {
	if c == nil {
		return nil
	}
	return c.Cancelled
}

type CancelAgentConversationStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Cancellation requested, or the run had already finished.
	Object *CancelAgentConversationStreamResponseBody
}

func (c CancelAgentConversationStreamResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CancelAgentConversationStreamResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CancelAgentConversationStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CancelAgentConversationStreamResponse) GetObject() *CancelAgentConversationStreamResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
