// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type CreateConversationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Conversation created with its first answer.
	CreateConversationResponse *components.CreateConversationResponse
	Headers                    map[string][]string
}

func (c CreateConversationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateConversationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateConversationResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateConversationResponse) GetCreateConversationResponse() *components.CreateConversationResponse {
	if c == nil {
		return nil
	}
	return c.CreateConversationResponse
}

func (c *CreateConversationResponse) GetHeaders() map[string][]string {
	if c == nil {
		return map[string][]string{}
	}
	return c.Headers
}
