// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// CreateProjectResponseBody - Project created
type CreateProjectResponseBody struct {
	// A workspace that groups related assistant and agent conversations
	// under a shared name, instructions, knowledge scope, tool
	// selection, and its own hidden Collection of uploaded files. See
	// the `Projects` tag description for the sharing model.
	//
	Project components.Project `json:"project"`
}

func (c *CreateProjectResponseBody) GetProject() components.Project {
	if c == nil {
		return components.Project{}
	}
	return c.Project
}

type CreateProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Project created
	Object *CreateProjectResponseBody
}

func (c CreateProjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateProjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateProjectResponse) GetObject() *CreateProjectResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
