// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type DeleteAgentConversationByIDRequest struct {
	AgentKey       string `pathParam:"style=simple,explode=false,name=agentKey"`
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
}

func (d *DeleteAgentConversationByIDRequest) GetAgentKey() string {
	if d == nil {
		return ""
	}
	return d.AgentKey
}

func (d *DeleteAgentConversationByIDRequest) GetConversationID() string {
	if d == nil {
		return ""
	}
	return d.ConversationID
}

type DeleteAgentConversationByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Conversation deleted or no-op delete completed successfully
	AgentConversationDeleteResponse *components.AgentConversationDeleteResponse
}

func (d DeleteAgentConversationByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteAgentConversationByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteAgentConversationByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteAgentConversationByIDResponse) GetAgentConversationDeleteResponse() *components.AgentConversationDeleteResponse {
	if d == nil {
		return nil
	}
	return d.AgentConversationDeleteResponse
}
