// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type DeleteRecordRequest struct {
	// Record ID
	RecordID string `pathParam:"style=simple,explode=false,name=recordId"`
}

func (d *DeleteRecordRequest) GetRecordID() string {
	if d == nil {
		return ""
	}
	return d.RecordID
}

type DeleteRecordResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Record deleted successfully
	DeleteRecordResponseSchema *components.DeleteRecordResponseSchema
}

func (d DeleteRecordResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteRecordResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteRecordResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteRecordResponse) GetDeleteRecordResponseSchema() *components.DeleteRecordResponseSchema {
	if d == nil {
		return nil
	}
	return d.DeleteRecordResponseSchema
}
