// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type DeleteAgentConversationChatAttachmentRequest struct {
	// Agent key path parameter. Must be non-empty.
	AgentKey string `pathParam:"style=simple,explode=false,name=agentKey"`
	// Attachment record id (from the upload response). Must be non-blank after trim.
	RecordID string `pathParam:"style=simple,explode=false,name=recordId"`
}

func (d *DeleteAgentConversationChatAttachmentRequest) GetAgentKey() string {
	if d == nil {
		return ""
	}
	return d.AgentKey
}

func (d *DeleteAgentConversationChatAttachmentRequest) GetRecordID() string {
	if d == nil {
		return ""
	}
	return d.RecordID
}

type DeleteAgentConversationChatAttachmentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteAgentConversationChatAttachmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
