// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type DeleteKnowledgeBaseRequest struct {
	// Knowledge base ID (non-empty string)
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
}

func (d *DeleteKnowledgeBaseRequest) GetKbID() string {
	if d == nil {
		return ""
	}
	return d.KbID
}

type DeleteKnowledgeBaseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Knowledge base deleted successfully
	DeleteKnowledgeBaseByID *components.DeleteKnowledgeBaseByID
}

func (d DeleteKnowledgeBaseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteKnowledgeBaseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteKnowledgeBaseResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteKnowledgeBaseResponse) GetDeleteKnowledgeBaseByID() *components.DeleteKnowledgeBaseByID {
	if d == nil {
		return nil
	}
	return d.DeleteKnowledgeBaseByID
}
