// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type EnsureProjectKnowledgeBaseRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
}

func (e *EnsureProjectKnowledgeBaseRequest) GetProjectID() string {
	if e == nil {
		return ""
	}
	return e.ProjectID
}

// EnsureProjectKnowledgeBaseResponseBody - The project's linked Collection id (existing or newly created)
type EnsureProjectKnowledgeBaseResponseBody struct {
	KbID string `json:"kbId"`
}

func (e *EnsureProjectKnowledgeBaseResponseBody) GetKbID() string {
	if e == nil {
		return ""
	}
	return e.KbID
}

type EnsureProjectKnowledgeBaseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The project's linked Collection id (existing or newly created)
	Object *EnsureProjectKnowledgeBaseResponseBody
}

func (e EnsureProjectKnowledgeBaseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnsureProjectKnowledgeBaseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnsureProjectKnowledgeBaseResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EnsureProjectKnowledgeBaseResponse) GetObject() *EnsureProjectKnowledgeBaseResponseBody {
	if e == nil {
		return nil
	}
	return e.Object
}
