// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"time"
)

// GetAgentConversationByIDSortBy - Field to sort messages by
type GetAgentConversationByIDSortBy string

const (
	GetAgentConversationByIDSortByCreatedAt   GetAgentConversationByIDSortBy = "createdAt"
	GetAgentConversationByIDSortByMessageType GetAgentConversationByIDSortBy = "messageType"
	GetAgentConversationByIDSortByContent     GetAgentConversationByIDSortBy = "content"
)

func (e GetAgentConversationByIDSortBy) ToPointer() *GetAgentConversationByIDSortBy {
	return &e
}
func (e *GetAgentConversationByIDSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "createdAt":
		fallthrough
	case "messageType":
		fallthrough
	case "content":
		*e = GetAgentConversationByIDSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAgentConversationByIDSortBy: %v", v)
	}
}

// GetAgentConversationByIDSortOrder - Sort direction
type GetAgentConversationByIDSortOrder string

const (
	GetAgentConversationByIDSortOrderAsc  GetAgentConversationByIDSortOrder = "asc"
	GetAgentConversationByIDSortOrderDesc GetAgentConversationByIDSortOrder = "desc"
)

func (e GetAgentConversationByIDSortOrder) ToPointer() *GetAgentConversationByIDSortOrder {
	return &e
}
func (e *GetAgentConversationByIDSortOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = GetAgentConversationByIDSortOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAgentConversationByIDSortOrder: %v", v)
	}
}

// GetAgentConversationByIDMessageType - Filter messages by type
type GetAgentConversationByIDMessageType string

const (
	GetAgentConversationByIDMessageTypeUserQuery   GetAgentConversationByIDMessageType = "user_query"
	GetAgentConversationByIDMessageTypeBotResponse GetAgentConversationByIDMessageType = "bot_response"
	GetAgentConversationByIDMessageTypeError       GetAgentConversationByIDMessageType = "error"
	GetAgentConversationByIDMessageTypeFeedback    GetAgentConversationByIDMessageType = "feedback"
	GetAgentConversationByIDMessageTypeSystem      GetAgentConversationByIDMessageType = "system"
)

func (e GetAgentConversationByIDMessageType) ToPointer() *GetAgentConversationByIDMessageType {
	return &e
}
func (e *GetAgentConversationByIDMessageType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user_query":
		fallthrough
	case "bot_response":
		fallthrough
	case "error":
		fallthrough
	case "feedback":
		fallthrough
	case "system":
		*e = GetAgentConversationByIDMessageType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAgentConversationByIDMessageType: %v", v)
	}
}

type GetAgentConversationByIDRequest struct {
	AgentKey       string `pathParam:"style=simple,explode=false,name=agentKey"`
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// Page number for message pagination (1 = most recent batch)
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of messages per page
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// Field to sort messages by
	SortBy *GetAgentConversationByIDSortBy `default:"createdAt" queryParam:"style=form,explode=true,name=sortBy"`
	// Sort direction
	SortOrder *GetAgentConversationByIDSortOrder `default:"desc" queryParam:"style=form,explode=true,name=sortOrder"`
	// Filter messages created on or after this date
	StartDate *time.Time `queryParam:"style=form,explode=true,name=startDate"`
	// Filter messages created on or before this date
	EndDate *time.Time `queryParam:"style=form,explode=true,name=endDate"`
	// Filter messages by type
	MessageType *GetAgentConversationByIDMessageType `queryParam:"style=form,explode=true,name=messageType"`
}

func (g GetAgentConversationByIDRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAgentConversationByIDRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAgentConversationByIDRequest) GetAgentKey() string {
	if g == nil {
		return ""
	}
	return g.AgentKey
}

func (g *GetAgentConversationByIDRequest) GetConversationID() string {
	if g == nil {
		return ""
	}
	return g.ConversationID
}

func (g *GetAgentConversationByIDRequest) GetPage() *int64 {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GetAgentConversationByIDRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetAgentConversationByIDRequest) GetSortBy() *GetAgentConversationByIDSortBy {
	if g == nil {
		return nil
	}
	return g.SortBy
}

func (g *GetAgentConversationByIDRequest) GetSortOrder() *GetAgentConversationByIDSortOrder {
	if g == nil {
		return nil
	}
	return g.SortOrder
}

func (g *GetAgentConversationByIDRequest) GetStartDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.StartDate
}

func (g *GetAgentConversationByIDRequest) GetEndDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.EndDate
}

func (g *GetAgentConversationByIDRequest) GetMessageType() *GetAgentConversationByIDMessageType {
	if g == nil {
		return nil
	}
	return g.MessageType
}

type GetAgentConversationByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Agent conversation detail
	AgentConversationDetailResponse *components.AgentConversationDetailResponse
}

func (g GetAgentConversationByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAgentConversationByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAgentConversationByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAgentConversationByIDResponse) GetAgentConversationDetailResponse() *components.AgentConversationDetailResponse {
	if g == nil {
		return nil
	}
	return g.AgentConversationDetailResponse
}
