// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetProjectConversationsRequest struct {
	ProjectID string `pathParam:"style=simple,explode=false,name=projectId"`
	Page      *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	Limit     *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
}

func (g GetProjectConversationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetProjectConversationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetProjectConversationsRequest) GetProjectID() string {
	if g == nil {
		return ""
	}
	return g.ProjectID
}

func (g *GetProjectConversationsRequest) GetPage() *int64 {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GetProjectConversationsRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

type GetProjectConversationsPagination struct {
	Page       *int64 `json:"page,omitzero"`
	Limit      *int64 `json:"limit,omitzero"`
	TotalCount *int64 `json:"totalCount,omitzero"`
	TotalPages *int64 `json:"totalPages,omitzero"`
}

func (g *GetProjectConversationsPagination) GetPage() *int64 {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GetProjectConversationsPagination) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetProjectConversationsPagination) GetTotalCount() *int64 {
	if g == nil {
		return nil
	}
	return g.TotalCount
}

func (g *GetProjectConversationsPagination) GetTotalPages() *int64 {
	if g == nil {
		return nil
	}
	return g.TotalPages
}

// GetProjectConversationsResponseBody - Paginated conversations linked to the project
type GetProjectConversationsResponseBody struct {
	Conversations []components.ConversationListItem `json:"conversations"`
	Pagination    GetProjectConversationsPagination `json:"pagination"`
}

func (g *GetProjectConversationsResponseBody) GetConversations() []components.ConversationListItem {
	if g == nil {
		return []components.ConversationListItem{}
	}
	return g.Conversations
}

func (g *GetProjectConversationsResponseBody) GetPagination() GetProjectConversationsPagination {
	if g == nil {
		return GetProjectConversationsPagination{}
	}
	return g.Pagination
}

type GetProjectConversationsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated conversations linked to the project
	Object *GetProjectConversationsResponseBody
}

func (g GetProjectConversationsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetProjectConversationsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetProjectConversationsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetProjectConversationsResponse) GetObject() *GetProjectConversationsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
