// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetRecordByIDRequest struct {
	// Record ID
	RecordID string `pathParam:"style=simple,explode=false,name=recordId"`
	// Optional format to convert the file to (e.g., PDF to text). Supported conversions include PPT to PDF and PPTX to PDF.
	ConvertTo *string `queryParam:"style=form,explode=true,name=convertTo"`
}

func (g *GetRecordByIDRequest) GetRecordID() string {
	if g == nil {
		return ""
	}
	return g.RecordID
}

func (g *GetRecordByIDRequest) GetConvertTo() *string {
	if g == nil {
		return nil
	}
	return g.ConvertTo
}

type GetRecordByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	GetRecordByIDResponseSchema *components.GetRecordByIDResponseSchema
}

func (g GetRecordByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRecordByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetRecordByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRecordByIDResponse) GetGetRecordByIDResponseSchema() *components.GetRecordByIDResponseSchema {
	if g == nil {
		return nil
	}
	return g.GetRecordByIDResponseSchema
}
