// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetRecordContentRequest struct {
	// Record ID to fetch. Obtain it from a `pipeshub_search` result (`hits[*].recordId`) or a chat citation (`citations[*].recordId`).
	RecordID string `pathParam:"style=simple,explode=false,name=recordId"`
}

func (g *GetRecordContentRequest) GetRecordID() string {
	if g == nil {
		return ""
	}
	return g.RecordID
}

type GetRecordContentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation. When the record has no available content
	// (e.g. not indexed), `content` is the literal `No record found`
	// rather than an error status.
	//
	GetRecordContentResponseSchema *components.GetRecordContentResponseSchema
}

func (g GetRecordContentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetRecordContentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetRecordContentResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetRecordContentResponse) GetGetRecordContentResponseSchema() *components.GetRecordContentResponseSchema {
	if g == nil {
		return nil
	}
	return g.GetRecordContentResponseSchema
}
