// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// ListKnowledgeBasesSortBy - Field to sort by.
type ListKnowledgeBasesSortBy string

const (
	ListKnowledgeBasesSortByName               ListKnowledgeBasesSortBy = "name"
	ListKnowledgeBasesSortByCreatedAtTimestamp ListKnowledgeBasesSortBy = "createdAtTimestamp"
	ListKnowledgeBasesSortByUpdatedAtTimestamp ListKnowledgeBasesSortBy = "updatedAtTimestamp"
	ListKnowledgeBasesSortByUserRole           ListKnowledgeBasesSortBy = "userRole"
)

func (e ListKnowledgeBasesSortBy) ToPointer() *ListKnowledgeBasesSortBy {
	return &e
}
func (e *ListKnowledgeBasesSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "name":
		fallthrough
	case "createdAtTimestamp":
		fallthrough
	case "updatedAtTimestamp":
		fallthrough
	case "userRole":
		*e = ListKnowledgeBasesSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListKnowledgeBasesSortBy: %v", v)
	}
}

// ListKnowledgeBasesSortOrder - Sort direction.
type ListKnowledgeBasesSortOrder string

const (
	ListKnowledgeBasesSortOrderAsc  ListKnowledgeBasesSortOrder = "asc"
	ListKnowledgeBasesSortOrderDesc ListKnowledgeBasesSortOrder = "desc"
)

func (e ListKnowledgeBasesSortOrder) ToPointer() *ListKnowledgeBasesSortOrder {
	return &e
}
func (e *ListKnowledgeBasesSortOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = ListKnowledgeBasesSortOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListKnowledgeBasesSortOrder: %v", v)
	}
}

type ListKnowledgeBasesRequest struct {
	// Page number (1-indexed). Omitted values default to 1.
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Results per page (max 100). Omitted values default to 20.
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// Search KB names (max 1000 chars). Rejected if it contains HTML/script tags,
	// event handlers, `javascript:`, or format specifiers (validated in Zod + controller).
	//
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// Comma-separated permission roles to filter by. Each token must be one of:
	// OWNER, WRITER, READER.
	//
	Permissions *string `queryParam:"style=form,explode=true,name=permissions"`
	// Field to sort by.
	SortBy *ListKnowledgeBasesSortBy `default:"name" queryParam:"style=form,explode=true,name=sortBy"`
	// Sort direction.
	SortOrder *ListKnowledgeBasesSortOrder `default:"asc" queryParam:"style=form,explode=true,name=sortOrder"`
}

func (l ListKnowledgeBasesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListKnowledgeBasesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListKnowledgeBasesRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListKnowledgeBasesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListKnowledgeBasesRequest) GetSearch() *string {
	if l == nil {
		return nil
	}
	return l.Search
}

func (l *ListKnowledgeBasesRequest) GetPermissions() *string {
	if l == nil {
		return nil
	}
	return l.Permissions
}

func (l *ListKnowledgeBasesRequest) GetSortBy() *ListKnowledgeBasesSortBy {
	if l == nil {
		return nil
	}
	return l.SortBy
}

func (l *ListKnowledgeBasesRequest) GetSortOrder() *ListKnowledgeBasesSortOrder {
	if l == nil {
		return nil
	}
	return l.SortOrder
}

type ListKnowledgeBasesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	GetAllKnowledgeBaseResponseSchema *components.GetAllKnowledgeBaseResponseSchema
}

func (l ListKnowledgeBasesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListKnowledgeBasesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListKnowledgeBasesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListKnowledgeBasesResponse) GetGetAllKnowledgeBaseResponseSchema() *components.GetAllKnowledgeBaseResponseSchema {
	if l == nil {
		return nil
	}
	return l.GetAllKnowledgeBaseResponseSchema
}
