// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ListPersonalAccessTokensResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The caller's active personal access tokens
	ListPatResponse *components.ListPatResponse
}

func (l ListPersonalAccessTokensResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPersonalAccessTokensResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPersonalAccessTokensResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListPersonalAccessTokensResponse) GetListPatResponse() *components.ListPatResponse {
	if l == nil {
		return nil
	}
	return l.ListPatResponse
}
