// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ListPersonalAccessTokenScopesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Scopes available to grant
	PatScopesListResponse *components.PatScopesListResponse
}

func (l ListPersonalAccessTokenScopesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPersonalAccessTokenScopesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPersonalAccessTokenScopesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListPersonalAccessTokenScopesResponse) GetPatScopesListResponse() *components.PatScopesListResponse {
	if l == nil {
		return nil
	}
	return l.PatScopesListResponse
}
