// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// ListAgentsSortOrder - Sort direction.
type ListAgentsSortOrder string

const (
	ListAgentsSortOrderAsc  ListAgentsSortOrder = "asc"
	ListAgentsSortOrderDesc ListAgentsSortOrder = "desc"
)

func (e ListAgentsSortOrder) ToPointer() *ListAgentsSortOrder {
	return &e
}
func (e *ListAgentsSortOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = ListAgentsSortOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListAgentsSortOrder: %v", v)
	}
}

type ListAgentsRequest struct {
	// 1-based page number.
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Maximum number of agents to return in the current page.
	Limit *int64 `default:"20" queryParam:"style=form,explode=true,name=limit"`
	// Case-insensitive search across agent name, description, and tags. Leading/trailing whitespace is trimmed; blank-after-trim values are rejected.
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// Backend sort field. Leading/trailing whitespace is trimmed. Common value is `updatedAtTimestamp`.
	SortBy *string `default:"updatedAtTimestamp" queryParam:"style=form,explode=true,name=sort_by"`
	// Sort direction.
	SortOrder *ListAgentsSortOrder `default:"desc" queryParam:"style=form,explode=true,name=sort_order"`
}

func (l ListAgentsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAgentsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAgentsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListAgentsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListAgentsRequest) GetSearch() *string {
	if l == nil {
		return nil
	}
	return l.Search
}

func (l *ListAgentsRequest) GetSortBy() *string {
	if l == nil {
		return nil
	}
	return l.SortBy
}

func (l *ListAgentsRequest) GetSortOrder() *ListAgentsSortOrder {
	if l == nil {
		return nil
	}
	return l.SortOrder
}

type ListAgentsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Paginated list of accessible agents.
	AgentListResponse *components.AgentListResponse
}

func (l ListAgentsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAgentsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAgentsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAgentsResponse) GetAgentListResponse() *components.AgentListResponse {
	if l == nil {
		return nil
	}
	return l.AgentListResponse
}
