// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"time"
)

type ListAgentConversationArchivesSortBy string

const (
	ListAgentConversationArchivesSortByCreatedAt      ListAgentConversationArchivesSortBy = "createdAt"
	ListAgentConversationArchivesSortByLastActivityAt ListAgentConversationArchivesSortBy = "lastActivityAt"
	ListAgentConversationArchivesSortByTitle          ListAgentConversationArchivesSortBy = "title"
)

func (e ListAgentConversationArchivesSortBy) ToPointer() *ListAgentConversationArchivesSortBy {
	return &e
}
func (e *ListAgentConversationArchivesSortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "createdAt":
		fallthrough
	case "lastActivityAt":
		fallthrough
	case "title":
		*e = ListAgentConversationArchivesSortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListAgentConversationArchivesSortBy: %v", v)
	}
}

type ListAgentConversationArchivesSortOrder string

const (
	ListAgentConversationArchivesSortOrderAsc  ListAgentConversationArchivesSortOrder = "asc"
	ListAgentConversationArchivesSortOrderDesc ListAgentConversationArchivesSortOrder = "desc"
)

func (e ListAgentConversationArchivesSortOrder) ToPointer() *ListAgentConversationArchivesSortOrder {
	return &e
}
func (e *ListAgentConversationArchivesSortOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = ListAgentConversationArchivesSortOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListAgentConversationArchivesSortOrder: %v", v)
	}
}

type ListAgentConversationArchivesRequest struct {
	AgentKey  string                                  `pathParam:"style=simple,explode=false,name=agentKey"`
	Page      *int64                                  `default:"1" queryParam:"style=form,explode=true,name=page"`
	Limit     *int64                                  `default:"20" queryParam:"style=form,explode=true,name=limit"`
	SortBy    *ListAgentConversationArchivesSortBy    `queryParam:"style=form,explode=true,name=sortBy"`
	SortOrder *ListAgentConversationArchivesSortOrder `queryParam:"style=form,explode=true,name=sortOrder"`
	Search    *string                                 `queryParam:"style=form,explode=true,name=search"`
	StartDate *time.Time                              `queryParam:"style=form,explode=true,name=startDate"`
	EndDate   *time.Time                              `queryParam:"style=form,explode=true,name=endDate"`
}

func (l ListAgentConversationArchivesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAgentConversationArchivesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAgentConversationArchivesRequest) GetAgentKey() string {
	if l == nil {
		return ""
	}
	return l.AgentKey
}

func (l *ListAgentConversationArchivesRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListAgentConversationArchivesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListAgentConversationArchivesRequest) GetSortBy() *ListAgentConversationArchivesSortBy {
	if l == nil {
		return nil
	}
	return l.SortBy
}

func (l *ListAgentConversationArchivesRequest) GetSortOrder() *ListAgentConversationArchivesSortOrder {
	if l == nil {
		return nil
	}
	return l.SortOrder
}

func (l *ListAgentConversationArchivesRequest) GetSearch() *string {
	if l == nil {
		return nil
	}
	return l.Search
}

func (l *ListAgentConversationArchivesRequest) GetStartDate() *time.Time {
	if l == nil {
		return nil
	}
	return l.StartDate
}

func (l *ListAgentConversationArchivesRequest) GetEndDate() *time.Time {
	if l == nil {
		return nil
	}
	return l.EndDate
}

type ListAgentConversationArchivesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Archived conversations for the agent
	AgentArchivedConversationListResponse *components.AgentArchivedConversationListResponse
}

func (l ListAgentConversationArchivesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAgentConversationArchivesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAgentConversationArchivesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAgentConversationArchivesResponse) GetAgentArchivedConversationListResponse() *components.AgentArchivedConversationListResponse {
	if l == nil {
		return nil
	}
	return l.AgentArchivedConversationListResponse
}
