// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ListAgentArchivedConversationsGroupedRequest struct {
	AgentPage  *int64 `default:"1" queryParam:"style=form,explode=true,name=agentPage"`
	AgentLimit *int64 `default:"5" queryParam:"style=form,explode=true,name=agentLimit"`
}

func (l ListAgentArchivedConversationsGroupedRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAgentArchivedConversationsGroupedRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAgentArchivedConversationsGroupedRequest) GetAgentPage() *int64 {
	if l == nil {
		return nil
	}
	return l.AgentPage
}

func (l *ListAgentArchivedConversationsGroupedRequest) GetAgentLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.AgentLimit
}

type ListAgentArchivedConversationsGroupedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Grouped archived conversations
	AgentArchivedGroupsResponse *components.AgentArchivedGroupsResponse
}

func (l ListAgentArchivedConversationsGroupedResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListAgentArchivedConversationsGroupedResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListAgentArchivedConversationsGroupedResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListAgentArchivedConversationsGroupedResponse) GetAgentArchivedGroupsResponse() *components.AgentArchivedGroupsResponse {
	if l == nil {
		return nil
	}
	return l.AgentArchivedGroupsResponse
}
