// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type MoveRecordRequest struct {
	// Knowledge base UUID
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
	// Record identifier (file or folder)
	RecordID string `pathParam:"style=simple,explode=false,name=recordId"`
	// Target location for the record
	Body components.KnowledgeBaseMoveRecordRequestBody `request:"mediaType=application/json"`
}

func (m *MoveRecordRequest) GetKbID() string {
	if m == nil {
		return ""
	}
	return m.KbID
}

func (m *MoveRecordRequest) GetRecordID() string {
	if m == nil {
		return ""
	}
	return m.RecordID
}

func (m *MoveRecordRequest) GetBody() components.KnowledgeBaseMoveRecordRequestBody {
	if m == nil {
		return components.KnowledgeBaseMoveRecordRequestBody{}
	}
	return m.Body
}

type MoveRecordResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Record moved successfully
	KnowledgeBaseMoveRecordResponse *components.KnowledgeBaseMoveRecordResponse
}

func (m MoveRecordResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MoveRecordResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MoveRecordResponse) GetHTTPMeta() components.HTTPMetadata {
	if m == nil {
		return components.HTTPMetadata{}
	}
	return m.HTTPMeta
}

func (m *MoveRecordResponse) GetKnowledgeBaseMoveRecordResponse() *components.KnowledgeBaseMoveRecordResponse {
	if m == nil {
		return nil
	}
	return m.KnowledgeBaseMoveRecordResponse
}
