// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"github.com/pipeshub-ai/pipeshub-sdk-go/types/stream"
)

type RegenerateAgentConversationMessageRequest struct {
	// Stable key identifying the agent that owns this conversation.
	AgentKey string `pathParam:"style=simple,explode=false,name=agentKey"`
	// ID of the agent conversation containing the target message.
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// ID of the bot-response message to regenerate.
	MessageID string `pathParam:"style=simple,explode=false,name=messageId"`
	// Regeneration payload requiring `chatMode: quick`.
	//
	Body components.AgentRegenerateRequest `request:"mediaType=application/json"`
}

func (r *RegenerateAgentConversationMessageRequest) GetAgentKey() string {
	if r == nil {
		return ""
	}
	return r.AgentKey
}

func (r *RegenerateAgentConversationMessageRequest) GetConversationID() string {
	if r == nil {
		return ""
	}
	return r.ConversationID
}

func (r *RegenerateAgentConversationMessageRequest) GetMessageID() string {
	if r == nil {
		return ""
	}
	return r.MessageID
}

func (r *RegenerateAgentConversationMessageRequest) GetBody() components.AgentRegenerateRequest {
	if r == nil {
		return components.AgentRegenerateRequest{}
	}
	return r.Body
}

type RegenerateAgentConversationMessageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SSE stream established.
	//
	// Stable event names:
	// - `RUN_FINISHED` — `{ type, result }`, where `result` contains the
	//   updated conversation and metadata
	// - `RUN_ERROR` — `{ type, message, code? }`, reporting lookup,
	//   authorization, or regenerate-rule failures
	//
	// Forwarded lifecycle and child-run events may include `runId`,
	// `threadId`, and `parentRunId`. Additional backend-defined
	// agent/tool events may be emitted.
	// Clients should ignore unknown event names.
	//
	AgentRegenerateSSEEvent *stream.EventStream[components.AgentRegenerateSSEEvent]
}

func (r *RegenerateAgentConversationMessageResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RegenerateAgentConversationMessageResponse) GetAgentRegenerateSSEEvent() *stream.EventStream[components.AgentRegenerateSSEEvent] {
	if r == nil {
		return nil
	}
	return r.AgentRegenerateSSEEvent
}
