// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"github.com/pipeshub-ai/pipeshub-sdk-go/types/stream"
)

type RegenerateAnswerRequest struct {
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// ID of the message to regenerate response for
	MessageID string `pathParam:"style=simple,explode=false,name=messageId"`
	// Request payload
	Body *components.RegenerateRequest `request:"mediaType=application/json"`
}

func (r RegenerateAnswerRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RegenerateAnswerRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RegenerateAnswerRequest) GetConversationID() string {
	if r == nil {
		return ""
	}
	return r.ConversationID
}

func (r *RegenerateAnswerRequest) GetMessageID() string {
	if r == nil {
		return ""
	}
	return r.MessageID
}

func (r *RegenerateAnswerRequest) GetBody() *components.RegenerateRequest {
	if r == nil {
		return nil
	}
	return r.Body
}

type RegenerateAnswerResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SSE stream established. The body is a sequence of
	// `text/event-stream` frames using the event vocabulary described
	// on `SSEEvent`. The exact subset of events emitted depends on
	// `chatMode` (see the route description for routing rules).
	//
	// The gateway emits a root `RUN_FINISHED` as `{ type, result }`
	// after persistence and a root `RUN_ERROR` as
	// `{ type, message, code? }` on failure. Forwarded lifecycle and
	// child-run events may contain `runId`, `threadId`, and
	// `parentRunId`. Clients should ignore unknown event names.
	//
	SSEEvent *stream.EventStream[components.SSEEvent]
}

func (r *RegenerateAnswerResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *RegenerateAnswerResponse) GetSSEEvent() *stream.EventStream[components.SSEEvent] {
	if r == nil {
		return nil
	}
	return r.SSEEvent
}
