// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type SetAgentConversationProjectVisibilityVisibility string

const (
	SetAgentConversationProjectVisibilityVisibilityPrivate SetAgentConversationProjectVisibilityVisibility = "private"
	SetAgentConversationProjectVisibilityVisibilityProject SetAgentConversationProjectVisibilityVisibility = "project"
)

func (e SetAgentConversationProjectVisibilityVisibility) ToPointer() *SetAgentConversationProjectVisibilityVisibility {
	return &e
}
func (e *SetAgentConversationProjectVisibilityVisibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private":
		fallthrough
	case "project":
		*e = SetAgentConversationProjectVisibilityVisibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SetAgentConversationProjectVisibilityVisibility: %v", v)
	}
}

type SetAgentConversationProjectVisibilityRequestBody struct {
	Visibility SetAgentConversationProjectVisibilityVisibility `json:"visibility"`
}

func (s *SetAgentConversationProjectVisibilityRequestBody) GetVisibility() SetAgentConversationProjectVisibilityVisibility {
	if s == nil {
		return SetAgentConversationProjectVisibilityVisibility("")
	}
	return s.Visibility
}

type SetAgentConversationProjectVisibilityRequest struct {
	AgentKey       string                                           `pathParam:"style=simple,explode=false,name=agentKey"`
	ConversationID string                                           `pathParam:"style=simple,explode=false,name=conversationId"`
	Body           SetAgentConversationProjectVisibilityRequestBody `request:"mediaType=application/json"`
}

func (s *SetAgentConversationProjectVisibilityRequest) GetAgentKey() string {
	if s == nil {
		return ""
	}
	return s.AgentKey
}

func (s *SetAgentConversationProjectVisibilityRequest) GetConversationID() string {
	if s == nil {
		return ""
	}
	return s.ConversationID
}

func (s *SetAgentConversationProjectVisibilityRequest) GetBody() SetAgentConversationProjectVisibilityRequestBody {
	if s == nil {
		return SetAgentConversationProjectVisibilityRequestBody{}
	}
	return s.Body
}

type SetAgentConversationProjectVisibilityProjectVisibility string

const (
	SetAgentConversationProjectVisibilityProjectVisibilityPrivate SetAgentConversationProjectVisibilityProjectVisibility = "private"
	SetAgentConversationProjectVisibilityProjectVisibilityProject SetAgentConversationProjectVisibilityProjectVisibility = "project"
)

func (e SetAgentConversationProjectVisibilityProjectVisibility) ToPointer() *SetAgentConversationProjectVisibilityProjectVisibility {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetAgentConversationProjectVisibilityProjectVisibility) IsExact() bool {
	if e != nil {
		switch *e {
		case "private", "project":
			return true
		}
	}
	return false
}

// SetAgentConversationProjectVisibilityResponseBody - Agent conversation's project visibility updated
type SetAgentConversationProjectVisibilityResponseBody struct {
	ConversationID    string                                                 `json:"conversationId"`
	ProjectVisibility SetAgentConversationProjectVisibilityProjectVisibility `json:"projectVisibility"`
}

func (s *SetAgentConversationProjectVisibilityResponseBody) GetConversationID() string {
	if s == nil {
		return ""
	}
	return s.ConversationID
}

func (s *SetAgentConversationProjectVisibilityResponseBody) GetProjectVisibility() SetAgentConversationProjectVisibilityProjectVisibility {
	if s == nil {
		return SetAgentConversationProjectVisibilityProjectVisibility("")
	}
	return s.ProjectVisibility
}

type SetAgentConversationProjectVisibilityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Agent conversation's project visibility updated
	Object *SetAgentConversationProjectVisibilityResponseBody
}

func (s SetAgentConversationProjectVisibilityResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetAgentConversationProjectVisibilityResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SetAgentConversationProjectVisibilityResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SetAgentConversationProjectVisibilityResponse) GetObject() *SetAgentConversationProjectVisibilityResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
