// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

type SetAgentConversationProjectRequestBody struct {
	// Target project id, or `null` to unlink.
	ProjectID *string `json:"projectId"`
}

func (s *SetAgentConversationProjectRequestBody) GetProjectID() *string {
	if s == nil {
		return nil
	}
	return s.ProjectID
}

type SetAgentConversationProjectRequest struct {
	AgentKey       string                                 `pathParam:"style=simple,explode=false,name=agentKey"`
	ConversationID string                                 `pathParam:"style=simple,explode=false,name=conversationId"`
	Body           SetAgentConversationProjectRequestBody `request:"mediaType=application/json"`
}

func (s *SetAgentConversationProjectRequest) GetAgentKey() string {
	if s == nil {
		return ""
	}
	return s.AgentKey
}

func (s *SetAgentConversationProjectRequest) GetConversationID() string {
	if s == nil {
		return ""
	}
	return s.ConversationID
}

func (s *SetAgentConversationProjectRequest) GetBody() SetAgentConversationProjectRequestBody {
	if s == nil {
		return SetAgentConversationProjectRequestBody{}
	}
	return s.Body
}

type SetAgentConversationProjectProjectVisibility string

const (
	SetAgentConversationProjectProjectVisibilityPrivate SetAgentConversationProjectProjectVisibility = "private"
	SetAgentConversationProjectProjectVisibilityProject SetAgentConversationProjectProjectVisibility = "project"
)

func (e SetAgentConversationProjectProjectVisibility) ToPointer() *SetAgentConversationProjectProjectVisibility {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetAgentConversationProjectProjectVisibility) IsExact() bool {
	if e != nil {
		switch *e {
		case "private", "project":
			return true
		}
	}
	return false
}

// SetAgentConversationProjectResponseBody - Agent conversation's project link updated
type SetAgentConversationProjectResponseBody struct {
	ConversationID    string                                                                          `json:"conversationId"`
	ProjectID         optionalnullable.OptionalNullable[string]                                       `json:"projectId,omitzero"`
	ProjectVisibility optionalnullable.OptionalNullable[SetAgentConversationProjectProjectVisibility] `json:"projectVisibility,omitzero"`
}

func (s *SetAgentConversationProjectResponseBody) GetConversationID() string {
	if s == nil {
		return ""
	}
	return s.ConversationID
}

func (s *SetAgentConversationProjectResponseBody) GetProjectID() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.ProjectID
}

func (s *SetAgentConversationProjectResponseBody) GetProjectVisibility() optionalnullable.OptionalNullable[SetAgentConversationProjectProjectVisibility] {
	if s == nil {
		return nil
	}
	return s.ProjectVisibility
}

type SetAgentConversationProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Agent conversation's project link updated
	Object *SetAgentConversationProjectResponseBody
}

func (s SetAgentConversationProjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetAgentConversationProjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SetAgentConversationProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SetAgentConversationProjectResponse) GetObject() *SetAgentConversationProjectResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
