// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type SetConversationProjectVisibilityVisibility string

const (
	SetConversationProjectVisibilityVisibilityPrivate SetConversationProjectVisibilityVisibility = "private"
	SetConversationProjectVisibilityVisibilityProject SetConversationProjectVisibilityVisibility = "project"
)

func (e SetConversationProjectVisibilityVisibility) ToPointer() *SetConversationProjectVisibilityVisibility {
	return &e
}
func (e *SetConversationProjectVisibilityVisibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private":
		fallthrough
	case "project":
		*e = SetConversationProjectVisibilityVisibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SetConversationProjectVisibilityVisibility: %v", v)
	}
}

type SetConversationProjectVisibilityRequestBody struct {
	Visibility SetConversationProjectVisibilityVisibility `json:"visibility"`
}

func (s *SetConversationProjectVisibilityRequestBody) GetVisibility() SetConversationProjectVisibilityVisibility {
	if s == nil {
		return SetConversationProjectVisibilityVisibility("")
	}
	return s.Visibility
}

type SetConversationProjectVisibilityRequest struct {
	// Unique conversation identifier
	ConversationID string                                      `pathParam:"style=simple,explode=false,name=conversationId"`
	Body           SetConversationProjectVisibilityRequestBody `request:"mediaType=application/json"`
}

func (s *SetConversationProjectVisibilityRequest) GetConversationID() string {
	if s == nil {
		return ""
	}
	return s.ConversationID
}

func (s *SetConversationProjectVisibilityRequest) GetBody() SetConversationProjectVisibilityRequestBody {
	if s == nil {
		return SetConversationProjectVisibilityRequestBody{}
	}
	return s.Body
}

type SetConversationProjectVisibilityProjectVisibility string

const (
	SetConversationProjectVisibilityProjectVisibilityPrivate SetConversationProjectVisibilityProjectVisibility = "private"
	SetConversationProjectVisibilityProjectVisibilityProject SetConversationProjectVisibilityProjectVisibility = "project"
)

func (e SetConversationProjectVisibilityProjectVisibility) ToPointer() *SetConversationProjectVisibilityProjectVisibility {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SetConversationProjectVisibilityProjectVisibility) IsExact() bool {
	if e != nil {
		switch *e {
		case "private", "project":
			return true
		}
	}
	return false
}

// SetConversationProjectVisibilityResponseBody - Conversation's project visibility updated
type SetConversationProjectVisibilityResponseBody struct {
	ConversationID    string                                            `json:"conversationId"`
	ProjectVisibility SetConversationProjectVisibilityProjectVisibility `json:"projectVisibility"`
}

func (s *SetConversationProjectVisibilityResponseBody) GetConversationID() string {
	if s == nil {
		return ""
	}
	return s.ConversationID
}

func (s *SetConversationProjectVisibilityResponseBody) GetProjectVisibility() SetConversationProjectVisibilityProjectVisibility {
	if s == nil {
		return SetConversationProjectVisibilityProjectVisibility("")
	}
	return s.ProjectVisibility
}

type SetConversationProjectVisibilityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Conversation's project visibility updated
	Object *SetConversationProjectVisibilityResponseBody
}

func (s SetConversationProjectVisibilityResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetConversationProjectVisibilityResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SetConversationProjectVisibilityResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SetConversationProjectVisibilityResponse) GetObject() *SetConversationProjectVisibilityResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
