// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type UpdateAgentRequest struct {
	// Unique agent identifier
	AgentKey string `pathParam:"style=simple,explode=false,name=agentKey"`
	// Partial agent configuration fields to update
	Body components.AgentUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateAgentRequest) GetAgentKey() string {
	if u == nil {
		return ""
	}
	return u.AgentKey
}

func (u *UpdateAgentRequest) GetBody() components.AgentUpdateRequest {
	if u == nil {
		return components.AgentUpdateRequest{}
	}
	return u.Body
}

type UpdateAgentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Agent updated successfully
	AgentUpdateResponse *components.AgentUpdateResponse
}

func (u UpdateAgentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAgentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAgentResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAgentResponse) GetAgentUpdateResponse() *components.AgentUpdateResponse {
	if u == nil {
		return nil
	}
	return u.AgentUpdateResponse
}
