// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// UpdateKnowledgeBaseRequestBody - Fields to update. `kbName` is optional; an empty object is valid.
type UpdateKnowledgeBaseRequestBody struct {
	// New name for the knowledge base
	KbName *string `json:"kbName,omitzero"`
}

func (u *UpdateKnowledgeBaseRequestBody) GetKbName() *string {
	if u == nil {
		return nil
	}
	return u.KbName
}

type UpdateKnowledgeBaseRequest struct {
	// Knowledge base ID (UUID)
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
	// Fields to update. `kbName` is optional; an empty object is valid.
	Body UpdateKnowledgeBaseRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateKnowledgeBaseRequest) GetKbID() string {
	if u == nil {
		return ""
	}
	return u.KbID
}

func (u *UpdateKnowledgeBaseRequest) GetBody() UpdateKnowledgeBaseRequestBody {
	if u == nil {
		return UpdateKnowledgeBaseRequestBody{}
	}
	return u.Body
}

type UpdateKnowledgeBaseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Knowledge base updated successfully
	UpdateKnowledgeBaseByID *components.UpdateKnowledgeBaseByID
}

func (u UpdateKnowledgeBaseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateKnowledgeBaseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateKnowledgeBaseResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateKnowledgeBaseResponse) GetUpdateKnowledgeBaseByID() *components.UpdateKnowledgeBaseByID {
	if u == nil {
		return nil
	}
	return u.UpdateKnowledgeBaseByID
}
