// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type UpdateAgentConversationTitleRequest struct {
	AgentKey       string `pathParam:"style=simple,explode=false,name=agentKey"`
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// New title for the agent conversation.
	//
	// The server trims the provided string before saving it.
	//
	Body components.ConversationTitleUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateAgentConversationTitleRequest) GetAgentKey() string {
	if u == nil {
		return ""
	}
	return u.AgentKey
}

func (u *UpdateAgentConversationTitleRequest) GetConversationID() string {
	if u == nil {
		return ""
	}
	return u.ConversationID
}

func (u *UpdateAgentConversationTitleRequest) GetBody() components.ConversationTitleUpdateRequest {
	if u == nil {
		return components.ConversationTitleUpdateRequest{}
	}
	return u.Body
}

type UpdateAgentConversationTitleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Title updated successfully
	AgentConversationTitleUpdateResponse *components.AgentConversationTitleUpdateResponse
}

func (u UpdateAgentConversationTitleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAgentConversationTitleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAgentConversationTitleResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAgentConversationTitleResponse) GetAgentConversationTitleUpdateResponse() *components.AgentConversationTitleUpdateResponse {
	if u == nil {
		return nil
	}
	return u.AgentConversationTitleUpdateResponse
}
