// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"github.com/pipeshub-ai/pipeshub-sdk-go/types/stream"
)

type UploadRecordsFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (u *UploadRecordsFile) GetFileName() string {
	if u == nil {
		return ""
	}
	return u.FileName
}

func (u *UploadRecordsFile) GetContent() any {
	if u == nil {
		return nil
	}
	return u.Content
}

// UploadRecordsRequestBody - Request payload
type UploadRecordsRequestBody struct {
	// Files to upload (max 1000)
	Files []UploadRecordsFile `multipartForm:"file,name=files"`
	// JSON array with file_path and last_modified for each file
	FilesMetadata *string `multipartForm:"name=files_metadata"`
	// Enable version tracking
	IsVersioned *bool `default:"true" multipartForm:"name=isVersioned"`
	// Type of records to create
	RecordType *string `default:"FILE" multipartForm:"name=recordType"`
}

func (u UploadRecordsRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadRecordsRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadRecordsRequestBody) GetFiles() []UploadRecordsFile {
	if u == nil {
		return []UploadRecordsFile{}
	}
	return u.Files
}

func (u *UploadRecordsRequestBody) GetFilesMetadata() *string {
	if u == nil {
		return nil
	}
	return u.FilesMetadata
}

func (u *UploadRecordsRequestBody) GetIsVersioned() *bool {
	if u == nil {
		return nil
	}
	return u.IsVersioned
}

func (u *UploadRecordsRequestBody) GetRecordType() *string {
	if u == nil {
		return nil
	}
	return u.RecordType
}

type UploadRecordsRequest struct {
	// Knowledge base ID
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
	// Target folder ID. Omit to upload to the KB root.
	FolderID *string `queryParam:"style=form,explode=true,name=folderId"`
	// Request payload
	Body UploadRecordsRequestBody `request:"mediaType=multipart/form-data"`
}

func (u *UploadRecordsRequest) GetKbID() string {
	if u == nil {
		return ""
	}
	return u.KbID
}

func (u *UploadRecordsRequest) GetFolderID() *string {
	if u == nil {
		return nil
	}
	return u.FolderID
}

func (u *UploadRecordsRequest) GetBody() UploadRecordsRequestBody {
	if u == nil {
		return UploadRecordsRequestBody{}
	}
	return u.Body
}

type UploadRecordsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SSE stream (`text/event-stream`) of per-file upload outcomes. The
	// stream emits `file:succeeded` / `file:failed` per file and a final
	// `done` summary, then closes. See `UploadStreamSSEEvent`.
	//
	UploadStreamSSEEvent *stream.EventStream[components.UploadStreamSSEEvent]
}

func (u *UploadRecordsResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UploadRecordsResponse) GetUploadStreamSSEEvent() *stream.EventStream[components.UploadStreamSSEEvent] {
	if u == nil {
		return nil
	}
	return u.UploadStreamSSEEvent
}
