// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	pipeshub "github.com/pipeshub-ai/pipeshub-sdk-go"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestOrganizations_GetCurrentOrganization(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("getCurrentOrganization")

	s := pipeshub.New(
		pipeshub.WithServerURL(utils.GetEnv("PIPESHUB_API_URL", "http://localhost:3000/api/v1")),
		pipeshub.WithSecurity(components.Security{
			Oauth2: &components.SchemeOauth2{
				ClientID:     utils.GetEnv("PIPESHUB_CLIENT_ID", "value"),
				ClientSecret: utils.GetEnv("PIPESHUB_CLIENT_SECRET", "value"),
				TokenURL:     utils.GetEnv("PIPESHUB_TOKEN_URL", "http://localhost:3000/api/v1/oauth2/token"),
			},
		}),
		pipeshub.WithClient(testHTTPClient),
	)

	res, err := s.Organizations.GetCurrentOrganization(ctx)
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}
