// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ActivateOAuthAppResponse - Response body for `POST /oauth-clients/{appId}/activate`
// (`oauth.app.controller.ts` `activateApp`). Re-activated app (never includes
// `clientSecret`) is nested under `app`.
type ActivateOAuthAppResponse struct {
	Message string `json:"message"`
	// OAuth app details (without secret). Fields under `required:` always appear
	// in `toAppResponse` (`oauth.app.service.ts`); optional URL/description fields
	// are only present when set by the caller.
	//
	App OAuthAppResponse `json:"app"`
}

func (a *ActivateOAuthAppResponse) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}

func (a *ActivateOAuthAppResponse) GetApp() OAuthAppResponse {
	if a == nil {
		return OAuthAppResponse{}
	}
	return a.App
}
