// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// AddMessageRequestChatMode - Optional execution mode for non-stream consumers of this shared
// request schema.
type AddMessageRequestChatMode string

const (
	AddMessageRequestChatModeAgent          AddMessageRequestChatMode = "agent"
	AddMessageRequestChatModeInternalSearch AddMessageRequestChatMode = "internal_search"
	AddMessageRequestChatModeWebSearch      AddMessageRequestChatMode = "web_search"
)

func (e AddMessageRequestChatMode) ToPointer() *AddMessageRequestChatMode {
	return &e
}
func (e *AddMessageRequestChatMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agent":
		fallthrough
	case "internal_search":
		fallthrough
	case "web_search":
		*e = AddMessageRequestChatMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AddMessageRequestChatMode: %v", v)
	}
}

// AddMessageRequestProtocol - AG-UI is the only supported wire protocol. When present must be
// `"agui"`. Omitting the field is equivalent — the server always
// uses the AG-UI vocabulary (see `ConversationMessageStreamSSEEvent`).
// Kept in the schema for backward compatibility with callers that
// already send it.
type AddMessageRequestProtocol string

const (
	AddMessageRequestProtocolAgui AddMessageRequestProtocol = "agui"
)

func (e AddMessageRequestProtocol) ToPointer() *AddMessageRequestProtocol {
	return &e
}
func (e *AddMessageRequestProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agui":
		*e = AddMessageRequestProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AddMessageRequestProtocol: %v", v)
	}
}

// AddMessageRequest - Request body for adding a message to an existing conversation
type AddMessageRequest struct {
	// The follow-up question or message content
	Query string `json:"query"`
	// App connector instance ids and knowledge-base / record-group ids that narrow retrieval
	// for a turn. For **org assistant** chat streams, send explicit `apps` / `kb` lists.
	// For **agent** chat streams, send explicit id lists, or **omit** `filters` (and `tools`)
	// to let the service use the agent’s stored knowledge and tool configuration. Sending
	// `{ "apps": [], "kb": [] }` on an agent stream means **no** knowledge sources for that
	// turn (it is not “full org default”).
	//
	Filters *Filters `json:"filters,omitzero"`
	// Rich filter state selected by the user, used for display and persistence only.
	// This mirrors the active selection shown in the UI and is distinct from the
	// machine-readable `filters` field used for retrieval scoping.
	//
	AppliedFilters *AppliedFilters `json:"appliedFilters,omitzero"`
	// Uploaded chat attachments for this follow-up turn (see
	// `POST /conversations/attachments/upload`).
	//
	Attachments []ChatAttachmentRef `json:"attachments,omitzero"`
	// Override the model for this specific message
	ModelKey *string `json:"modelKey,omitzero"`
	// Display name of the model
	ModelName *string `json:"modelName,omitzero"`
	// Friendly display name of the model
	ModelFriendlyName *string `json:"modelFriendlyName,omitzero"`
	// Optional execution mode for non-stream consumers of this shared
	// request schema.
	//
	ChatMode *AddMessageRequestChatMode `json:"chatMode,omitzero"`
	// IANA timezone identifier from the client (top-level field).
	// Used to provide time-aware context to the AI.
	//
	Timezone *string `json:"timezone,omitzero"`
	// ISO 8601 / RFC 3339 datetime from the client (top-level field; UTC `Z` or numeric offset).
	//
	CurrentTime *time.Time `json:"currentTime,omitzero"`
	// Optional list of tool identifiers the agent may invoke for this
	// follow-up message. Semantics are identical to the create-conversation
	// tools field.
	//
	Tools []string `json:"tools,omitzero"`
	// AG-UI is the only supported wire protocol. When present must be
	// `"agui"`. Omitting the field is equivalent — the server always
	// uses the AG-UI vocabulary (see `ConversationMessageStreamSSEEvent`).
	// Kept in the schema for backward compatibility with callers that
	// already send it.
	//
	Protocol *AddMessageRequestProtocol `json:"protocol,omitzero"`
	// Per-request agent capability toggles. Only meaningful when `chatMode`
	// selects an agent mode; ignored otherwise. Each field falls back to its
	// own `default` below when omitted — a missing flag is not uniformly
	// `true`. Omitting the whole object applies every default.
	//
	AgentCapabilities *AgentCapabilities `json:"agentCapabilities,omitzero"`
	// Client-generated identifier for this run. Send it here to enable
	// `POST /conversations/{conversationId}/cancel {runId}` while the
	// stream is still generating.
	//
	RunID *string `json:"runId,omitzero"`
}

func (a AddMessageRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddMessageRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddMessageRequest) GetQuery() string {
	if a == nil {
		return ""
	}
	return a.Query
}

func (a *AddMessageRequest) GetFilters() *Filters {
	if a == nil {
		return nil
	}
	return a.Filters
}

func (a *AddMessageRequest) GetAppliedFilters() *AppliedFilters {
	if a == nil {
		return nil
	}
	return a.AppliedFilters
}

func (a *AddMessageRequest) GetAttachments() []ChatAttachmentRef {
	if a == nil {
		return nil
	}
	return a.Attachments
}

func (a *AddMessageRequest) GetModelKey() *string {
	if a == nil {
		return nil
	}
	return a.ModelKey
}

func (a *AddMessageRequest) GetModelName() *string {
	if a == nil {
		return nil
	}
	return a.ModelName
}

func (a *AddMessageRequest) GetModelFriendlyName() *string {
	if a == nil {
		return nil
	}
	return a.ModelFriendlyName
}

func (a *AddMessageRequest) GetChatMode() *AddMessageRequestChatMode {
	if a == nil {
		return nil
	}
	return a.ChatMode
}

func (a *AddMessageRequest) GetTimezone() *string {
	if a == nil {
		return nil
	}
	return a.Timezone
}

func (a *AddMessageRequest) GetCurrentTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.CurrentTime
}

func (a *AddMessageRequest) GetTools() []string {
	if a == nil {
		return nil
	}
	return a.Tools
}

func (a *AddMessageRequest) GetProtocol() *AddMessageRequestProtocol {
	if a == nil {
		return nil
	}
	return a.Protocol
}

func (a *AddMessageRequest) GetAgentCapabilities() *AgentCapabilities {
	if a == nil {
		return nil
	}
	return a.AgentCapabilities
}

func (a *AddMessageRequest) GetRunID() *string {
	if a == nil {
		return nil
	}
	return a.RunID
}
