// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

type AddMessageResponseMeta struct {
	// Request correlation id. Omitted when upstream middleware did
	// not set `req.context.requestId`.
	//
	RequestID *string `json:"requestId,omitzero"`
	// Server timestamp when the response was sent.
	Timestamp time.Time `json:"timestamp"`
	// Total handler duration in milliseconds.
	Duration int64 `json:"duration"`
	// Same value as the top-level `recordsUsed`. Duplicated inside
	// `meta` for client convenience.
	//
	RecordsUsed *int64 `json:"recordsUsed,omitzero"`
}

func (a AddMessageResponseMeta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddMessageResponseMeta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddMessageResponseMeta) GetRequestID() *string {
	if a == nil {
		return nil
	}
	return a.RequestID
}

func (a *AddMessageResponseMeta) GetTimestamp() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.Timestamp
}

func (a *AddMessageResponseMeta) GetDuration() int64 {
	if a == nil {
		return 0
	}
	return a.Duration
}

func (a *AddMessageResponseMeta) GetRecordsUsed() *int64 {
	if a == nil {
		return nil
	}
	return a.RecordsUsed
}

// AddMessageResponse - Envelope returned by `POST /conversations/{conversationId}/messages`.
// Contains the updated conversation, the number of citation records used
// to ground the AI response for this turn, and request metadata.
type AddMessageResponse struct {
	// A conversation represents a chat session between a user and the AI.
	// Conversations maintain context across multiple messages and can be
	// shared, archived, and organized.
	//
	Conversation Conversation `json:"conversation"`
	// Number of citation records used to ground the AI response generated
	// for this turn.
	//
	RecordsUsed int64                  `json:"recordsUsed"`
	Meta        AddMessageResponseMeta `json:"meta"`
}

func (a *AddMessageResponse) GetConversation() Conversation {
	if a == nil {
		return Conversation{}
	}
	return a.Conversation
}

func (a *AddMessageResponse) GetRecordsUsed() int64 {
	if a == nil {
		return 0
	}
	return a.RecordsUsed
}

func (a *AddMessageResponse) GetMeta() AddMessageResponseMeta {
	if a == nil {
		return AddMessageResponseMeta{}
	}
	return a.Meta
}
