// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdminPatListResponsePagination struct {
	Page int64 `json:"page"`
	// Items per page (max 100)
	Limit      int64 `json:"limit"`
	Total      int64 `json:"total"`
	TotalPages int64 `json:"totalPages"`
}

func (a *AdminPatListResponsePagination) GetPage() int64 {
	if a == nil {
		return 0
	}
	return a.Page
}

func (a *AdminPatListResponsePagination) GetLimit() int64 {
	if a == nil {
		return 0
	}
	return a.Limit
}

func (a *AdminPatListResponsePagination) GetTotal() int64 {
	if a == nil {
		return 0
	}
	return a.Total
}

func (a *AdminPatListResponsePagination) GetTotalPages() int64 {
	if a == nil {
		return 0
	}
	return a.TotalPages
}

// AdminPatListResponse - Response body for `GET /personal-access-tokens/admin` (`adminListTokens`).
// Paginated — unlike the self-service `ListPatResponse` — since an org
// can have far more active tokens than a fixed-window cap's worth.
type AdminPatListResponse struct {
	Data       []AdminPatListItem             `json:"data"`
	Pagination AdminPatListResponsePagination `json:"pagination"`
}

func (a *AdminPatListResponse) GetData() []AdminPatListItem {
	if a == nil {
		return []AdminPatListItem{}
	}
	return a.Data
}

func (a *AdminPatListResponse) GetPagination() AdminPatListResponsePagination {
	if a == nil {
		return AdminPatListResponsePagination{}
	}
	return a.Pagination
}
