// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentArchivedGroupsResponse - Response from `GET /agents/conversations/show/archives` — archived agent
// conversations grouped by `agentKey`, with agent-level pagination over
// the groups and a fixed slice of conversations under each agent.
type AgentArchivedGroupsResponse struct {
	Groups []AgentArchivedConversationGroup `json:"groups"`
	// Pagination block emitted by `buildPaginationMetadata` (utils.ts:417).
	// `totalPages` is `Math.ceil(totalCount / limit)`, so an empty result
	// has `totalPages: 0`, not `1`.
	//
	AgentPagination SemanticSearchHistoryPagination `json:"agentPagination"`
	// Basic request metadata returned by the API.
	Meta RequestMeta `json:"meta"`
}

func (a *AgentArchivedGroupsResponse) GetGroups() []AgentArchivedConversationGroup {
	if a == nil {
		return []AgentArchivedConversationGroup{}
	}
	return a.Groups
}

func (a *AgentArchivedGroupsResponse) GetAgentPagination() SemanticSearchHistoryPagination {
	if a == nil {
		return SemanticSearchHistoryPagination{}
	}
	return a.AgentPagination
}

func (a *AgentArchivedGroupsResponse) GetMeta() RequestMeta {
	if a == nil {
		return RequestMeta{}
	}
	return a.Meta
}
