// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

// AgentListItemWebSearch - Web-search provider attachment for this agent, or `null` when none is attached.
//
// For `GET /agents`, the response formatter always emits `provider`.
// It may also emit `providerKey` and `providerLabel` when those values
// were present on the stored attachment. It does not emit `iconPath`
// on this response path.
type AgentListItemWebSearch struct {
	Provider      *string `json:"provider,omitzero"`
	ProviderKey   *string `json:"providerKey,omitzero"`
	ProviderLabel *string `json:"providerLabel,omitzero"`
}

func (a *AgentListItemWebSearch) GetProvider() *string {
	if a == nil {
		return nil
	}
	return a.Provider
}

func (a *AgentListItemWebSearch) GetProviderKey() *string {
	if a == nil {
		return nil
	}
	return a.ProviderKey
}

func (a *AgentListItemWebSearch) GetProviderLabel() *string {
	if a == nil {
		return nil
	}
	return a.ProviderLabel
}

// AgentListItem - Agent projection returned by `GET /agents`.
//
// This is the list-view envelope item emitted by the Python backend and
// forwarded by the Node gateway. It is not the full detail projection
// used by `GET /agents/{agentKey}`.
type AgentListItem struct {
	// Full document id in the backing graph store.
	ID string `json:"_id"`
	// Stable agent key used in route params.
	Key string `json:"_key"`
	// Backend document revision token.
	Rev *string `json:"_rev,omitzero"`
	// Unix epoch timestamp in milliseconds when the agent was created.
	CreatedAtTimestamp int64 `json:"createdAtTimestamp"`
	// User id of the creator.
	CreatedBy string `json:"createdBy"`
	// Short human-readable description of the agent.
	Description optionalnullable.OptionalNullable[string] `json:"description,omitzero"`
	// Additional execution instructions stored on the agent.
	Instructions optionalnullable.OptionalNullable[string] `json:"instructions,omitzero"`
	// Whether the agent is active.
	IsActive bool `json:"isActive"`
	// Whether the agent has been soft-deleted.
	IsDeleted bool `json:"isDeleted"`
	// Whether this agent is a service-account agent.
	IsServiceAccount bool `json:"isServiceAccount"`
	// Model entries configured on the agent.
	//
	// For `GET /agents`, the backend returns the stored normalized string
	// representation, typically `modelKey_modelName`.
	//
	Models []string `json:"models"`
	// Display name of the agent.
	Name string `json:"name"`
	// Greeting shown at conversation start.
	StartMessage optionalnullable.OptionalNullable[string] `json:"startMessage,omitzero"`
	// System prompt stored on the agent.
	SystemPrompt optionalnullable.OptionalNullable[string] `json:"systemPrompt,omitzero"`
	// Free-form agent tags.
	Tags []string `json:"tags"`
	// Unix epoch timestamp in milliseconds when the agent was last updated.
	UpdatedAtTimestamp int64 `json:"updatedAtTimestamp"`
	// User id of the last updater, if present.
	UpdatedBy optionalnullable.OptionalNullable[string] `json:"updatedBy,omitzero"`
	// Web-search provider attachment for this agent, or `null` when none is attached.
	//
	// For `GET /agents`, the response formatter always emits `provider`.
	// It may also emit `providerKey` and `providerLabel` when those values
	// were present on the stored attachment. It does not emit `iconPath`
	// on this response path.
	//
	WebSearch optionalnullable.OptionalNullable[AgentListItemWebSearch] `json:"webSearch,omitzero"`
	// Whether the agent is shared with the organization.
	ShareWithOrg bool `json:"shareWithOrg"`
	// Effective permission to view the agent.
	CanView bool `json:"can_view"`
	// Effective permission to share the agent.
	CanShare bool `json:"can_share"`
	// Effective permission to edit the agent.
	CanEdit bool `json:"can_edit"`
	// Effective permission to delete the agent.
	CanDelete bool `json:"can_delete"`
	// Effective role of the current user on this agent.
	UserRole string `json:"user_role"`
	// How the user can access this agent.
	AccessType string `json:"access_type"`
}

func (a AgentListItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentListItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentListItem) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AgentListItem) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

func (a *AgentListItem) GetRev() *string {
	if a == nil {
		return nil
	}
	return a.Rev
}

func (a *AgentListItem) GetCreatedAtTimestamp() int64 {
	if a == nil {
		return 0
	}
	return a.CreatedAtTimestamp
}

func (a *AgentListItem) GetCreatedBy() string {
	if a == nil {
		return ""
	}
	return a.CreatedBy
}

func (a *AgentListItem) GetDescription() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AgentListItem) GetInstructions() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.Instructions
}

func (a *AgentListItem) GetIsActive() bool {
	if a == nil {
		return false
	}
	return a.IsActive
}

func (a *AgentListItem) GetIsDeleted() bool {
	if a == nil {
		return false
	}
	return a.IsDeleted
}

func (a *AgentListItem) GetIsServiceAccount() bool {
	if a == nil {
		return false
	}
	return a.IsServiceAccount
}

func (a *AgentListItem) GetModels() []string {
	if a == nil {
		return []string{}
	}
	return a.Models
}

func (a *AgentListItem) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AgentListItem) GetStartMessage() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.StartMessage
}

func (a *AgentListItem) GetSystemPrompt() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.SystemPrompt
}

func (a *AgentListItem) GetTags() []string {
	if a == nil {
		return []string{}
	}
	return a.Tags
}

func (a *AgentListItem) GetUpdatedAtTimestamp() int64 {
	if a == nil {
		return 0
	}
	return a.UpdatedAtTimestamp
}

func (a *AgentListItem) GetUpdatedBy() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.UpdatedBy
}

func (a *AgentListItem) GetWebSearch() optionalnullable.OptionalNullable[AgentListItemWebSearch] {
	if a == nil {
		return nil
	}
	return a.WebSearch
}

func (a *AgentListItem) GetShareWithOrg() bool {
	if a == nil {
		return false
	}
	return a.ShareWithOrg
}

func (a *AgentListItem) GetCanView() bool {
	if a == nil {
		return false
	}
	return a.CanView
}

func (a *AgentListItem) GetCanShare() bool {
	if a == nil {
		return false
	}
	return a.CanShare
}

func (a *AgentListItem) GetCanEdit() bool {
	if a == nil {
		return false
	}
	return a.CanEdit
}

func (a *AgentListItem) GetCanDelete() bool {
	if a == nil {
		return false
	}
	return a.CanDelete
}

func (a *AgentListItem) GetUserRole() string {
	if a == nil {
		return ""
	}
	return a.UserRole
}

func (a *AgentListItem) GetAccessType() string {
	if a == nil {
		return ""
	}
	return a.AccessType
}
