// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// AgentConversationArchiveMeta - Request-scoped metadata returned by the archive route. `requestId` is
// omitted when upstream middleware did not attach one.
type AgentConversationArchiveMeta struct {
	RequestID *string   `json:"requestId,omitzero"`
	Timestamp time.Time `json:"timestamp"`
	Duration  int64     `json:"duration"`
}

func (a AgentConversationArchiveMeta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentConversationArchiveMeta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentConversationArchiveMeta) GetRequestID() *string {
	if a == nil {
		return nil
	}
	return a.RequestID
}

func (a *AgentConversationArchiveMeta) GetTimestamp() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.Timestamp
}

func (a *AgentConversationArchiveMeta) GetDuration() int64 {
	if a == nil {
		return 0
	}
	return a.Duration
}
