// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type AgentCreateModelEntry struct {
	ModelKey    string  `json:"modelKey"`
	ModelName   *string `json:"modelName,omitzero"`
	Provider    *string `json:"provider,omitzero"`
	IsReasoning *bool   `json:"isReasoning,omitzero"`
}

func (a AgentCreateModelEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentCreateModelEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentCreateModelEntry) GetModelKey() string {
	if a == nil {
		return ""
	}
	return a.ModelKey
}

func (a *AgentCreateModelEntry) GetModelName() *string {
	if a == nil {
		return nil
	}
	return a.ModelName
}

func (a *AgentCreateModelEntry) GetProvider() *string {
	if a == nil {
		return nil
	}
	return a.Provider
}

func (a *AgentCreateModelEntry) GetIsReasoning() *bool {
	if a == nil {
		return nil
	}
	return a.IsReasoning
}

type AgentCreateModelEntryUnionType string

const (
	AgentCreateModelEntryUnionTypeStr                   AgentCreateModelEntryUnionType = "str"
	AgentCreateModelEntryUnionTypeAgentCreateModelEntry AgentCreateModelEntryUnionType = "AgentCreateModelEntry"
)

// AgentCreateModelEntryUnion - Accepted model entry for `POST /agents/create`.
// The gateway accepts either a non-empty string model entry or an object entry
// with a required `modelKey`.
//
// The `models` array must include at least one object entry with `isReasoning: true`.
// String-only entries are schema-valid but are rejected at the gateway with HTTP 400.
type AgentCreateModelEntryUnion struct {
	Str                   *string                `queryParam:"inline" union:"member"`
	AgentCreateModelEntry *AgentCreateModelEntry `queryParam:"inline" union:"member"`

	Type AgentCreateModelEntryUnionType
}

func CreateAgentCreateModelEntryUnionStr(str string) AgentCreateModelEntryUnion {
	typ := AgentCreateModelEntryUnionTypeStr

	return AgentCreateModelEntryUnion{
		Str:  &str,
		Type: typ,
	}
}

func CreateAgentCreateModelEntryUnionAgentCreateModelEntry(agentCreateModelEntry AgentCreateModelEntry) AgentCreateModelEntryUnion {
	typ := AgentCreateModelEntryUnionTypeAgentCreateModelEntry

	return AgentCreateModelEntryUnion{
		AgentCreateModelEntry: &agentCreateModelEntry,
		Type:                  typ,
	}
}

func (u *AgentCreateModelEntryUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AgentCreateModelEntryUnionTypeStr,
			Value: &str,
		})
	}

	var agentCreateModelEntry AgentCreateModelEntry = AgentCreateModelEntry{}
	if err := utils.UnmarshalJSON(data, &agentCreateModelEntry, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AgentCreateModelEntryUnionTypeAgentCreateModelEntry,
			Value: &agentCreateModelEntry,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AgentCreateModelEntryUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AgentCreateModelEntryUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(AgentCreateModelEntryUnionType)
	switch best.Type {
	case AgentCreateModelEntryUnionTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case AgentCreateModelEntryUnionTypeAgentCreateModelEntry:
		u.AgentCreateModelEntry = best.Value.(*AgentCreateModelEntry)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AgentCreateModelEntryUnion", string(data))
}

func (u AgentCreateModelEntryUnion) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.AgentCreateModelEntry != nil {
		return utils.MarshalJSON(u.AgentCreateModelEntry, "", true)
	}

	return nil, errors.New("could not marshal union type AgentCreateModelEntryUnion: all fields are null")
}
