// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentConversationDetailAccessAccessLevel string

const (
	AgentConversationDetailAccessAccessLevelRead  AgentConversationDetailAccessAccessLevel = "read"
	AgentConversationDetailAccessAccessLevelWrite AgentConversationDetailAccessAccessLevel = "write"
)

func (e AgentConversationDetailAccessAccessLevel) ToPointer() *AgentConversationDetailAccessAccessLevel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentConversationDetailAccessAccessLevel) IsExact() bool {
	if e != nil {
		switch *e {
		case "read", "write":
			return true
		}
	}
	return false
}

type AgentConversationDetailAccess struct {
	IsOwner     *bool                                     `json:"isOwner,omitzero"`
	AccessLevel *AgentConversationDetailAccessAccessLevel `json:"accessLevel,omitzero"`
}

func (a *AgentConversationDetailAccess) GetIsOwner() *bool {
	if a == nil {
		return nil
	}
	return a.IsOwner
}

func (a *AgentConversationDetailAccess) GetAccessLevel() *AgentConversationDetailAccessAccessLevel {
	if a == nil {
		return nil
	}
	return a.AccessLevel
}
