// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentConversationListResponse - Envelope returned by `GET /agents/{agentKey}/conversations`.
// `conversations` contains rows owned by the caller for the agent;
// `sharedWithMeConversations` contains rows shared with the caller for
// the same agent. Both arrays use the same pagination and sort inputs,
// but `pagination.totalCount` and `totalPages` are computed only from
// `conversations` because the handler counts the owned-query filter only.
type AgentConversationListResponse struct {
	Conversations             []AgentConversationListItem `json:"conversations"`
	SharedWithMeConversations []AgentConversationListItem `json:"sharedWithMeConversations"`
	// Pagination block emitted by `buildPaginationMetadata` (utils.ts:417).
	// `totalPages` is `Math.ceil(totalCount / limit)`, so an empty result
	// has `totalPages: 0`, not `1`.
	//
	Pagination SemanticSearchHistoryPagination `json:"pagination"`
	Filters    SemanticSearchHistoryFilters    `json:"filters"`
	// `requestId` comes from `req.context?.requestId` and is omitted from
	// the JSON when upstream middleware did not set it.
	//
	Meta SemanticSearchHistoryMeta `json:"meta"`
}

func (a *AgentConversationListResponse) GetConversations() []AgentConversationListItem {
	if a == nil {
		return []AgentConversationListItem{}
	}
	return a.Conversations
}

func (a *AgentConversationListResponse) GetSharedWithMeConversations() []AgentConversationListItem {
	if a == nil {
		return []AgentConversationListItem{}
	}
	return a.SharedWithMeConversations
}

func (a *AgentConversationListResponse) GetPagination() SemanticSearchHistoryPagination {
	if a == nil {
		return SemanticSearchHistoryPagination{}
	}
	return a.Pagination
}

func (a *AgentConversationListResponse) GetFilters() SemanticSearchHistoryFilters {
	if a == nil {
		return SemanticSearchHistoryFilters{}
	}
	return a.Filters
}

func (a *AgentConversationListResponse) GetMeta() SemanticSearchHistoryMeta {
	if a == nil {
		return SemanticSearchHistoryMeta{}
	}
	return a.Meta
}
