// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
	"time"
)

type AgentConversationListItemStatus string

const (
	AgentConversationListItemStatusNone       AgentConversationListItemStatus = "None"
	AgentConversationListItemStatusInprogress AgentConversationListItemStatus = "Inprogress"
	AgentConversationListItemStatusComplete   AgentConversationListItemStatus = "Complete"
	AgentConversationListItemStatusFailed     AgentConversationListItemStatus = "Failed"
)

func (e AgentConversationListItemStatus) ToPointer() *AgentConversationListItemStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentConversationListItemStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "None", "Inprogress", "Complete", "Failed":
			return true
		}
	}
	return false
}

type AgentConversationListItemSharedWithAccessLevel string

const (
	AgentConversationListItemSharedWithAccessLevelRead  AgentConversationListItemSharedWithAccessLevel = "read"
	AgentConversationListItemSharedWithAccessLevelWrite AgentConversationListItemSharedWithAccessLevel = "write"
)

func (e AgentConversationListItemSharedWithAccessLevel) ToPointer() *AgentConversationListItemSharedWithAccessLevel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentConversationListItemSharedWithAccessLevel) IsExact() bool {
	if e != nil {
		switch *e {
		case "read", "write":
			return true
		}
	}
	return false
}

type AgentConversationListItemSharedWith struct {
	UserID      *string                                         `json:"userId,omitzero"`
	AccessLevel *AgentConversationListItemSharedWithAccessLevel `json:"accessLevel,omitzero"`
}

func (a *AgentConversationListItemSharedWith) GetUserID() *string {
	if a == nil {
		return nil
	}
	return a.UserID
}

func (a *AgentConversationListItemSharedWith) GetAccessLevel() *AgentConversationListItemSharedWithAccessLevel {
	if a == nil {
		return nil
	}
	return a.AccessLevel
}

type AgentConversationListItemConversationError struct {
	Message   *string        `json:"message,omitzero"`
	ErrorType *string        `json:"errorType,omitzero"`
	Timestamp *time.Time     `json:"timestamp,omitzero"`
	MessageID *string        `json:"messageId,omitzero"`
	Stack     *string        `json:"stack,omitzero"`
	Metadata  map[string]any `json:"metadata,omitzero"`
}

func (a AgentConversationListItemConversationError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentConversationListItemConversationError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentConversationListItemConversationError) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

func (a *AgentConversationListItemConversationError) GetErrorType() *string {
	if a == nil {
		return nil
	}
	return a.ErrorType
}

func (a *AgentConversationListItemConversationError) GetTimestamp() *time.Time {
	if a == nil {
		return nil
	}
	return a.Timestamp
}

func (a *AgentConversationListItemConversationError) GetMessageID() *string {
	if a == nil {
		return nil
	}
	return a.MessageID
}

func (a *AgentConversationListItemConversationError) GetStack() *string {
	if a == nil {
		return nil
	}
	return a.Stack
}

func (a *AgentConversationListItemConversationError) GetMetadata() map[string]any {
	if a == nil {
		return nil
	}
	return a.Metadata
}

type AgentConversationListItemConversationSource string

const (
	AgentConversationListItemConversationSourceAgentChat AgentConversationListItemConversationSource = "agent_chat"
)

func (e AgentConversationListItemConversationSource) ToPointer() *AgentConversationListItemConversationSource {
	return &e
}
func (e *AgentConversationListItemConversationSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agent_chat":
		*e = AgentConversationListItemConversationSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentConversationListItemConversationSource: %v", v)
	}
}

// AgentConversationListItemAccessLevel - Computed per request from `sharedWith`; defaults to `read` when no
// explicit share grant is attached to the serialized row.
type AgentConversationListItemAccessLevel string

const (
	AgentConversationListItemAccessLevelRead  AgentConversationListItemAccessLevel = "read"
	AgentConversationListItemAccessLevelWrite AgentConversationListItemAccessLevel = "write"
)

func (e AgentConversationListItemAccessLevel) ToPointer() *AgentConversationListItemAccessLevel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentConversationListItemAccessLevel) IsExact() bool {
	if e != nil {
		switch *e {
		case "read", "write":
			return true
		}
	}
	return false
}

// AgentConversationListItem - Conversation summary returned by `GET /agents/{agentKey}/conversations`.
// The handler excludes `messages` and `__v` from both result sets. Rows
// in `sharedWithMeConversations` also omit `sharedWith` because the
// secondary query explicitly deselects that field before serialization.
type AgentConversationListItem struct {
	ID *string `json:"_id,omitzero"`
	// Agent identifier from the route path
	AgentKey   *string                          `json:"agentKey,omitzero"`
	UserID     *string                          `json:"userId,omitzero"`
	OrgID      *string                          `json:"orgId,omitzero"`
	Title      *string                          `json:"title,omitzero"`
	Initiator  *string                          `json:"initiator,omitzero"`
	Status     *AgentConversationListItemStatus `json:"status,omitzero"`
	FailReason *string                          `json:"failReason,omitzero"`
	// AI model configuration recorded against a conversation or message.
	ModelInfo  *ConversationModelInfo                    `json:"modelInfo,omitzero"`
	IsShared   *bool                                     `json:"isShared,omitzero"`
	ShareLink  *string                                   `json:"shareLink,omitzero"`
	SharedWith []AgentConversationListItemSharedWith     `json:"sharedWith,omitzero"`
	IsArchived *bool                                     `json:"isArchived,omitzero"`
	ArchivedBy optionalnullable.OptionalNullable[string] `json:"archivedBy,omitzero"`
	// Present on archived conversation endpoints. Derived from the
	// document `updatedAt` timestamp when the archive response is built.
	//
	ArchivedAt         *time.Time                                   `json:"archivedAt,omitzero"`
	IsDeleted          *bool                                        `json:"isDeleted,omitzero"`
	DeletedBy          optionalnullable.OptionalNullable[string]    `json:"deletedBy,omitzero"`
	ConversationErrors []AgentConversationListItemConversationError `json:"conversationErrors,omitzero"`
	ConversationSource *AgentConversationListItemConversationSource `json:"conversationSource,omitzero"`
	// Epoch milliseconds of the latest activity on the thread
	LastActivityAt *int64     `json:"lastActivityAt,omitzero"`
	CreatedAt      *time.Time `json:"createdAt,omitzero"`
	UpdatedAt      *time.Time `json:"updatedAt,omitzero"`
	// Computed per request. `true` when the conversation `initiator`
	// matches the authenticated user.
	//
	IsOwner *bool `json:"isOwner,omitzero"`
	// Computed per request from `sharedWith`; defaults to `read` when no
	// explicit share grant is attached to the serialized row.
	//
	AccessLevel *AgentConversationListItemAccessLevel `json:"accessLevel,omitzero"`
}

func (a AgentConversationListItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentConversationListItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentConversationListItem) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AgentConversationListItem) GetAgentKey() *string {
	if a == nil {
		return nil
	}
	return a.AgentKey
}

func (a *AgentConversationListItem) GetUserID() *string {
	if a == nil {
		return nil
	}
	return a.UserID
}

func (a *AgentConversationListItem) GetOrgID() *string {
	if a == nil {
		return nil
	}
	return a.OrgID
}

func (a *AgentConversationListItem) GetTitle() *string {
	if a == nil {
		return nil
	}
	return a.Title
}

func (a *AgentConversationListItem) GetInitiator() *string {
	if a == nil {
		return nil
	}
	return a.Initiator
}

func (a *AgentConversationListItem) GetStatus() *AgentConversationListItemStatus {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AgentConversationListItem) GetFailReason() *string {
	if a == nil {
		return nil
	}
	return a.FailReason
}

func (a *AgentConversationListItem) GetModelInfo() *ConversationModelInfo {
	if a == nil {
		return nil
	}
	return a.ModelInfo
}

func (a *AgentConversationListItem) GetIsShared() *bool {
	if a == nil {
		return nil
	}
	return a.IsShared
}

func (a *AgentConversationListItem) GetShareLink() *string {
	if a == nil {
		return nil
	}
	return a.ShareLink
}

func (a *AgentConversationListItem) GetSharedWith() []AgentConversationListItemSharedWith {
	if a == nil {
		return nil
	}
	return a.SharedWith
}

func (a *AgentConversationListItem) GetIsArchived() *bool {
	if a == nil {
		return nil
	}
	return a.IsArchived
}

func (a *AgentConversationListItem) GetArchivedBy() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.ArchivedBy
}

func (a *AgentConversationListItem) GetArchivedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.ArchivedAt
}

func (a *AgentConversationListItem) GetIsDeleted() *bool {
	if a == nil {
		return nil
	}
	return a.IsDeleted
}

func (a *AgentConversationListItem) GetDeletedBy() optionalnullable.OptionalNullable[string] {
	if a == nil {
		return nil
	}
	return a.DeletedBy
}

func (a *AgentConversationListItem) GetConversationErrors() []AgentConversationListItemConversationError {
	if a == nil {
		return nil
	}
	return a.ConversationErrors
}

func (a *AgentConversationListItem) GetConversationSource() *AgentConversationListItemConversationSource {
	if a == nil {
		return nil
	}
	return a.ConversationSource
}

func (a *AgentConversationListItem) GetLastActivityAt() *int64 {
	if a == nil {
		return nil
	}
	return a.LastActivityAt
}

func (a *AgentConversationListItem) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AgentConversationListItem) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *AgentConversationListItem) GetIsOwner() *bool {
	if a == nil {
		return nil
	}
	return a.IsOwner
}

func (a *AgentConversationListItem) GetAccessLevel() *AgentConversationListItemAccessLevel {
	if a == nil {
		return nil
	}
	return a.AccessLevel
}
