// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// AgentKnowledgeFiltersParsed - Indexed scope for a knowledge connector: record-group ids and
// individual record ids. On GET, `filtersParsed` is this shape parsed
// from the stored `filters` JSON string.
type AgentKnowledgeFiltersParsed struct {
	// Deprecated/legacy: record-group ids for connector record-group scoping (e.g. Confluence spaces, Jira projects). No longer set for KB (Collection) entries — a KB is identified by its own `connectorId`, not by an id in this list.
	RecordGroups []string `json:"recordGroups,omitzero"`
	// Individual record ids in scope.
	Records []string `json:"records,omitzero"`
}

func (a AgentKnowledgeFiltersParsed) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentKnowledgeFiltersParsed) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentKnowledgeFiltersParsed) GetRecordGroups() []string {
	if a == nil {
		return nil
	}
	return a.RecordGroups
}

func (a *AgentKnowledgeFiltersParsed) GetRecords() []string {
	if a == nil {
		return nil
	}
	return a.Records
}
