// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// AgentConversationDetailMessageCitation - Citation entry returned inside a conversation message after the
// handler populates `messages.citations.citationId` and rewrites each
// item to `{ citationId, citationData }`.
type AgentConversationDetailMessageCitation struct {
	CitationID *string `json:"citationId,omitzero"`
	// A populated citation document. Represents a single chunk of source
	// content (e.g. a passage from a document or record) referenced by an
	// AI response, together with its provenance metadata.
	//
	CitationData *Citation `json:"citationData,omitzero"`
}

func (a AgentConversationDetailMessageCitation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentConversationDetailMessageCitation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentConversationDetailMessageCitation) GetCitationID() *string {
	if a == nil {
		return nil
	}
	return a.CitationID
}

func (a *AgentConversationDetailMessageCitation) GetCitationData() *Citation {
	if a == nil {
		return nil
	}
	return a.CitationData
}
