// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentRegenerateSSEEventEvent string

const (
	AgentRegenerateSSEEventEventRunStarted              AgentRegenerateSSEEventEvent = "RUN_STARTED"
	AgentRegenerateSSEEventEventRunFinished             AgentRegenerateSSEEventEvent = "RUN_FINISHED"
	AgentRegenerateSSEEventEventRunError                AgentRegenerateSSEEventEvent = "RUN_ERROR"
	AgentRegenerateSSEEventEventStepStarted             AgentRegenerateSSEEventEvent = "STEP_STARTED"
	AgentRegenerateSSEEventEventStepFinished            AgentRegenerateSSEEventEvent = "STEP_FINISHED"
	AgentRegenerateSSEEventEventTextMessageStart        AgentRegenerateSSEEventEvent = "TEXT_MESSAGE_START"
	AgentRegenerateSSEEventEventTextMessageContent      AgentRegenerateSSEEventEvent = "TEXT_MESSAGE_CONTENT"
	AgentRegenerateSSEEventEventTextMessageEnd          AgentRegenerateSSEEventEvent = "TEXT_MESSAGE_END"
	AgentRegenerateSSEEventEventReasoningStart          AgentRegenerateSSEEventEvent = "REASONING_START"
	AgentRegenerateSSEEventEventReasoningMessageStart   AgentRegenerateSSEEventEvent = "REASONING_MESSAGE_START"
	AgentRegenerateSSEEventEventReasoningMessageContent AgentRegenerateSSEEventEvent = "REASONING_MESSAGE_CONTENT"
	AgentRegenerateSSEEventEventReasoningMessageEnd     AgentRegenerateSSEEventEvent = "REASONING_MESSAGE_END"
	AgentRegenerateSSEEventEventReasoningEnd            AgentRegenerateSSEEventEvent = "REASONING_END"
	AgentRegenerateSSEEventEventToolCallStart           AgentRegenerateSSEEventEvent = "TOOL_CALL_START"
	AgentRegenerateSSEEventEventToolCallArgs            AgentRegenerateSSEEventEvent = "TOOL_CALL_ARGS"
	AgentRegenerateSSEEventEventToolCallEnd             AgentRegenerateSSEEventEvent = "TOOL_CALL_END"
	AgentRegenerateSSEEventEventToolCallResult          AgentRegenerateSSEEventEvent = "TOOL_CALL_RESULT"
	AgentRegenerateSSEEventEventStateDelta              AgentRegenerateSSEEventEvent = "STATE_DELTA"
	AgentRegenerateSSEEventEventStateSnapshot           AgentRegenerateSSEEventEvent = "STATE_SNAPSHOT"
	AgentRegenerateSSEEventEventCustom                  AgentRegenerateSSEEventEvent = "CUSTOM"
	AgentRegenerateSSEEventEventHeartbeat               AgentRegenerateSSEEventEvent = "HEARTBEAT"
)

func (e AgentRegenerateSSEEventEvent) ToPointer() *AgentRegenerateSSEEventEvent {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentRegenerateSSEEventEvent) IsExact() bool {
	if e != nil {
		switch *e {
		case "RUN_STARTED", "RUN_FINISHED", "RUN_ERROR", "STEP_STARTED", "STEP_FINISHED", "TEXT_MESSAGE_START", "TEXT_MESSAGE_CONTENT", "TEXT_MESSAGE_END", "REASONING_START", "REASONING_MESSAGE_START", "REASONING_MESSAGE_CONTENT", "REASONING_MESSAGE_END", "REASONING_END", "TOOL_CALL_START", "TOOL_CALL_ARGS", "TOOL_CALL_END", "TOOL_CALL_RESULT", "STATE_DELTA", "STATE_SNAPSHOT", "CUSTOM", "HEARTBEAT":
			return true
		}
	}
	return false
}

// AgentRegenerateSSEEvent - SSE event envelope for `POST /agents/{agentKey}/conversations/{conversationId}/message/{messageId}/regenerate`.
// AG-UI is the sole wire protocol.
//
// `event` carries the AG-UI type name and `data` is a JSON object that
// includes a `"type"` field matching `event`, plus type-specific
// fields. Stable gateway-generated top-level outcomes:
//
//   - `RUN_FINISHED` returns `{ type, result }` where
//     `result` is `{ conversation, recordsUsed, meta }` — the updated
//     conversation plus request metadata after the regenerated response
//     is persisted.
//   - `RUN_ERROR` returns `{ type, message, code? }`. Conversation
//     lookup failures, unauthorized conversation access, and regenerate
//     rule failures such as "not the last message" are reported here.
//
// Other events are forwarded from the agent backend and should be
// treated as informational updates. Those forwarded lifecycle and
// child-run events may contain `runId`, `threadId`, and `parentRunId`;
// the gateway-generated root terminal event does not.
type AgentRegenerateSSEEvent struct {
	Event *AgentRegenerateSSEEventEvent `json:"event,omitzero"`
	// JSON-encoded event payload. The decoded JSON includes a `"type"`
	// field matching `event`, plus type-specific fields. Shape depends
	// on `event`.
	//
	Data *string `json:"data,omitzero"`
}

func (a *AgentRegenerateSSEEvent) GetEvent() *AgentRegenerateSSEEventEvent {
	if a == nil {
		return nil
	}
	return a.Event
}

func (a *AgentRegenerateSSEEvent) GetData() *string {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a AgentRegenerateSSEEvent) GetEventEncoding(event string) (string, error) {
	return "string", nil
}
