// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentCreateResponseToolset struct {
	// Registered toolset name (lowercase) accepted by the create-agent gateway.
	Name AgentCreateToolsetName `json:"name"`
	// Human-readable toolset product label (for example `Jira` or `Slack`).
	DisplayName string                    `json:"displayName"`
	Key         string                    `json:"key"`
	Tools       []AgentCreateResponseTool `json:"tools"`
}

func (a *AgentCreateResponseToolset) GetName() AgentCreateToolsetName {
	if a == nil {
		return AgentCreateToolsetName("")
	}
	return a.Name
}

func (a *AgentCreateResponseToolset) GetDisplayName() string {
	if a == nil {
		return ""
	}
	return a.DisplayName
}

func (a *AgentCreateResponseToolset) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

func (a *AgentCreateResponseToolset) GetTools() []AgentCreateResponseTool {
	if a == nil {
		return []AgentCreateResponseTool{}
	}
	return a.Tools
}
