// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type AgentCreateResponseKnowledgeFiltersType string

const (
	AgentCreateResponseKnowledgeFiltersTypeMapOfAny   AgentCreateResponseKnowledgeFiltersType = "mapOfAny"
	AgentCreateResponseKnowledgeFiltersTypeStr        AgentCreateResponseKnowledgeFiltersType = "str"
	AgentCreateResponseKnowledgeFiltersTypeArrayOfAny AgentCreateResponseKnowledgeFiltersType = "arrayOfAny"
	AgentCreateResponseKnowledgeFiltersTypeUnknown    AgentCreateResponseKnowledgeFiltersType = "Unknown"
)

type AgentCreateResponseKnowledgeFilters struct {
	MapOfAny   map[string]any  `queryParam:"inline" union:"member"`
	Str        *string         `queryParam:"inline" union:"member"`
	ArrayOfAny []any           `queryParam:"inline" union:"member"`
	UnknownRaw json.RawMessage `json:"-" union:"unknown"`

	Type AgentCreateResponseKnowledgeFiltersType
}

func CreateAgentCreateResponseKnowledgeFiltersMapOfAny(mapOfAny map[string]any) AgentCreateResponseKnowledgeFilters {
	typ := AgentCreateResponseKnowledgeFiltersTypeMapOfAny

	return AgentCreateResponseKnowledgeFilters{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateAgentCreateResponseKnowledgeFiltersStr(str string) AgentCreateResponseKnowledgeFilters {
	typ := AgentCreateResponseKnowledgeFiltersTypeStr

	return AgentCreateResponseKnowledgeFilters{
		Str:  &str,
		Type: typ,
	}
}

func CreateAgentCreateResponseKnowledgeFiltersArrayOfAny(arrayOfAny []any) AgentCreateResponseKnowledgeFilters {
	typ := AgentCreateResponseKnowledgeFiltersTypeArrayOfAny

	return AgentCreateResponseKnowledgeFilters{
		ArrayOfAny: arrayOfAny,
		Type:       typ,
	}
}

func CreateAgentCreateResponseKnowledgeFiltersUnknown(raw json.RawMessage) AgentCreateResponseKnowledgeFilters {
	return AgentCreateResponseKnowledgeFilters{
		UnknownRaw: raw,
		Type:       AgentCreateResponseKnowledgeFiltersTypeUnknown,
	}
}

func (u AgentCreateResponseKnowledgeFilters) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u AgentCreateResponseKnowledgeFilters) IsUnknown() bool {
	return u.Type == AgentCreateResponseKnowledgeFiltersTypeUnknown
}

func (u *AgentCreateResponseKnowledgeFilters) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AgentCreateResponseKnowledgeFiltersTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AgentCreateResponseKnowledgeFiltersTypeStr,
			Value: &str,
		})
	}

	var arrayOfAny []any = []any{}
	if err := utils.UnmarshalJSON(data, &arrayOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AgentCreateResponseKnowledgeFiltersTypeArrayOfAny,
			Value: arrayOfAny,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AgentCreateResponseKnowledgeFiltersTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AgentCreateResponseKnowledgeFiltersTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(AgentCreateResponseKnowledgeFiltersType)
	switch best.Type {
	case AgentCreateResponseKnowledgeFiltersTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	case AgentCreateResponseKnowledgeFiltersTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case AgentCreateResponseKnowledgeFiltersTypeArrayOfAny:
		u.ArrayOfAny = best.Value.([]any)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = AgentCreateResponseKnowledgeFiltersTypeUnknown
	return nil
}

func (u AgentCreateResponseKnowledgeFilters) MarshalJSON() ([]byte, error) {
	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfAny != nil {
		return utils.MarshalJSON(u.ArrayOfAny, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type AgentCreateResponseKnowledgeFilters: all fields are null")
}

type AgentCreateResponseKnowledge struct {
	ConnectorID string                              `json:"connectorId"`
	Key         string                              `json:"key"`
	Filters     AgentCreateResponseKnowledgeFilters `json:"filters"`
}

func (a *AgentCreateResponseKnowledge) GetConnectorID() string {
	if a == nil {
		return ""
	}
	return a.ConnectorID
}

func (a *AgentCreateResponseKnowledge) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}

func (a *AgentCreateResponseKnowledge) GetFilters() AgentCreateResponseKnowledgeFilters {
	if a == nil {
		return AgentCreateResponseKnowledgeFilters{}
	}
	return a.Filters
}
