// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// AgentAddMessageRequestChatMode - Execution mode. Scoped agent conversations support only `quick`.
// Required on the `/stream` route; optional on the non-streaming
// route.
type AgentAddMessageRequestChatMode string

const (
	AgentAddMessageRequestChatModeQuick AgentAddMessageRequestChatMode = "quick"
)

func (e AgentAddMessageRequestChatMode) ToPointer() *AgentAddMessageRequestChatMode {
	return &e
}
func (e *AgentAddMessageRequestChatMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "quick":
		*e = AgentAddMessageRequestChatMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentAddMessageRequestChatMode: %v", v)
	}
}

// AgentAddMessageRequestProtocol - AG-UI is the only supported wire protocol. When present must be
// `"agui"`. Omitting the field is equivalent — the server always
// uses the AG-UI vocabulary (see `AgentMessageStreamSSEEvent`).
// Kept in the schema for backward compatibility with callers that
// already send it.
type AgentAddMessageRequestProtocol string

const (
	AgentAddMessageRequestProtocolAgui AgentAddMessageRequestProtocol = "agui"
)

func (e AgentAddMessageRequestProtocol) ToPointer() *AgentAddMessageRequestProtocol {
	return &e
}
func (e *AgentAddMessageRequestProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agui":
		*e = AgentAddMessageRequestProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentAddMessageRequestProtocol: %v", v)
	}
}

// AgentAddMessageRequest - Follow-up turn on an agent conversation. Used as-is by the
// non-streaming `POST /agents/{agentKey}/conversations/{conversationId}/messages`,
// where `chatMode` may be omitted; `AgentAddMessageStreamRequest`
// additionally requires it. Unknown fields are stripped during validation.
type AgentAddMessageRequest struct {
	// User follow-up prompt to append to the existing agent conversation.
	// Saved as a new `user_query` message before the upstream AI stream
	// starts.
	//
	Query string `json:"query"`
	// Optional retrieval scope (`apps` / `kb`) for this turn. Each id must
	// be a valid UUID. Omit to let the agent use its stored defaults;
	// send `{ "apps": [], "kb": [] }` to force no knowledge sources for this turn.
	//
	Filters *Filters `json:"filters,omitzero"`
	// UI filter state persisted on the saved user message. Not used for
	// retrieval and not forwarded to the upstream agent backend.
	//
	AppliedFilters *AppliedFilters `json:"appliedFilters,omitzero"`
	// Uploaded attachments to ground this turn. Each entry references a
	// record id returned from the agent attachment upload endpoint.
	//
	Attachments []ChatAttachmentRef `json:"attachments,omitzero"`
	// Execution mode. Scoped agent conversations support only `quick`.
	// Required on the `/stream` route; optional on the non-streaming
	// route.
	//
	ChatMode *AgentAddMessageRequestChatMode `json:"chatMode,omitzero"`
	// AI model configuration id override for this turn. Omit to use the
	// agent's default model.
	//
	ModelKey *string `json:"modelKey,omitzero"`
	// Provider model name (the underlying LLM identifier).
	ModelName *string `json:"modelName,omitzero"`
	// Friendly UI label for the selected model.
	ModelFriendlyName *string `json:"modelFriendlyName,omitzero"`
	// Client IANA timezone, such as `America/New_York`. Helps the agent
	// resolve relative date references in the prompt.
	//
	Timezone *string `json:"timezone,omitzero"`
	// Client time in ISO 8601 / RFC 3339 format (UTC `Z` or numeric
	// offset). Sent alongside `timezone` for time-aware answers.
	//
	CurrentTime *time.Time `json:"currentTime,omitzero"`
	// Allowed tool ids for this turn, such as `jira.create_issue`. Omit
	// to let the agent use its default toolset; send `[]` to disable
	// tools for this turn.
	//
	Tools []string `json:"tools,omitzero"`
	// AG-UI is the only supported wire protocol. When present must be
	// `"agui"`. Omitting the field is equivalent — the server always
	// uses the AG-UI vocabulary (see `AgentMessageStreamSSEEvent`).
	// Kept in the schema for backward compatibility with callers that
	// already send it.
	//
	Protocol *AgentAddMessageRequestProtocol `json:"protocol,omitzero"`
	// Per-request agent capability toggles. Only meaningful when `chatMode`
	// selects an agent mode; ignored otherwise. Each field falls back to its
	// own `default` below when omitted — a missing flag is not uniformly
	// `true`. Omitting the whole object applies every default.
	//
	AgentCapabilities *AgentCapabilities `json:"agentCapabilities,omitzero"`
	// Client-generated identifier for this run. Send it here to enable
	// `POST /agents/{agentKey}/conversations/{conversationId}/cancel
	// {runId}` while the stream is still generating.
	//
	RunID *string `json:"runId,omitzero"`
}

func (a AgentAddMessageRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentAddMessageRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentAddMessageRequest) GetQuery() string {
	if a == nil {
		return ""
	}
	return a.Query
}

func (a *AgentAddMessageRequest) GetFilters() *Filters {
	if a == nil {
		return nil
	}
	return a.Filters
}

func (a *AgentAddMessageRequest) GetAppliedFilters() *AppliedFilters {
	if a == nil {
		return nil
	}
	return a.AppliedFilters
}

func (a *AgentAddMessageRequest) GetAttachments() []ChatAttachmentRef {
	if a == nil {
		return nil
	}
	return a.Attachments
}

func (a *AgentAddMessageRequest) GetChatMode() *AgentAddMessageRequestChatMode {
	if a == nil {
		return nil
	}
	return a.ChatMode
}

func (a *AgentAddMessageRequest) GetModelKey() *string {
	if a == nil {
		return nil
	}
	return a.ModelKey
}

func (a *AgentAddMessageRequest) GetModelName() *string {
	if a == nil {
		return nil
	}
	return a.ModelName
}

func (a *AgentAddMessageRequest) GetModelFriendlyName() *string {
	if a == nil {
		return nil
	}
	return a.ModelFriendlyName
}

func (a *AgentAddMessageRequest) GetTimezone() *string {
	if a == nil {
		return nil
	}
	return a.Timezone
}

func (a *AgentAddMessageRequest) GetCurrentTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.CurrentTime
}

func (a *AgentAddMessageRequest) GetTools() []string {
	if a == nil {
		return nil
	}
	return a.Tools
}

func (a *AgentAddMessageRequest) GetProtocol() *AgentAddMessageRequestProtocol {
	if a == nil {
		return nil
	}
	return a.Protocol
}

func (a *AgentAddMessageRequest) GetAgentCapabilities() *AgentCapabilities {
	if a == nil {
		return nil
	}
	return a.AgentCapabilities
}

func (a *AgentAddMessageRequest) GetRunID() *string {
	if a == nil {
		return nil
	}
	return a.RunID
}
