// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentCreateWarning struct {
	Name  *string `json:"name,omitzero"`
	Error *string `json:"error,omitzero"`
}

func (a *AgentCreateWarning) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AgentCreateWarning) GetError() *string {
	if a == nil {
		return nil
	}
	return a.Error
}
