// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

type AgentConversationDetailAccessLevel string

const (
	AgentConversationDetailAccessLevelRead  AgentConversationDetailAccessLevel = "read"
	AgentConversationDetailAccessLevelWrite AgentConversationDetailAccessLevel = "write"
)

func (e AgentConversationDetailAccessLevel) ToPointer() *AgentConversationDetailAccessLevel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentConversationDetailAccessLevel) IsExact() bool {
	if e != nil {
		switch *e {
		case "read", "write":
			return true
		}
	}
	return false
}

type AgentConversationDetailSharedWith struct {
	UserID      *string                             `json:"userId,omitzero"`
	AccessLevel *AgentConversationDetailAccessLevel `json:"accessLevel,omitzero"`
}

func (a *AgentConversationDetailSharedWith) GetUserID() *string {
	if a == nil {
		return nil
	}
	return a.UserID
}

func (a *AgentConversationDetailSharedWith) GetAccessLevel() *AgentConversationDetailAccessLevel {
	if a == nil {
		return nil
	}
	return a.AccessLevel
}

type AgentConversationDetailStatus string

const (
	AgentConversationDetailStatusNone       AgentConversationDetailStatus = "None"
	AgentConversationDetailStatusInprogress AgentConversationDetailStatus = "Inprogress"
	AgentConversationDetailStatusComplete   AgentConversationDetailStatus = "Complete"
	AgentConversationDetailStatusFailed     AgentConversationDetailStatus = "Failed"
)

func (e AgentConversationDetailStatus) ToPointer() *AgentConversationDetailStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentConversationDetailStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "None", "Inprogress", "Complete", "Failed":
			return true
		}
	}
	return false
}

// AgentConversationDetail - Reduced conversation view returned by the by-id GET route. This is
// not the raw `AgentConversation` document shape: fields like `agentKey`,
// `userId`, `orgId`, `conversationSource`, and root-level `messages`
// metadata outside the selected slice are omitted.
type AgentConversationDetail struct {
	ID         string                              `json:"id"`
	Title      *string                             `json:"title,omitzero"`
	Initiator  *string                             `json:"initiator,omitzero"`
	CreatedAt  time.Time                           `json:"createdAt"`
	IsShared   bool                                `json:"isShared"`
	SharedWith []AgentConversationDetailSharedWith `json:"sharedWith"`
	Status     *AgentConversationDetailStatus      `json:"status,omitzero"`
	FailReason *string                             `json:"failReason,omitzero"`
	Messages   []AgentConversationDetailMessage    `json:"messages"`
	// AI model configuration recorded against a conversation or message.
	ModelInfo *ConversationModelInfo `json:"modelInfo,omitzero"`
	// Message pagination returned inside the `conversation` object. The
	// handler paginates backwards from the end of the stored message array,
	// then sorts the selected page in memory before serialization.
	//
	Pagination AgentConversationDetailPagination `json:"pagination"`
	Access     AgentConversationDetailAccess     `json:"access"`
}

func (a AgentConversationDetail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentConversationDetail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentConversationDetail) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AgentConversationDetail) GetTitle() *string {
	if a == nil {
		return nil
	}
	return a.Title
}

func (a *AgentConversationDetail) GetInitiator() *string {
	if a == nil {
		return nil
	}
	return a.Initiator
}

func (a *AgentConversationDetail) GetCreatedAt() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.CreatedAt
}

func (a *AgentConversationDetail) GetIsShared() bool {
	if a == nil {
		return false
	}
	return a.IsShared
}

func (a *AgentConversationDetail) GetSharedWith() []AgentConversationDetailSharedWith {
	if a == nil {
		return []AgentConversationDetailSharedWith{}
	}
	return a.SharedWith
}

func (a *AgentConversationDetail) GetStatus() *AgentConversationDetailStatus {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AgentConversationDetail) GetFailReason() *string {
	if a == nil {
		return nil
	}
	return a.FailReason
}

func (a *AgentConversationDetail) GetMessages() []AgentConversationDetailMessage {
	if a == nil {
		return []AgentConversationDetailMessage{}
	}
	return a.Messages
}

func (a *AgentConversationDetail) GetModelInfo() *ConversationModelInfo {
	if a == nil {
		return nil
	}
	return a.ModelInfo
}

func (a *AgentConversationDetail) GetPagination() AgentConversationDetailPagination {
	if a == nil {
		return AgentConversationDetailPagination{}
	}
	return a.Pagination
}

func (a *AgentConversationDetail) GetAccess() AgentConversationDetailAccess {
	if a == nil {
		return AgentConversationDetailAccess{}
	}
	return a.Access
}
