// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// AgentConversationDetailMeta - Request-scoped metadata returned by the by-id GET route. `requestId`
// is omitted when upstream middleware did not attach one.
type AgentConversationDetailMeta struct {
	RequestID      *string   `json:"requestId,omitzero"`
	Timestamp      time.Time `json:"timestamp"`
	Duration       int64     `json:"duration"`
	ConversationID string    `json:"conversationId"`
	MessageCount   int64     `json:"messageCount"`
}

func (a AgentConversationDetailMeta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentConversationDetailMeta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentConversationDetailMeta) GetRequestID() *string {
	if a == nil {
		return nil
	}
	return a.RequestID
}

func (a *AgentConversationDetailMeta) GetTimestamp() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.Timestamp
}

func (a *AgentConversationDetailMeta) GetDuration() int64 {
	if a == nil {
		return 0
	}
	return a.Duration
}

func (a *AgentConversationDetailMeta) GetConversationID() string {
	if a == nil {
		return ""
	}
	return a.ConversationID
}

func (a *AgentConversationDetailMeta) GetMessageCount() int64 {
	if a == nil {
		return 0
	}
	return a.MessageCount
}
