// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type AgentCreateToolset struct {
	// Registered toolset name (lowercase) accepted by the create-agent gateway.
	Name         AgentCreateToolsetName `json:"name"`
	DisplayName  *string                `json:"displayName,omitzero"`
	Type         *string                `json:"type,omitzero"`
	InstanceID   *string                `json:"instanceId,omitzero"`
	InstanceName *string                `json:"instanceName,omitzero"`
	Tools        []AgentCreateToolRef   `json:"tools,omitzero"`
}

func (a AgentCreateToolset) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentCreateToolset) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentCreateToolset) GetName() AgentCreateToolsetName {
	if a == nil {
		return AgentCreateToolsetName("")
	}
	return a.Name
}

func (a *AgentCreateToolset) GetDisplayName() *string {
	if a == nil {
		return nil
	}
	return a.DisplayName
}

func (a *AgentCreateToolset) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AgentCreateToolset) GetInstanceID() *string {
	if a == nil {
		return nil
	}
	return a.InstanceID
}

func (a *AgentCreateToolset) GetInstanceName() *string {
	if a == nil {
		return nil
	}
	return a.InstanceName
}

func (a *AgentCreateToolset) GetTools() []AgentCreateToolRef {
	if a == nil {
		return nil
	}
	return a.Tools
}
