// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

type AgentCreateRequest struct {
	// Agent display name
	Name string `json:"name"`
	// What the agent does
	Description *string `json:"description,omitzero"`
	// Initial greeting shown when conversation starts
	StartMessage *string `json:"startMessage,omitzero"`
	// System instructions for the agent
	SystemPrompt *string `json:"systemPrompt,omitzero"`
	// Additional agent execution instructions
	Instructions *string `json:"instructions,omitzero"`
	// Agent model configuration entries. The gateway requires at least one
	// object entry with `isReasoning: true`. String-only arrays are schema-valid
	// but rejected at runtime with HTTP 400.
	//
	Models []AgentCreateModelEntryUnion `json:"models"`
	Tags   []string                     `json:"tags,omitzero"`
	// Share agent with the organization
	ShareWithOrg *bool `default:"false" json:"shareWithOrg"`
	// Create the agent as a service-account agent
	IsServiceAccount *bool `default:"false" json:"isServiceAccount"`
	// Toolsets attached to the agent (instance-aware)
	Toolsets []AgentCreateToolset `json:"toolsets,omitzero"`
	// Knowledge sources connected to the agent
	Knowledge []AgentCreateKnowledge `json:"knowledge,omitzero"`
	// Accepted web-search attachment for `POST /agents/create`.
	// The gateway accepts either a provider string or an object with at least
	// a `provider` field.
	//
	WebSearch optionalnullable.OptionalNullable[AgentCreateWebSearchUnion] `json:"webSearch,omitzero"`
}

func (a AgentCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentCreateRequest) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AgentCreateRequest) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AgentCreateRequest) GetStartMessage() *string {
	if a == nil {
		return nil
	}
	return a.StartMessage
}

func (a *AgentCreateRequest) GetSystemPrompt() *string {
	if a == nil {
		return nil
	}
	return a.SystemPrompt
}

func (a *AgentCreateRequest) GetInstructions() *string {
	if a == nil {
		return nil
	}
	return a.Instructions
}

func (a *AgentCreateRequest) GetModels() []AgentCreateModelEntryUnion {
	if a == nil {
		return []AgentCreateModelEntryUnion{}
	}
	return a.Models
}

func (a *AgentCreateRequest) GetTags() []string {
	if a == nil {
		return nil
	}
	return a.Tags
}

func (a *AgentCreateRequest) GetShareWithOrg() *bool {
	if a == nil {
		return nil
	}
	return a.ShareWithOrg
}

func (a *AgentCreateRequest) GetIsServiceAccount() *bool {
	if a == nil {
		return nil
	}
	return a.IsServiceAccount
}

func (a *AgentCreateRequest) GetToolsets() []AgentCreateToolset {
	if a == nil {
		return nil
	}
	return a.Toolsets
}

func (a *AgentCreateRequest) GetKnowledge() []AgentCreateKnowledge {
	if a == nil {
		return nil
	}
	return a.Knowledge
}

func (a *AgentCreateRequest) GetWebSearch() optionalnullable.OptionalNullable[AgentCreateWebSearchUnion] {
	if a == nil {
		return nil
	}
	return a.WebSearch
}
