// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type AgentCreateWebSearch struct {
	Provider      string  `json:"provider"`
	ProviderKey   *string `json:"providerKey,omitzero"`
	ProviderLabel *string `json:"providerLabel,omitzero"`
	IconPath      *string `json:"iconPath,omitzero"`
}

func (a AgentCreateWebSearch) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentCreateWebSearch) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentCreateWebSearch) GetProvider() string {
	if a == nil {
		return ""
	}
	return a.Provider
}

func (a *AgentCreateWebSearch) GetProviderKey() *string {
	if a == nil {
		return nil
	}
	return a.ProviderKey
}

func (a *AgentCreateWebSearch) GetProviderLabel() *string {
	if a == nil {
		return nil
	}
	return a.ProviderLabel
}

func (a *AgentCreateWebSearch) GetIconPath() *string {
	if a == nil {
		return nil
	}
	return a.IconPath
}

type AgentCreateWebSearchUnionType string

const (
	AgentCreateWebSearchUnionTypeStr                  AgentCreateWebSearchUnionType = "str"
	AgentCreateWebSearchUnionTypeAgentCreateWebSearch AgentCreateWebSearchUnionType = "AgentCreateWebSearch"
)

// AgentCreateWebSearchUnion - Accepted web-search attachment for `POST /agents/create`.
// The gateway accepts either a provider string or an object with at least
// a `provider` field.
type AgentCreateWebSearchUnion struct {
	Str                  *string               `queryParam:"inline" union:"member"`
	AgentCreateWebSearch *AgentCreateWebSearch `queryParam:"inline" union:"member"`

	Type AgentCreateWebSearchUnionType
}

func CreateAgentCreateWebSearchUnionStr(str string) AgentCreateWebSearchUnion {
	typ := AgentCreateWebSearchUnionTypeStr

	return AgentCreateWebSearchUnion{
		Str:  &str,
		Type: typ,
	}
}

func CreateAgentCreateWebSearchUnionAgentCreateWebSearch(agentCreateWebSearch AgentCreateWebSearch) AgentCreateWebSearchUnion {
	typ := AgentCreateWebSearchUnionTypeAgentCreateWebSearch

	return AgentCreateWebSearchUnion{
		AgentCreateWebSearch: &agentCreateWebSearch,
		Type:                 typ,
	}
}

func (u *AgentCreateWebSearchUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AgentCreateWebSearchUnionTypeStr,
			Value: &str,
		})
	}

	var agentCreateWebSearch AgentCreateWebSearch = AgentCreateWebSearch{}
	if err := utils.UnmarshalJSON(data, &agentCreateWebSearch, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AgentCreateWebSearchUnionTypeAgentCreateWebSearch,
			Value: &agentCreateWebSearch,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AgentCreateWebSearchUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for AgentCreateWebSearchUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(AgentCreateWebSearchUnionType)
	switch best.Type {
	case AgentCreateWebSearchUnionTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case AgentCreateWebSearchUnionTypeAgentCreateWebSearch:
		u.AgentCreateWebSearch = best.Value.(*AgentCreateWebSearch)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for AgentCreateWebSearchUnion", string(data))
}

func (u AgentCreateWebSearchUnion) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.AgentCreateWebSearch != nil {
		return utils.MarshalJSON(u.AgentCreateWebSearch, "", true)
	}

	return nil, errors.New("could not marshal union type AgentCreateWebSearchUnion: all fields are null")
}
