// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentCreateResponseMcpServerTool struct {
	Name     string `json:"name"`
	FullName string `json:"fullName"`
	Key      string `json:"key"`
}

func (a *AgentCreateResponseMcpServerTool) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AgentCreateResponseMcpServerTool) GetFullName() string {
	if a == nil {
		return ""
	}
	return a.FullName
}

func (a *AgentCreateResponseMcpServerTool) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}
