// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// AgentStreamCreateConversationRequestChatMode - Required execution mode. Scoped agent conversations currently
// support only `quick`.
type AgentStreamCreateConversationRequestChatMode string

const (
	AgentStreamCreateConversationRequestChatModeQuick AgentStreamCreateConversationRequestChatMode = "quick"
)

func (e AgentStreamCreateConversationRequestChatMode) ToPointer() *AgentStreamCreateConversationRequestChatMode {
	return &e
}
func (e *AgentStreamCreateConversationRequestChatMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "quick":
		*e = AgentStreamCreateConversationRequestChatMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentStreamCreateConversationRequestChatMode: %v", v)
	}
}

// AgentStreamCreateConversationRequestProtocol - AG-UI is the only supported wire protocol. When present must be
// `"agui"`. Omitting the field is equivalent — the server always
// uses the AG-UI vocabulary (see `AgentStreamSSEEvent`). Kept in
// the schema for backward compatibility with callers that already
// send it.
type AgentStreamCreateConversationRequestProtocol string

const (
	AgentStreamCreateConversationRequestProtocolAgui AgentStreamCreateConversationRequestProtocol = "agui"
)

func (e AgentStreamCreateConversationRequestProtocol) ToPointer() *AgentStreamCreateConversationRequestProtocol {
	return &e
}
func (e *AgentStreamCreateConversationRequestProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agui":
		*e = AgentStreamCreateConversationRequestProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentStreamCreateConversationRequestProtocol: %v", v)
	}
}

// AgentStreamCreateConversationRequest - Request body for `POST /agents/{agentKey}/conversations/stream`.
// `query` and `chatMode: quick` are required; all other fields are
// optional overrides. Unknown fields are stripped during validation.
type AgentStreamCreateConversationRequest struct {
	// User prompt for the first turn. Saved as the initial `user_query`
	// message and sent to the agent backend.
	//
	Query string `json:"query"`
	// Optional record ids to include as context for this turn. Each id
	// must be a 24-character MongoDB ObjectId.
	//
	RecordIds []string `json:"recordIds,omitzero"`
	// Optional retrieval scope (`apps` / `kb`) for this turn. Each id must
	// be a valid UUID. Omit for agent defaults; send `{ "apps": [], "kb": [] }`
	// to force no knowledge sources for this turn.
	//
	Filters *Filters `json:"filters,omitzero"`
	// UI filter state persisted on the saved user message. Not used for
	// retrieval and not forwarded to the upstream agent backend.
	//
	AppliedFilters *AppliedFilters `json:"appliedFilters,omitzero"`
	// Uploaded attachments to ground this turn. Each entry references a
	// record id returned from the agent attachment upload endpoint.
	//
	Attachments []ChatAttachmentRef `json:"attachments,omitzero"`
	// Required execution mode. Scoped agent conversations currently
	// support only `quick`.
	//
	ChatMode AgentStreamCreateConversationRequestChatMode `json:"chatMode"`
	// AI model configuration id for this turn. Omit to use the agent's
	// default model.
	//
	ModelKey *string `json:"modelKey,omitzero"`
	// Provider model name (the underlying LLM identifier).
	ModelName *string `json:"modelName,omitzero"`
	// Friendly UI label for the selected model.
	ModelFriendlyName *string `json:"modelFriendlyName,omitzero"`
	// Client IANA timezone, such as `America/New_York`. Helps the agent
	// resolve relative date references in the prompt.
	//
	Timezone *string `json:"timezone,omitzero"`
	// Client time in ISO 8601 / RFC 3339 format (UTC `Z` or numeric
	// offset). Sent alongside `timezone` for time-aware answers.
	//
	CurrentTime *time.Time `json:"currentTime,omitzero"`
	// Allowed tool ids for this turn, such as `jira.create_issue`. Omit
	// to let the agent use its default toolset; send `[]` to disable
	// tools for this turn.
	//
	Tools []string `json:"tools,omitzero"`
	// AG-UI is the only supported wire protocol. When present must be
	// `"agui"`. Omitting the field is equivalent — the server always
	// uses the AG-UI vocabulary (see `AgentStreamSSEEvent`). Kept in
	// the schema for backward compatibility with callers that already
	// send it.
	//
	Protocol *AgentStreamCreateConversationRequestProtocol `json:"protocol,omitzero"`
	// Per-request agent capability toggles. Only meaningful when `chatMode`
	// selects an agent mode; ignored otherwise. Each field falls back to its
	// own `default` below when omitted — a missing flag is not uniformly
	// `true`. Omitting the whole object applies every default.
	//
	AgentCapabilities *AgentCapabilities `json:"agentCapabilities,omitzero"`
}

func (a AgentStreamCreateConversationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentStreamCreateConversationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentStreamCreateConversationRequest) GetQuery() string {
	if a == nil {
		return ""
	}
	return a.Query
}

func (a *AgentStreamCreateConversationRequest) GetRecordIds() []string {
	if a == nil {
		return nil
	}
	return a.RecordIds
}

func (a *AgentStreamCreateConversationRequest) GetFilters() *Filters {
	if a == nil {
		return nil
	}
	return a.Filters
}

func (a *AgentStreamCreateConversationRequest) GetAppliedFilters() *AppliedFilters {
	if a == nil {
		return nil
	}
	return a.AppliedFilters
}

func (a *AgentStreamCreateConversationRequest) GetAttachments() []ChatAttachmentRef {
	if a == nil {
		return nil
	}
	return a.Attachments
}

func (a *AgentStreamCreateConversationRequest) GetChatMode() AgentStreamCreateConversationRequestChatMode {
	if a == nil {
		return AgentStreamCreateConversationRequestChatMode("")
	}
	return a.ChatMode
}

func (a *AgentStreamCreateConversationRequest) GetModelKey() *string {
	if a == nil {
		return nil
	}
	return a.ModelKey
}

func (a *AgentStreamCreateConversationRequest) GetModelName() *string {
	if a == nil {
		return nil
	}
	return a.ModelName
}

func (a *AgentStreamCreateConversationRequest) GetModelFriendlyName() *string {
	if a == nil {
		return nil
	}
	return a.ModelFriendlyName
}

func (a *AgentStreamCreateConversationRequest) GetTimezone() *string {
	if a == nil {
		return nil
	}
	return a.Timezone
}

func (a *AgentStreamCreateConversationRequest) GetCurrentTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.CurrentTime
}

func (a *AgentStreamCreateConversationRequest) GetTools() []string {
	if a == nil {
		return nil
	}
	return a.Tools
}

func (a *AgentStreamCreateConversationRequest) GetProtocol() *AgentStreamCreateConversationRequestProtocol {
	if a == nil {
		return nil
	}
	return a.Protocol
}

func (a *AgentStreamCreateConversationRequest) GetAgentCapabilities() *AgentCapabilities {
	if a == nil {
		return nil
	}
	return a.AgentCapabilities
}
