// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// AgentAddMessageStreamRequestChatMode - Chat mode hint forwarded to the agent backend. Defaults to `auto`
// in the upstream AI payload when omitted.
// - `auto` lets the agent pick its default strategy.
// - `quick` favors low-latency answers over depth.
// - `verification` runs additional grounding/verification passes.
// - `deep` performs deeper retrieval and reasoning.
type AgentAddMessageStreamRequestChatMode string

const (
	AgentAddMessageStreamRequestChatModeAuto         AgentAddMessageStreamRequestChatMode = "auto"
	AgentAddMessageStreamRequestChatModeQuick        AgentAddMessageStreamRequestChatMode = "quick"
	AgentAddMessageStreamRequestChatModeVerification AgentAddMessageStreamRequestChatMode = "verification"
	AgentAddMessageStreamRequestChatModeDeep         AgentAddMessageStreamRequestChatMode = "deep"
)

func (e AgentAddMessageStreamRequestChatMode) ToPointer() *AgentAddMessageStreamRequestChatMode {
	return &e
}
func (e *AgentAddMessageStreamRequestChatMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "auto":
		fallthrough
	case "quick":
		fallthrough
	case "verification":
		fallthrough
	case "deep":
		*e = AgentAddMessageStreamRequestChatMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentAddMessageStreamRequestChatMode: %v", v)
	}
}

// AgentAddMessageStreamRequest - Request body for `POST /agents/{agentKey}/conversations/{conversationId}/messages/stream`.
// Only `query` is required; all other fields are optional overrides or
// routing hints. Unknown fields are stripped during validation.
type AgentAddMessageStreamRequest struct {
	// User follow-up prompt to append to the existing agent conversation.
	// Saved as a new `user_query` message before the upstream AI stream
	// starts.
	//
	Query string `json:"query"`
	// Optional retrieval scope (`apps` / `kb`) for this turn. Each id must
	// be a UUID or a `knowledgeBase_<orgId>` collection id. Omit to let
	// the agent use its stored defaults; send `{ "apps": [], "kb": [] }`
	// to force no knowledge sources for this turn.
	//
	Filters *Filters `json:"filters,omitzero"`
	// UI filter state persisted on the saved user message. Not used for
	// retrieval and not forwarded to the upstream agent backend.
	//
	AppliedFilters *AppliedFilters `json:"appliedFilters,omitzero"`
	// Uploaded attachments to ground this turn. Each entry references a
	// record id returned from the agent attachment upload endpoint.
	//
	Attachments []ChatAttachmentRef `json:"attachments,omitzero"`
	// Chat mode hint forwarded to the agent backend. Defaults to `auto`
	// in the upstream AI payload when omitted.
	// - `auto` lets the agent pick its default strategy.
	// - `quick` favors low-latency answers over depth.
	// - `verification` runs additional grounding/verification passes.
	// - `deep` performs deeper retrieval and reasoning.
	//
	ChatMode *AgentAddMessageStreamRequestChatMode `json:"chatMode,omitzero"`
	// AI model configuration id override for this turn. Omit to use the
	// agent's default model.
	//
	ModelKey *string `json:"modelKey,omitzero"`
	// Provider model name (the underlying LLM identifier).
	ModelName *string `json:"modelName,omitzero"`
	// Friendly UI label for the selected model.
	ModelFriendlyName *string `json:"modelFriendlyName,omitzero"`
	// Client IANA timezone, such as `America/New_York`. Helps the agent
	// resolve relative date references in the prompt.
	//
	Timezone *string `json:"timezone,omitzero"`
	// Client time in ISO 8601 / RFC 3339 format (UTC `Z` or numeric
	// offset). Sent alongside `timezone` for time-aware answers.
	//
	CurrentTime *time.Time `json:"currentTime,omitzero"`
	// Allowed tool ids for this turn, such as `jira.create_issue`. Omit
	// to let the agent use its default toolset; send `[]` to disable
	// tools for this turn.
	//
	Tools []string `json:"tools,omitzero"`
}

func (a AgentAddMessageStreamRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentAddMessageStreamRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentAddMessageStreamRequest) GetQuery() string {
	if a == nil {
		return ""
	}
	return a.Query
}

func (a *AgentAddMessageStreamRequest) GetFilters() *Filters {
	if a == nil {
		return nil
	}
	return a.Filters
}

func (a *AgentAddMessageStreamRequest) GetAppliedFilters() *AppliedFilters {
	if a == nil {
		return nil
	}
	return a.AppliedFilters
}

func (a *AgentAddMessageStreamRequest) GetAttachments() []ChatAttachmentRef {
	if a == nil {
		return nil
	}
	return a.Attachments
}

func (a *AgentAddMessageStreamRequest) GetChatMode() *AgentAddMessageStreamRequestChatMode {
	if a == nil {
		return nil
	}
	return a.ChatMode
}

func (a *AgentAddMessageStreamRequest) GetModelKey() *string {
	if a == nil {
		return nil
	}
	return a.ModelKey
}

func (a *AgentAddMessageStreamRequest) GetModelName() *string {
	if a == nil {
		return nil
	}
	return a.ModelName
}

func (a *AgentAddMessageStreamRequest) GetModelFriendlyName() *string {
	if a == nil {
		return nil
	}
	return a.ModelFriendlyName
}

func (a *AgentAddMessageStreamRequest) GetTimezone() *string {
	if a == nil {
		return nil
	}
	return a.Timezone
}

func (a *AgentAddMessageStreamRequest) GetCurrentTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.CurrentTime
}

func (a *AgentAddMessageStreamRequest) GetTools() []string {
	if a == nil {
		return nil
	}
	return a.Tools
}
