// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// AgentStreamCreateConversationRequestChatMode - Chat mode hint forwarded to the agent backend.
// - `auto` lets the agent pick its default strategy.
// - `quick` favors low-latency answers over depth.
// - `verification` runs additional grounding/verification passes.
// - `deep` performs deeper retrieval and reasoning.
type AgentStreamCreateConversationRequestChatMode string

const (
	AgentStreamCreateConversationRequestChatModeAuto         AgentStreamCreateConversationRequestChatMode = "auto"
	AgentStreamCreateConversationRequestChatModeQuick        AgentStreamCreateConversationRequestChatMode = "quick"
	AgentStreamCreateConversationRequestChatModeVerification AgentStreamCreateConversationRequestChatMode = "verification"
	AgentStreamCreateConversationRequestChatModeDeep         AgentStreamCreateConversationRequestChatMode = "deep"
)

func (e AgentStreamCreateConversationRequestChatMode) ToPointer() *AgentStreamCreateConversationRequestChatMode {
	return &e
}
func (e *AgentStreamCreateConversationRequestChatMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "auto":
		fallthrough
	case "quick":
		fallthrough
	case "verification":
		fallthrough
	case "deep":
		*e = AgentStreamCreateConversationRequestChatMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentStreamCreateConversationRequestChatMode: %v", v)
	}
}

// AgentStreamCreateConversationRequest - Request body for `POST /agents/{agentKey}/conversations/stream`. Only
// `query` is required; all other fields are optional overrides or routing
// hints. Unknown fields are stripped during validation.
type AgentStreamCreateConversationRequest struct {
	// User prompt for the first turn. Saved as the initial `user_query`
	// message and sent to the agent backend.
	//
	Query string `json:"query"`
	// Optional record ids to include as context for this turn. Each id
	// must be a 24-character MongoDB ObjectId.
	//
	RecordIds []string `json:"recordIds,omitzero"`
	// Optional retrieval scope (`apps` / `kb`) for this turn. Each id must
	// be a UUID or a `knowledgeBase_<orgId>` collection id. Omit for
	// agent defaults; send `{ "apps": [], "kb": [] }` to force no
	// knowledge sources for this turn.
	//
	Filters *Filters `json:"filters,omitzero"`
	// UI filter state persisted on the saved user message. Not used for
	// retrieval and not forwarded to the upstream agent backend.
	//
	AppliedFilters *AppliedFilters `json:"appliedFilters,omitzero"`
	// Uploaded attachments to ground this turn. Each entry references a
	// record id returned from the agent attachment upload endpoint.
	//
	Attachments []ChatAttachmentRef `json:"attachments,omitzero"`
	// Chat mode hint forwarded to the agent backend.
	// - `auto` lets the agent pick its default strategy.
	// - `quick` favors low-latency answers over depth.
	// - `verification` runs additional grounding/verification passes.
	// - `deep` performs deeper retrieval and reasoning.
	//
	ChatMode *AgentStreamCreateConversationRequestChatMode `json:"chatMode,omitzero"`
	// AI model configuration id for this turn. Omit to use the agent's
	// default model.
	//
	ModelKey *string `json:"modelKey,omitzero"`
	// Provider model name (the underlying LLM identifier).
	ModelName *string `json:"modelName,omitzero"`
	// Friendly UI label for the selected model.
	ModelFriendlyName *string `json:"modelFriendlyName,omitzero"`
	// Client IANA timezone, such as `America/New_York`. Helps the agent
	// resolve relative date references in the prompt.
	//
	Timezone *string `json:"timezone,omitzero"`
	// Client time in ISO 8601 / RFC 3339 format (UTC `Z` or numeric
	// offset). Sent alongside `timezone` for time-aware answers.
	//
	CurrentTime *time.Time `json:"currentTime,omitzero"`
	// Allowed tool ids for this turn, such as `jira.create_issue`. Omit
	// to let the agent use its default toolset; send `[]` to disable
	// tools for this turn.
	//
	Tools []string `json:"tools,omitzero"`
}

func (a AgentStreamCreateConversationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentStreamCreateConversationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentStreamCreateConversationRequest) GetQuery() string {
	if a == nil {
		return ""
	}
	return a.Query
}

func (a *AgentStreamCreateConversationRequest) GetRecordIds() []string {
	if a == nil {
		return nil
	}
	return a.RecordIds
}

func (a *AgentStreamCreateConversationRequest) GetFilters() *Filters {
	if a == nil {
		return nil
	}
	return a.Filters
}

func (a *AgentStreamCreateConversationRequest) GetAppliedFilters() *AppliedFilters {
	if a == nil {
		return nil
	}
	return a.AppliedFilters
}

func (a *AgentStreamCreateConversationRequest) GetAttachments() []ChatAttachmentRef {
	if a == nil {
		return nil
	}
	return a.Attachments
}

func (a *AgentStreamCreateConversationRequest) GetChatMode() *AgentStreamCreateConversationRequestChatMode {
	if a == nil {
		return nil
	}
	return a.ChatMode
}

func (a *AgentStreamCreateConversationRequest) GetModelKey() *string {
	if a == nil {
		return nil
	}
	return a.ModelKey
}

func (a *AgentStreamCreateConversationRequest) GetModelName() *string {
	if a == nil {
		return nil
	}
	return a.ModelName
}

func (a *AgentStreamCreateConversationRequest) GetModelFriendlyName() *string {
	if a == nil {
		return nil
	}
	return a.ModelFriendlyName
}

func (a *AgentStreamCreateConversationRequest) GetTimezone() *string {
	if a == nil {
		return nil
	}
	return a.Timezone
}

func (a *AgentStreamCreateConversationRequest) GetCurrentTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.CurrentTime
}

func (a *AgentStreamCreateConversationRequest) GetTools() []string {
	if a == nil {
		return nil
	}
	return a.Tools
}
