// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AgentCreateResponseSkill - A skill linked to the agent at creation time. Creating or updating an
// agent only links edges to skills that already exist and never writes a
// skill document, so only the name is echoed back here.
type AgentCreateResponseSkill struct {
	Name string `json:"name"`
}

func (a *AgentCreateResponseSkill) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}
