// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentCreateResponseTool struct {
	Name     string `json:"name"`
	FullName string `json:"fullName"`
	Key      string `json:"key"`
}

func (a *AgentCreateResponseTool) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AgentCreateResponseTool) GetFullName() string {
	if a == nil {
		return ""
	}
	return a.FullName
}

func (a *AgentCreateResponseTool) GetKey() string {
	if a == nil {
		return ""
	}
	return a.Key
}
