// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AgentMessageStreamSSEEventEvent string

const (
	AgentMessageStreamSSEEventEventRunStarted              AgentMessageStreamSSEEventEvent = "RUN_STARTED"
	AgentMessageStreamSSEEventEventRunFinished             AgentMessageStreamSSEEventEvent = "RUN_FINISHED"
	AgentMessageStreamSSEEventEventRunError                AgentMessageStreamSSEEventEvent = "RUN_ERROR"
	AgentMessageStreamSSEEventEventStepStarted             AgentMessageStreamSSEEventEvent = "STEP_STARTED"
	AgentMessageStreamSSEEventEventStepFinished            AgentMessageStreamSSEEventEvent = "STEP_FINISHED"
	AgentMessageStreamSSEEventEventTextMessageStart        AgentMessageStreamSSEEventEvent = "TEXT_MESSAGE_START"
	AgentMessageStreamSSEEventEventTextMessageContent      AgentMessageStreamSSEEventEvent = "TEXT_MESSAGE_CONTENT"
	AgentMessageStreamSSEEventEventTextMessageEnd          AgentMessageStreamSSEEventEvent = "TEXT_MESSAGE_END"
	AgentMessageStreamSSEEventEventReasoningStart          AgentMessageStreamSSEEventEvent = "REASONING_START"
	AgentMessageStreamSSEEventEventReasoningMessageStart   AgentMessageStreamSSEEventEvent = "REASONING_MESSAGE_START"
	AgentMessageStreamSSEEventEventReasoningMessageContent AgentMessageStreamSSEEventEvent = "REASONING_MESSAGE_CONTENT"
	AgentMessageStreamSSEEventEventReasoningMessageEnd     AgentMessageStreamSSEEventEvent = "REASONING_MESSAGE_END"
	AgentMessageStreamSSEEventEventReasoningEnd            AgentMessageStreamSSEEventEvent = "REASONING_END"
	AgentMessageStreamSSEEventEventToolCallStart           AgentMessageStreamSSEEventEvent = "TOOL_CALL_START"
	AgentMessageStreamSSEEventEventToolCallArgs            AgentMessageStreamSSEEventEvent = "TOOL_CALL_ARGS"
	AgentMessageStreamSSEEventEventToolCallEnd             AgentMessageStreamSSEEventEvent = "TOOL_CALL_END"
	AgentMessageStreamSSEEventEventToolCallResult          AgentMessageStreamSSEEventEvent = "TOOL_CALL_RESULT"
	AgentMessageStreamSSEEventEventStateDelta              AgentMessageStreamSSEEventEvent = "STATE_DELTA"
	AgentMessageStreamSSEEventEventStateSnapshot           AgentMessageStreamSSEEventEvent = "STATE_SNAPSHOT"
	AgentMessageStreamSSEEventEventCustom                  AgentMessageStreamSSEEventEvent = "CUSTOM"
	AgentMessageStreamSSEEventEventHeartbeat               AgentMessageStreamSSEEventEvent = "HEARTBEAT"
)

func (e AgentMessageStreamSSEEventEvent) ToPointer() *AgentMessageStreamSSEEventEvent {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentMessageStreamSSEEventEvent) IsExact() bool {
	if e != nil {
		switch *e {
		case "RUN_STARTED", "RUN_FINISHED", "RUN_ERROR", "STEP_STARTED", "STEP_FINISHED", "TEXT_MESSAGE_START", "TEXT_MESSAGE_CONTENT", "TEXT_MESSAGE_END", "REASONING_START", "REASONING_MESSAGE_START", "REASONING_MESSAGE_CONTENT", "REASONING_MESSAGE_END", "REASONING_END", "TOOL_CALL_START", "TOOL_CALL_ARGS", "TOOL_CALL_END", "TOOL_CALL_RESULT", "STATE_DELTA", "STATE_SNAPSHOT", "CUSTOM", "HEARTBEAT":
			return true
		}
	}
	return false
}

// AgentMessageStreamSSEEvent - Server-Sent Event envelope for `POST /agents/{agentKey}/conversations/{conversationId}/messages/stream`.
// AG-UI is the sole wire protocol.
//
// `event` carries the AG-UI type name and `data` is a JSON-encoded
// object that includes a `"type"` field matching `event`, plus
// type-specific fields. The public route requires `chatMode: quick`.
// Forwarded lifecycle events may carry `runId`, `threadId`, and
// `parentRunId`. Stable gateway-generated top-level outcomes:
//
//   - `CUSTOM` (`name: "conversation_created"`) — fired once after the
//     SSE stream opens.
//   - `RUN_FINISHED` — fired once after the upstream AI's result is
//     parsed, citations are saved, and the updated conversation is
//     persisted. The gateway emits `{ type, result }`; `result` carries
//     `{ conversation, recordsUsed, meta }`.
//   - `RUN_ERROR` — fired for runtime failures after the stream has
//     already started, including conversation lookup failures, upstream
//     AI startup failures, save failures, and stream transport errors.
//
// Gateway-generated root terminal events do not contain `runId`,
// `threadId`, or `parentRunId`.
// Clients should ignore unknown event names rather than treating them
// as errors.
type AgentMessageStreamSSEEvent struct {
	Event *AgentMessageStreamSSEEventEvent `json:"event,omitzero"`
	// JSON-encoded event payload. The decoded JSON includes a `"type"`
	// field matching `event`, plus type-specific fields. Shape depends
	// on `event`.
	//
	Data *string `json:"data,omitzero"`
}

func (a *AgentMessageStreamSSEEvent) GetEvent() *AgentMessageStreamSSEEventEvent {
	if a == nil {
		return nil
	}
	return a.Event
}

func (a *AgentMessageStreamSSEEvent) GetData() *string {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a AgentMessageStreamSSEEvent) GetEventEncoding(event string) (string, error) {
	return "string", nil
}
