// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

type AgentConversationDetailMessageMessageType string

const (
	AgentConversationDetailMessageMessageTypeUserQuery   AgentConversationDetailMessageMessageType = "user_query"
	AgentConversationDetailMessageMessageTypeBotResponse AgentConversationDetailMessageMessageType = "bot_response"
	AgentConversationDetailMessageMessageTypeError       AgentConversationDetailMessageMessageType = "error"
	AgentConversationDetailMessageMessageTypeFeedback    AgentConversationDetailMessageMessageType = "feedback"
	AgentConversationDetailMessageMessageTypeSystem      AgentConversationDetailMessageMessageType = "system"
)

func (e AgentConversationDetailMessageMessageType) ToPointer() *AgentConversationDetailMessageMessageType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentConversationDetailMessageMessageType) IsExact() bool {
	if e != nil {
		switch *e {
		case "user_query", "bot_response", "error", "feedback", "system":
			return true
		}
	}
	return false
}

type AgentConversationDetailMessageContentFormat string

const (
	AgentConversationDetailMessageContentFormatMarkdown AgentConversationDetailMessageContentFormat = "MARKDOWN"
	AgentConversationDetailMessageContentFormatJSON     AgentConversationDetailMessageContentFormat = "JSON"
	AgentConversationDetailMessageContentFormatHTML     AgentConversationDetailMessageContentFormat = "HTML"
)

func (e AgentConversationDetailMessageContentFormat) ToPointer() *AgentConversationDetailMessageContentFormat {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AgentConversationDetailMessageContentFormat) IsExact() bool {
	if e != nil {
		switch *e {
		case "MARKDOWN", "JSON", "HTML":
			return true
		}
	}
	return false
}

type Confidence string

const (
	ConfidenceVeryHigh Confidence = "Very High"
	ConfidenceHigh     Confidence = "High"
	ConfidenceMedium   Confidence = "Medium"
	ConfidenceLow      Confidence = "Low"
	ConfidenceUnknown  Confidence = "Unknown"
)

func (e Confidence) ToPointer() *Confidence {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Confidence) IsExact() bool {
	if e != nil {
		switch *e {
		case "Very High", "High", "Medium", "Low", "Unknown":
			return true
		}
	}
	return false
}

type AgentConversationDetailMessageReferenceDatum struct {
	// Display name shown to the user.
	Name *string `json:"name,omitzero"`
	// Technical identifier (numeric ID, UUID, etc.).
	ID *string `json:"id,omitzero"`
	// Item type (e.g. `project`, `issue`, `file`, `notebook`, `page`).
	Type *string `json:"type,omitzero"`
	// Source application (e.g. `jira`, `confluence`, `sharepoint`,
	// `slack`, `drive`, `gmail`).
	//
	App *string `json:"app,omitzero"`
	// URL to open the item in a browser.
	WebURL *string `json:"webUrl,omitzero"`
	// App-specific fields keyed by name (e.g. `key` for a Jira project,
	// `siteId` for a SharePoint document).
	//
	Metadata map[string]string `json:"metadata,omitzero"`
}

func (a AgentConversationDetailMessageReferenceDatum) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentConversationDetailMessageReferenceDatum) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentConversationDetailMessageReferenceDatum) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AgentConversationDetailMessageReferenceDatum) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AgentConversationDetailMessageReferenceDatum) GetType() *string {
	if a == nil {
		return nil
	}
	return a.Type
}

func (a *AgentConversationDetailMessageReferenceDatum) GetApp() *string {
	if a == nil {
		return nil
	}
	return a.App
}

func (a *AgentConversationDetailMessageReferenceDatum) GetWebURL() *string {
	if a == nil {
		return nil
	}
	return a.WebURL
}

func (a *AgentConversationDetailMessageReferenceDatum) GetMetadata() map[string]string {
	if a == nil {
		return nil
	}
	return a.Metadata
}

type AgentConversationDetailMessageMetadata struct {
	ProcessingTimeMs *float64 `json:"processingTimeMs,omitzero"`
	ModelVersion     *string  `json:"modelVersion,omitzero"`
	AiTransactionID  *string  `json:"aiTransactionId,omitzero"`
}

func (a *AgentConversationDetailMessageMetadata) GetProcessingTimeMs() *float64 {
	if a == nil {
		return nil
	}
	return a.ProcessingTimeMs
}

func (a *AgentConversationDetailMessageMetadata) GetModelVersion() *string {
	if a == nil {
		return nil
	}
	return a.ModelVersion
}

func (a *AgentConversationDetailMessageMetadata) GetAiTransactionID() *string {
	if a == nil {
		return nil
	}
	return a.AiTransactionID
}

// AgentConversationDetailMessage - Message shape returned by `GET /agents/{agentKey}/conversations/{conversationId}`.
// The response spreads the stored message document and replaces
// `citations` with populated citation objects.
type AgentConversationDetailMessage struct {
	ID                *string                                      `json:"_id,omitzero"`
	MessageType       *AgentConversationDetailMessageMessageType   `json:"messageType,omitzero"`
	Content           *string                                      `json:"content,omitzero"`
	ContentFormat     *AgentConversationDetailMessageContentFormat `json:"contentFormat,omitzero"`
	Citations         []AgentConversationDetailMessageCitation     `json:"citations,omitzero"`
	Confidence        *Confidence                                  `json:"confidence,omitzero"`
	FollowUpQuestions []FollowUpQuestion                           `json:"followUpQuestions,omitzero"`
	Feedback          []MessageFeedback                            `json:"feedback,omitzero"`
	// Reference identifiers surfaced from tool responses, used to scope
	// follow-up queries.
	//
	ReferenceData []AgentConversationDetailMessageReferenceDatum `json:"referenceData,omitzero"`
	// Files uploaded for this message turn (see
	// `POST /agents/{agentKey}/conversations/attachments/upload`).
	//
	Attachments []ChatAttachmentRef `json:"attachments,omitzero"`
	// AI model configuration recorded against a conversation or message.
	ModelInfo *ConversationModelInfo `json:"modelInfo,omitzero"`
	// Rich filter state selected by the user, used for display and persistence only.
	// This mirrors the active selection shown in the UI and is distinct from the
	// machine-readable `filters` field used for retrieval scoping.
	//
	AppliedFilters *AppliedFilters                         `json:"appliedFilters,omitzero"`
	Metadata       *AgentConversationDetailMessageMetadata `json:"metadata,omitzero"`
	CreatedAt      *time.Time                              `json:"createdAt,omitzero"`
	UpdatedAt      *time.Time                              `json:"updatedAt,omitzero"`
}

func (a AgentConversationDetailMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AgentConversationDetailMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AgentConversationDetailMessage) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AgentConversationDetailMessage) GetMessageType() *AgentConversationDetailMessageMessageType {
	if a == nil {
		return nil
	}
	return a.MessageType
}

func (a *AgentConversationDetailMessage) GetContent() *string {
	if a == nil {
		return nil
	}
	return a.Content
}

func (a *AgentConversationDetailMessage) GetContentFormat() *AgentConversationDetailMessageContentFormat {
	if a == nil {
		return nil
	}
	return a.ContentFormat
}

func (a *AgentConversationDetailMessage) GetCitations() []AgentConversationDetailMessageCitation {
	if a == nil {
		return nil
	}
	return a.Citations
}

func (a *AgentConversationDetailMessage) GetConfidence() *Confidence {
	if a == nil {
		return nil
	}
	return a.Confidence
}

func (a *AgentConversationDetailMessage) GetFollowUpQuestions() []FollowUpQuestion {
	if a == nil {
		return nil
	}
	return a.FollowUpQuestions
}

func (a *AgentConversationDetailMessage) GetFeedback() []MessageFeedback {
	if a == nil {
		return nil
	}
	return a.Feedback
}

func (a *AgentConversationDetailMessage) GetReferenceData() []AgentConversationDetailMessageReferenceDatum {
	if a == nil {
		return nil
	}
	return a.ReferenceData
}

func (a *AgentConversationDetailMessage) GetAttachments() []ChatAttachmentRef {
	if a == nil {
		return nil
	}
	return a.Attachments
}

func (a *AgentConversationDetailMessage) GetModelInfo() *ConversationModelInfo {
	if a == nil {
		return nil
	}
	return a.ModelInfo
}

func (a *AgentConversationDetailMessage) GetAppliedFilters() *AppliedFilters {
	if a == nil {
		return nil
	}
	return a.AppliedFilters
}

func (a *AgentConversationDetailMessage) GetMetadata() *AgentConversationDetailMessageMetadata {
	if a == nil {
		return nil
	}
	return a.Metadata
}

func (a *AgentConversationDetailMessage) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AgentConversationDetailMessage) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}
