// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type ApplicationJSONErrorResponseError struct {
	// Machine-readable code (e.g. `HTTP_UNAUTHORIZED`, `HTTP_FORBIDDEN`).
	Code    string `json:"code"`
	Message string `json:"message"`
	// Optional; may appear in non-production for some errors.
	Metadata map[string]any `json:"metadata,omitzero"`
}

func (a ApplicationJSONErrorResponseError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApplicationJSONErrorResponseError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ApplicationJSONErrorResponseError) GetCode() string {
	if a == nil {
		return ""
	}
	return a.Code
}

func (a *ApplicationJSONErrorResponseError) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}

func (a *ApplicationJSONErrorResponseError) GetMetadata() map[string]any {
	if a == nil {
		return nil
	}
	return a.Metadata
}
