// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// AppliedFilterNode - A single filter node selected by the user (used for display/persistence of active filters)
type AppliedFilterNode struct {
	// Unique identifier of the filter node
	ID *string `json:"id,omitzero"`
	// Display name of the filter node
	Name *string `json:"name,omitzero"`
	// Type of the node (e.g. app, recordGroup, folder, record)
	NodeType *string `json:"nodeType,omitzero"`
	// Connector identifier associated with this node
	Connector *string `json:"connector,omitzero"`
}

func (a AppliedFilterNode) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AppliedFilterNode) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AppliedFilterNode) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AppliedFilterNode) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AppliedFilterNode) GetNodeType() *string {
	if a == nil {
		return nil
	}
	return a.NodeType
}

func (a *AppliedFilterNode) GetConnector() *string {
	if a == nil {
		return nil
	}
	return a.Connector
}
