// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ChatAttachmentRef - Reference to an attachment produced by `POST /conversations/attachments/upload`
// (or the equivalent agent route). Include in create/stream/message bodies
// so the turn is sent with uploaded files.
type ChatAttachmentRef struct {
	// Attachment record id returned from the upload endpoint.
	RecordID string `json:"recordId"`
	// Original display name of the file when known.
	RecordName *string `json:"recordName,omitzero"`
	// MIME type of the uploaded file.
	MimeType *string `json:"mimeType,omitzero"`
	// File extension (e.g. `pdf`).
	Extension *string `json:"extension,omitzero"`
	// Optional synthetic record id used by the graph layer.
	VirtualRecordID *string `json:"virtualRecordId,omitzero"`
}

func (c *ChatAttachmentRef) GetRecordID() string {
	if c == nil {
		return ""
	}
	return c.RecordID
}

func (c *ChatAttachmentRef) GetRecordName() *string {
	if c == nil {
		return nil
	}
	return c.RecordName
}

func (c *ChatAttachmentRef) GetMimeType() *string {
	if c == nil {
		return nil
	}
	return c.MimeType
}

func (c *ChatAttachmentRef) GetExtension() *string {
	if c == nil {
		return nil
	}
	return c.Extension
}

func (c *ChatAttachmentRef) GetVirtualRecordID() *string {
	if c == nil {
		return nil
	}
	return c.VirtualRecordID
}
