// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ChatAttachmentUploadResponse - Success envelope returned by `POST /conversations/attachments/upload`
// and `POST /agents/{agentKey}/conversations/attachments/upload`.
type ChatAttachmentUploadResponse struct {
	// Existing conversation id echoed from the request when the upload is tied to a thread; otherwise `null`.
	//
	ConversationID *string                   `json:"conversationId"`
	Attachments    []ChatAttachmentUploadRef `json:"attachments"`
}

func (c *ChatAttachmentUploadResponse) GetConversationID() *string {
	if c == nil {
		return nil
	}
	return c.ConversationID
}

func (c *ChatAttachmentUploadResponse) GetAttachments() []ChatAttachmentUploadRef {
	if c == nil {
		return []ChatAttachmentUploadRef{}
	}
	return c.Attachments
}
