// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// ConversationStreamRequestChatMode - Optional execution mode for non-stream consumers of this shared
// request schema.
// `agent` uses the universal agent loop, while `internal_search`
// and `web_search` use their corresponding assistant search paths.
type ConversationStreamRequestChatMode string

const (
	ConversationStreamRequestChatModeAgent          ConversationStreamRequestChatMode = "agent"
	ConversationStreamRequestChatModeInternalSearch ConversationStreamRequestChatMode = "internal_search"
	ConversationStreamRequestChatModeWebSearch      ConversationStreamRequestChatMode = "web_search"
)

func (e ConversationStreamRequestChatMode) ToPointer() *ConversationStreamRequestChatMode {
	return &e
}
func (e *ConversationStreamRequestChatMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agent":
		fallthrough
	case "internal_search":
		fallthrough
	case "web_search":
		*e = ConversationStreamRequestChatMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConversationStreamRequestChatMode: %v", v)
	}
}

// ConversationStreamRequestProtocol - AG-UI is the only supported wire protocol. When present must be
// `"agui"`. Omitting the field is equivalent — the server always
// uses the AG-UI vocabulary (`RUN_STARTED`, `TEXT_MESSAGE_CONTENT`,
// etc.). Kept in the schema for backward compatibility with callers
// that already send it.
type ConversationStreamRequestProtocol string

const (
	ConversationStreamRequestProtocolAgui ConversationStreamRequestProtocol = "agui"
)

func (e ConversationStreamRequestProtocol) ToPointer() *ConversationStreamRequestProtocol {
	return &e
}
func (e *ConversationStreamRequestProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agui":
		*e = ConversationStreamRequestProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConversationStreamRequestProtocol: %v", v)
	}
}

// ConversationStreamRequest - Request body for `POST /conversations/stream`. The public stream
// requires an explicit universal execution mode.
type ConversationStreamRequest struct {
	// The user's question or prompt to start the conversation.
	// Supports natural language queries of any complexity.
	//
	Query string `json:"query"`
	// Limit the AI's knowledge scope to specific records/documents.
	// When provided, only these records will be searched for context.
	//
	RecordIds []string `json:"recordIds,omitzero"`
	// App connector instance ids and knowledge-base / record-group ids that narrow retrieval
	// for a turn. For **org assistant** chat streams, send explicit `apps` / `kb` lists.
	// For **agent** chat streams, send explicit id lists, or **omit** `filters` (and `tools`)
	// to let the service use the agent’s stored knowledge and tool configuration. Sending
	// `{ "apps": [], "kb": [] }` on an agent stream means **no** knowledge sources for that
	// turn (it is not “full org default”).
	//
	Filters *Filters `json:"filters,omitzero"`
	// Rich filter state selected by the user, used for display and persistence only.
	// This mirrors the active selection shown in the UI and is distinct from the
	// machine-readable `filters` field used for retrieval scoping.
	//
	AppliedFilters *AppliedFilters `json:"appliedFilters,omitzero"`
	// Uploaded chat attachments to associate with this conversation turn (see
	// `POST /conversations/attachments/upload`).
	//
	Attachments []ChatAttachmentRef `json:"attachments,omitzero"`
	// Identifier for the AI model configuration to use.
	// Available models depend on organization settings.
	//
	ModelKey *string `json:"modelKey,omitzero"`
	// Display name of the AI model
	ModelName *string `json:"modelName,omitzero"`
	// Friendly display name of the selected model
	ModelFriendlyName *string `json:"modelFriendlyName,omitzero"`
	// Optional execution mode for non-stream consumers of this shared
	// request schema.
	// `agent` uses the universal agent loop, while `internal_search`
	// and `web_search` use their corresponding assistant search paths.
	//
	ChatMode ConversationStreamRequestChatMode `json:"chatMode"`
	// IANA timezone identifier from the client (top-level field).
	// Used to provide time-aware context to the AI.
	//
	Timezone *string `json:"timezone,omitzero"`
	// ISO 8601 / RFC 3339 datetime from the client (top-level field; UTC `Z` or numeric offset).
	//
	CurrentTime *time.Time `json:"currentTime,omitzero"`
	// Optional list of tool identifiers (fully-qualified action names such as
	// "jira.create_issue") that the AI agent is permitted to invoke for this
	// request. When omitted the agent may use any configured tool. Applicable
	// only when `chatMode` is `agent`.
	//
	Tools []string `json:"tools,omitzero"`
	// AG-UI is the only supported wire protocol. When present must be
	// `"agui"`. Omitting the field is equivalent — the server always
	// uses the AG-UI vocabulary (`RUN_STARTED`, `TEXT_MESSAGE_CONTENT`,
	// etc.). Kept in the schema for backward compatibility with callers
	// that already send it.
	//
	Protocol *ConversationStreamRequestProtocol `json:"protocol,omitzero"`
	// Per-request agent capability toggles. Only meaningful when `chatMode`
	// selects an agent mode; ignored otherwise. Each field falls back to its
	// own `default` below when omitted — a missing flag is not uniformly
	// `true`. Omitting the whole object applies every default.
	//
	AgentCapabilities *AgentCapabilities `json:"agentCapabilities,omitzero"`
}

func (c ConversationStreamRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConversationStreamRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConversationStreamRequest) GetQuery() string {
	if c == nil {
		return ""
	}
	return c.Query
}

func (c *ConversationStreamRequest) GetRecordIds() []string {
	if c == nil {
		return nil
	}
	return c.RecordIds
}

func (c *ConversationStreamRequest) GetFilters() *Filters {
	if c == nil {
		return nil
	}
	return c.Filters
}

func (c *ConversationStreamRequest) GetAppliedFilters() *AppliedFilters {
	if c == nil {
		return nil
	}
	return c.AppliedFilters
}

func (c *ConversationStreamRequest) GetAttachments() []ChatAttachmentRef {
	if c == nil {
		return nil
	}
	return c.Attachments
}

func (c *ConversationStreamRequest) GetModelKey() *string {
	if c == nil {
		return nil
	}
	return c.ModelKey
}

func (c *ConversationStreamRequest) GetModelName() *string {
	if c == nil {
		return nil
	}
	return c.ModelName
}

func (c *ConversationStreamRequest) GetModelFriendlyName() *string {
	if c == nil {
		return nil
	}
	return c.ModelFriendlyName
}

func (c *ConversationStreamRequest) GetChatMode() ConversationStreamRequestChatMode {
	if c == nil {
		return ConversationStreamRequestChatMode("")
	}
	return c.ChatMode
}

func (c *ConversationStreamRequest) GetTimezone() *string {
	if c == nil {
		return nil
	}
	return c.Timezone
}

func (c *ConversationStreamRequest) GetCurrentTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.CurrentTime
}

func (c *ConversationStreamRequest) GetTools() []string {
	if c == nil {
		return nil
	}
	return c.Tools
}

func (c *ConversationStreamRequest) GetProtocol() *ConversationStreamRequestProtocol {
	if c == nil {
		return nil
	}
	return c.Protocol
}

func (c *ConversationStreamRequest) GetAgentCapabilities() *AgentCapabilities {
	if c == nil {
		return nil
	}
	return c.AgentCapabilities
}
