// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ConversationSharedBy - Present on conversations the caller received via share. Identifies the
// conversation initiator (the only user who can share a chat).
type ConversationSharedBy struct {
	UserID string `json:"userId"`
	// Display name, falling back to email or the user id
	Name string `json:"name"`
}

func (c *ConversationSharedBy) GetUserID() string {
	if c == nil {
		return ""
	}
	return c.UserID
}

func (c *ConversationSharedBy) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}
