// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ConversationStreamSSEEventEvent string

const (
	ConversationStreamSSEEventEventRunStarted              ConversationStreamSSEEventEvent = "RUN_STARTED"
	ConversationStreamSSEEventEventRunFinished             ConversationStreamSSEEventEvent = "RUN_FINISHED"
	ConversationStreamSSEEventEventRunError                ConversationStreamSSEEventEvent = "RUN_ERROR"
	ConversationStreamSSEEventEventStepStarted             ConversationStreamSSEEventEvent = "STEP_STARTED"
	ConversationStreamSSEEventEventStepFinished            ConversationStreamSSEEventEvent = "STEP_FINISHED"
	ConversationStreamSSEEventEventTextMessageStart        ConversationStreamSSEEventEvent = "TEXT_MESSAGE_START"
	ConversationStreamSSEEventEventTextMessageContent      ConversationStreamSSEEventEvent = "TEXT_MESSAGE_CONTENT"
	ConversationStreamSSEEventEventTextMessageEnd          ConversationStreamSSEEventEvent = "TEXT_MESSAGE_END"
	ConversationStreamSSEEventEventReasoningStart          ConversationStreamSSEEventEvent = "REASONING_START"
	ConversationStreamSSEEventEventReasoningMessageStart   ConversationStreamSSEEventEvent = "REASONING_MESSAGE_START"
	ConversationStreamSSEEventEventReasoningMessageContent ConversationStreamSSEEventEvent = "REASONING_MESSAGE_CONTENT"
	ConversationStreamSSEEventEventReasoningMessageEnd     ConversationStreamSSEEventEvent = "REASONING_MESSAGE_END"
	ConversationStreamSSEEventEventReasoningEnd            ConversationStreamSSEEventEvent = "REASONING_END"
	ConversationStreamSSEEventEventToolCallStart           ConversationStreamSSEEventEvent = "TOOL_CALL_START"
	ConversationStreamSSEEventEventToolCallArgs            ConversationStreamSSEEventEvent = "TOOL_CALL_ARGS"
	ConversationStreamSSEEventEventToolCallEnd             ConversationStreamSSEEventEvent = "TOOL_CALL_END"
	ConversationStreamSSEEventEventToolCallResult          ConversationStreamSSEEventEvent = "TOOL_CALL_RESULT"
	ConversationStreamSSEEventEventStateDelta              ConversationStreamSSEEventEvent = "STATE_DELTA"
	ConversationStreamSSEEventEventStateSnapshot           ConversationStreamSSEEventEvent = "STATE_SNAPSHOT"
	ConversationStreamSSEEventEventCustom                  ConversationStreamSSEEventEvent = "CUSTOM"
	ConversationStreamSSEEventEventHeartbeat               ConversationStreamSSEEventEvent = "HEARTBEAT"
)

func (e ConversationStreamSSEEventEvent) ToPointer() *ConversationStreamSSEEventEvent {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ConversationStreamSSEEventEvent) IsExact() bool {
	if e != nil {
		switch *e {
		case "RUN_STARTED", "RUN_FINISHED", "RUN_ERROR", "STEP_STARTED", "STEP_FINISHED", "TEXT_MESSAGE_START", "TEXT_MESSAGE_CONTENT", "TEXT_MESSAGE_END", "REASONING_START", "REASONING_MESSAGE_START", "REASONING_MESSAGE_CONTENT", "REASONING_MESSAGE_END", "REASONING_END", "TOOL_CALL_START", "TOOL_CALL_ARGS", "TOOL_CALL_END", "TOOL_CALL_RESULT", "STATE_DELTA", "STATE_SNAPSHOT", "CUSTOM", "HEARTBEAT":
			return true
		}
	}
	return false
}

// ConversationStreamSSEEvent - Server-Sent Event envelope for public conversation streams using
// `agent`, `internal_search`, or `web_search`. AG-UI is the sole wire
// protocol.
//
// `event` carries the AG-UI type name and `data` is a JSON-encoded
// object that includes a `"type"` field matching `event`, plus
// type-specific fields. Universal `agent` mode may emit `STEP_STARTED`,
// `STEP_FINISHED`, and nested child-run events carrying `parentRunId`.
// Stable gateway-generated top-level outcomes:
//
//   - `CUSTOM` (`name: "conversation_created"`) — fired once on
//     connection. Carries the newly created `conversationId` and
//     `title` so the client can link the stream to the new row before
//     any tokens arrive.
//   - `RUN_FINISHED` — fired once after the AI backend finishes.
//     The gateway emits `{ type, result }`; `result` carries the full
//     persisted `conversation` and a `meta` block.
//   - `RUN_ERROR` — fired when the stream fails. Carries a `message`
//     and optional `code`; the conversation row is marked FAILED
//     before close.
//
// Forwarded upstream lifecycle or child-run events may contain `runId`,
// `threadId`, and `parentRunId`. Gateway-generated root terminal events
// do not.
// Clients should ignore unknown event names rather than treating them
// as errors.
type ConversationStreamSSEEvent struct {
	Event *ConversationStreamSSEEventEvent `json:"event,omitzero"`
	// JSON-encoded event payload. The decoded JSON includes a `"type"`
	// field matching `event`, plus type-specific fields. Shape depends
	// on `event`. Forwarded lifecycle events may carry `runId`,
	// `threadId`, and `parentRunId`.
	//
	Data *string `json:"data,omitzero"`
}

func (c *ConversationStreamSSEEvent) GetEvent() *ConversationStreamSSEEventEvent {
	if c == nil {
		return nil
	}
	return c.Event
}

func (c *ConversationStreamSSEEvent) GetData() *string {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c ConversationStreamSSEEvent) GetEventEncoding(event string) (string, error) {
	return "string", nil
}
