// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type CreateOAuthAppRequestAllowedGrantType string

const (
	CreateOAuthAppRequestAllowedGrantTypeAuthorizationCode CreateOAuthAppRequestAllowedGrantType = "authorization_code"
	CreateOAuthAppRequestAllowedGrantTypeClientCredentials CreateOAuthAppRequestAllowedGrantType = "client_credentials"
	CreateOAuthAppRequestAllowedGrantTypeRefreshToken      CreateOAuthAppRequestAllowedGrantType = "refresh_token"
)

func (e CreateOAuthAppRequestAllowedGrantType) ToPointer() *CreateOAuthAppRequestAllowedGrantType {
	return &e
}
func (e *CreateOAuthAppRequestAllowedGrantType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "authorization_code":
		fallthrough
	case "client_credentials":
		fallthrough
	case "refresh_token":
		*e = CreateOAuthAppRequestAllowedGrantType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateOAuthAppRequestAllowedGrantType: %v", v)
	}
}

// CreateOAuthAppRequest - Request to create a new OAuth app (`createAppSchema` in `oauth.validators.ts`).
//
// **Required:** `name`, `allowedScopes`. **Optional:** `description`, `redirectUris`, `allowedGrantTypes`,
// `homepageUrl`, `privacyPolicyUrl`, `termsOfServiceUrl`, `isConfidential`, `accessTokenLifetime`, `refreshTokenLifetime`.
//
// **Redirect rule (Zod refine):** If the effective grant list includes `authorization_code`
// (including when `allowedGrantTypes` is omitted — defaults to `authorization_code` + `refresh_token`),
// at least one redirect URI is required. If grants exclude `authorization_code`, `redirectUris` may be omitted.
type CreateOAuthAppRequest struct {
	// App name (displayed to users during authorization)
	Name string `json:"name"`
	// App description
	Description *string `json:"description,omitzero"`
	// Allowed redirect URIs (max 10). Required when an effective grant list includes `authorization_code`
	// (including the default when `allowedGrantTypes` is omitted).
	//
	RedirectUris []string `json:"redirectUris,omitzero"`
	// Allowed grant types. Defaults to `["authorization_code", "refresh_token"]` if omitted (applied by the service, not Zod).
	//
	AllowedGrantTypes []CreateOAuthAppRequestAllowedGrantType `json:"allowedGrantTypes,omitzero"`
	// Scopes the app can request (non-empty)
	AllowedScopes []string `json:"allowedScopes"`
	// App homepage URL (shown during authorization)
	HomepageURL *string `json:"homepageUrl,omitzero"`
	// Privacy policy URL
	PrivacyPolicyURL *string `json:"privacyPolicyUrl,omitzero"`
	// Terms of service URL
	TermsOfServiceURL *string `json:"termsOfServiceUrl,omitzero"`
	// Whether the app can securely store secrets.
	// - `true`: Server-side app (secret required for token requests)
	// - `false`: Browser/mobile app (must use PKCE)
	//
	IsConfidential *bool `default:"true" json:"isConfidential"`
	// Access token lifetime in seconds (300–86400)
	AccessTokenLifetime *int64 `default:"3600" json:"accessTokenLifetime"`
	// Refresh token lifetime in seconds (3600–31536000)
	RefreshTokenLifetime *int64 `default:"2592000" json:"refreshTokenLifetime"`
}

func (c CreateOAuthAppRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOAuthAppRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOAuthAppRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOAuthAppRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateOAuthAppRequest) GetRedirectUris() []string {
	if c == nil {
		return nil
	}
	return c.RedirectUris
}

func (c *CreateOAuthAppRequest) GetAllowedGrantTypes() []CreateOAuthAppRequestAllowedGrantType {
	if c == nil {
		return nil
	}
	return c.AllowedGrantTypes
}

func (c *CreateOAuthAppRequest) GetAllowedScopes() []string {
	if c == nil {
		return []string{}
	}
	return c.AllowedScopes
}

func (c *CreateOAuthAppRequest) GetHomepageURL() *string {
	if c == nil {
		return nil
	}
	return c.HomepageURL
}

func (c *CreateOAuthAppRequest) GetPrivacyPolicyURL() *string {
	if c == nil {
		return nil
	}
	return c.PrivacyPolicyURL
}

func (c *CreateOAuthAppRequest) GetTermsOfServiceURL() *string {
	if c == nil {
		return nil
	}
	return c.TermsOfServiceURL
}

func (c *CreateOAuthAppRequest) GetIsConfidential() *bool {
	if c == nil {
		return nil
	}
	return c.IsConfidential
}

func (c *CreateOAuthAppRequest) GetAccessTokenLifetime() *int64 {
	if c == nil {
		return nil
	}
	return c.AccessTokenLifetime
}

func (c *CreateOAuthAppRequest) GetRefreshTokenLifetime() *int64 {
	if c == nil {
		return nil
	}
	return c.RefreshTokenLifetime
}
