// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// CreateConversationRequestProjectVisibility - Only meaningful together with `projectId`. Overrides the
// project's default sharing behavior for this one conversation:
// `private` keeps it visible to the owner only; `project` exposes
// it to every project member. Defaults from the project's
// `chatSharing` setting when omitted.
type CreateConversationRequestProjectVisibility string

const (
	CreateConversationRequestProjectVisibilityPrivate CreateConversationRequestProjectVisibility = "private"
	CreateConversationRequestProjectVisibilityProject CreateConversationRequestProjectVisibility = "project"
)

func (e CreateConversationRequestProjectVisibility) ToPointer() *CreateConversationRequestProjectVisibility {
	return &e
}
func (e *CreateConversationRequestProjectVisibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private":
		fallthrough
	case "project":
		*e = CreateConversationRequestProjectVisibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateConversationRequestProjectVisibility: %v", v)
	}
}

// CreateConversationRequestChatMode - Optional execution mode for non-stream consumers of this shared
// request schema.
// `agent` uses the universal agent loop, while `internal_search`
// and `web_search` use their corresponding assistant search paths.
type CreateConversationRequestChatMode string

const (
	CreateConversationRequestChatModeAgent          CreateConversationRequestChatMode = "agent"
	CreateConversationRequestChatModeInternalSearch CreateConversationRequestChatMode = "internal_search"
	CreateConversationRequestChatModeWebSearch      CreateConversationRequestChatMode = "web_search"
)

func (e CreateConversationRequestChatMode) ToPointer() *CreateConversationRequestChatMode {
	return &e
}
func (e *CreateConversationRequestChatMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agent":
		fallthrough
	case "internal_search":
		fallthrough
	case "web_search":
		*e = CreateConversationRequestChatMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateConversationRequestChatMode: %v", v)
	}
}

// CreateConversationRequestProtocol - AG-UI is the only supported wire protocol. When present must be
// `"agui"`. Omitting the field is equivalent — the server always
// uses the AG-UI vocabulary (`RUN_STARTED`, `TEXT_MESSAGE_CONTENT`,
// etc.). Kept in the schema for backward compatibility with callers
// that already send it.
type CreateConversationRequestProtocol string

const (
	CreateConversationRequestProtocolAgui CreateConversationRequestProtocol = "agui"
)

func (e CreateConversationRequestProtocol) ToPointer() *CreateConversationRequestProtocol {
	return &e
}
func (e *CreateConversationRequestProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agui":
		*e = CreateConversationRequestProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateConversationRequestProtocol: %v", v)
	}
}

// CreateConversationRequest - Request body for creating a new AI conversation.
//
// **Query Processing:**
//
// The query is processed through PipesHub's AI pipeline which:
//
// - Performs semantic search across indexed knowledge bases
// - Retrieves relevant context from matching documents
// - Generates a response with citations to source materials
// - Suggests follow-up questions based on the conversation
type CreateConversationRequest struct {
	// The user's question or prompt to start the conversation.
	// Supports natural language queries of any complexity.
	//
	Query string `json:"query"`
	// Limit the AI's knowledge scope to specific records/documents.
	// When provided, only these records will be searched for context.
	//
	RecordIds []string `json:"recordIds,omitzero"`
	// App connector instance ids and knowledge-base / record-group ids that narrow retrieval
	// for a turn. For **org assistant** chat streams, send explicit `apps` / `kb` lists.
	// For **agent** chat streams, send explicit id lists, or **omit** `filters` (and `tools`)
	// to let the service use the agent’s stored knowledge and tool configuration. Sending
	// `{ "apps": [], "kb": [] }` on an agent stream means **no** knowledge sources for that
	// turn (it is not “full org default”).
	//
	Filters *Filters `json:"filters,omitzero"`
	// Rich filter state selected by the user, used for display and persistence only.
	// This mirrors the active selection shown in the UI and is distinct from the
	// machine-readable `filters` field used for retrieval scoping.
	//
	AppliedFilters *AppliedFilters `json:"appliedFilters,omitzero"`
	// Uploaded chat attachments to associate with this conversation turn (see
	// `POST /conversations/attachments/upload`).
	//
	Attachments []ChatAttachmentRef `json:"attachments,omitzero"`
	// Link the new conversation to a project the caller has at least
	// viewer access to. When the project's instructions, knowledge
	// scope, or files are set and this request didn't supply its own
	// `filters`/`attachments`, they are merged in as a fallback (the
	// request always wins). Ignored on follow-up turns — only
	// meaningful when creating a conversation.
	//
	ProjectID *string `json:"projectId,omitzero"`
	// Only meaningful together with `projectId`. Overrides the
	// project's default sharing behavior for this one conversation:
	// `private` keeps it visible to the owner only; `project` exposes
	// it to every project member. Defaults from the project's
	// `chatSharing` setting when omitted.
	//
	ProjectVisibility *CreateConversationRequestProjectVisibility `json:"projectVisibility,omitzero"`
	// Identifier for the AI model configuration to use.
	// Available models depend on organization settings.
	//
	ModelKey *string `json:"modelKey,omitzero"`
	// Display name of the AI model
	ModelName *string `json:"modelName,omitzero"`
	// Friendly display name of the selected model
	ModelFriendlyName *string `json:"modelFriendlyName,omitzero"`
	// Optional execution mode for non-stream consumers of this shared
	// request schema.
	// `agent` uses the universal agent loop, while `internal_search`
	// and `web_search` use their corresponding assistant search paths.
	//
	ChatMode *CreateConversationRequestChatMode `json:"chatMode,omitzero"`
	// IANA timezone identifier from the client (top-level field).
	// Used to provide time-aware context to the AI.
	//
	Timezone *string `json:"timezone,omitzero"`
	// ISO 8601 / RFC 3339 datetime from the client (top-level field; UTC `Z` or numeric offset).
	//
	CurrentTime *time.Time `json:"currentTime,omitzero"`
	// Optional list of tool identifiers (fully-qualified action names such as
	// "jira.create_issue") that the AI agent is permitted to invoke for this
	// request. When omitted the agent may use any configured tool. Applicable
	// only when `chatMode` is `agent`.
	//
	Tools []string `json:"tools,omitzero"`
	// AG-UI is the only supported wire protocol. When present must be
	// `"agui"`. Omitting the field is equivalent — the server always
	// uses the AG-UI vocabulary (`RUN_STARTED`, `TEXT_MESSAGE_CONTENT`,
	// etc.). Kept in the schema for backward compatibility with callers
	// that already send it.
	//
	Protocol *CreateConversationRequestProtocol `json:"protocol,omitzero"`
	// Per-request agent capability toggles. Only meaningful when `chatMode`
	// selects an agent mode; ignored otherwise. Each field falls back to its
	// own `default` below when omitted — a missing flag is not uniformly
	// `true`. Omitting the whole object applies every default.
	//
	AgentCapabilities *AgentCapabilities `json:"agentCapabilities,omitzero"`
	// Client-generated identifier for this run. Send it here to enable
	// `POST /conversations/{conversationId}/cancel {runId}` while the
	// stream is still generating. Optional — a caller that never sends
	// one just can't cooperatively cancel the run.
	//
	RunID *string `json:"runId,omitzero"`
}

func (c CreateConversationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateConversationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateConversationRequest) GetQuery() string {
	if c == nil {
		return ""
	}
	return c.Query
}

func (c *CreateConversationRequest) GetRecordIds() []string {
	if c == nil {
		return nil
	}
	return c.RecordIds
}

func (c *CreateConversationRequest) GetFilters() *Filters {
	if c == nil {
		return nil
	}
	return c.Filters
}

func (c *CreateConversationRequest) GetAppliedFilters() *AppliedFilters {
	if c == nil {
		return nil
	}
	return c.AppliedFilters
}

func (c *CreateConversationRequest) GetAttachments() []ChatAttachmentRef {
	if c == nil {
		return nil
	}
	return c.Attachments
}

func (c *CreateConversationRequest) GetProjectID() *string {
	if c == nil {
		return nil
	}
	return c.ProjectID
}

func (c *CreateConversationRequest) GetProjectVisibility() *CreateConversationRequestProjectVisibility {
	if c == nil {
		return nil
	}
	return c.ProjectVisibility
}

func (c *CreateConversationRequest) GetModelKey() *string {
	if c == nil {
		return nil
	}
	return c.ModelKey
}

func (c *CreateConversationRequest) GetModelName() *string {
	if c == nil {
		return nil
	}
	return c.ModelName
}

func (c *CreateConversationRequest) GetModelFriendlyName() *string {
	if c == nil {
		return nil
	}
	return c.ModelFriendlyName
}

func (c *CreateConversationRequest) GetChatMode() *CreateConversationRequestChatMode {
	if c == nil {
		return nil
	}
	return c.ChatMode
}

func (c *CreateConversationRequest) GetTimezone() *string {
	if c == nil {
		return nil
	}
	return c.Timezone
}

func (c *CreateConversationRequest) GetCurrentTime() *time.Time {
	if c == nil {
		return nil
	}
	return c.CurrentTime
}

func (c *CreateConversationRequest) GetTools() []string {
	if c == nil {
		return nil
	}
	return c.Tools
}

func (c *CreateConversationRequest) GetProtocol() *CreateConversationRequestProtocol {
	if c == nil {
		return nil
	}
	return c.Protocol
}

func (c *CreateConversationRequest) GetAgentCapabilities() *AgentCapabilities {
	if c == nil {
		return nil
	}
	return c.AgentCapabilities
}

func (c *CreateConversationRequest) GetRunID() *string {
	if c == nil {
		return nil
	}
	return c.RunID
}
