// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

type CreateAgentConversationResponseMeta struct {
	RequestID *string   `json:"requestId,omitzero"`
	Timestamp time.Time `json:"timestamp"`
	Duration  int64     `json:"duration"`
}

func (c CreateAgentConversationResponseMeta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateAgentConversationResponseMeta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateAgentConversationResponseMeta) GetRequestID() *string {
	if c == nil {
		return nil
	}
	return c.RequestID
}

func (c *CreateAgentConversationResponseMeta) GetTimestamp() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Timestamp
}

func (c *CreateAgentConversationResponseMeta) GetDuration() int64 {
	if c == nil {
		return 0
	}
	return c.Duration
}

// CreateAgentConversationResponse - Envelope returned by `POST /agents/{agentKey}/conversations`: the
// persisted agent conversation (initial user message plus the agent's
// answer) and request metadata.
type CreateAgentConversationResponse struct {
	// A conversation with a specific AI agent. Similar to regular conversations
	// but tied to an agent's configuration and capabilities.
	//
	Conversation AgentConversation                   `json:"conversation"`
	Meta         CreateAgentConversationResponseMeta `json:"meta"`
}

func (c *CreateAgentConversationResponse) GetConversation() AgentConversation {
	if c == nil {
		return AgentConversation{}
	}
	return c.Conversation
}

func (c *CreateAgentConversationResponse) GetMeta() CreateAgentConversationResponseMeta {
	if c == nil {
		return CreateAgentConversationResponseMeta{}
	}
	return c.Meta
}
