// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

type CreateConversationResponseMeta struct {
	// Request correlation id. Omitted when upstream middleware did
	// not set a request id on the context.
	//
	RequestID *string `json:"requestId,omitzero"`
	// Server timestamp when the response was sent.
	Timestamp time.Time `json:"timestamp"`
	// Total handler duration in milliseconds.
	Duration int64 `json:"duration"`
}

func (c CreateConversationResponseMeta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateConversationResponseMeta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateConversationResponseMeta) GetRequestID() *string {
	if c == nil {
		return nil
	}
	return c.RequestID
}

func (c *CreateConversationResponseMeta) GetTimestamp() time.Time {
	if c == nil {
		return time.Time{}
	}
	return c.Timestamp
}

func (c *CreateConversationResponseMeta) GetDuration() int64 {
	if c == nil {
		return 0
	}
	return c.Duration
}

// CreateConversationResponse - Envelope returned by `POST /conversations/create`. Contains the
// persisted conversation (including the initial user message and the AI
// response) plus request metadata.
type CreateConversationResponse struct {
	// A conversation represents a chat session between a user and the AI.
	// Conversations maintain context across multiple messages and can be
	// shared, archived, and organized.
	//
	Conversation Conversation                   `json:"conversation"`
	Meta         CreateConversationResponseMeta `json:"meta"`
}

func (c *CreateConversationResponse) GetConversation() Conversation {
	if c == nil {
		return Conversation{}
	}
	return c.Conversation
}

func (c *CreateConversationResponse) GetMeta() CreateConversationResponseMeta {
	if c == nil {
		return CreateConversationResponseMeta{}
	}
	return c.Meta
}
