// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

// DeleteRecordResponseSchema - Response returned by DELETE /knowledgeBase/record/{recordId}.
type DeleteRecordResponseSchema struct {
	Success   bool                                      `json:"success"`
	Message   string                                    `json:"message"`
	RecordID  string                                    `json:"recordId"`
	Connector optionalnullable.OptionalNullable[string] `json:"connector,omitzero"`
	Timestamp optionalnullable.OptionalNullable[int64]  `json:"timestamp,omitzero"`
}

func (d *DeleteRecordResponseSchema) GetSuccess() bool {
	if d == nil {
		return false
	}
	return d.Success
}

func (d *DeleteRecordResponseSchema) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

func (d *DeleteRecordResponseSchema) GetRecordID() string {
	if d == nil {
		return ""
	}
	return d.RecordID
}

func (d *DeleteRecordResponseSchema) GetConnector() optionalnullable.OptionalNullable[string] {
	if d == nil {
		return nil
	}
	return d.Connector
}

func (d *DeleteRecordResponseSchema) GetTimestamp() optionalnullable.OptionalNullable[int64] {
	if d == nil {
		return nil
	}
	return d.Timestamp
}
