// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// Filters - App connector instance ids and knowledge-base / record-group ids that narrow retrieval
// for a turn. For **org assistant** chat streams, send explicit `apps` / `kb` lists.
// For **agent** chat streams, send explicit id lists, or **omit** `filters` (and `tools`)
// to let the service use the agent’s stored knowledge and tool configuration. Sending
// `{ "apps": [], "kb": [] }` on an agent stream means **no** knowledge sources for that
// turn (it is not “full org default”).
type Filters struct {
	// Connector instance ids to scope retrieval for this turn. Each element
	// must be a UUID (connector instance id, record-group id, etc.) or the
	// org knowledge-base collection sentinel `knowledgeBase_<orgId>`
	// (pattern `knowledgeBase_[a-zA-Z0-9_-]+`). Gateway validation matches
	// Zod `appOrKbIdSchema`.
	//
	Apps []string `json:"apps,omitzero"`
	// Knowledge-base / record-group ids to scope retrieval for this turn.
	// Each element uses the same accepted formats as `apps`: a UUID or
	// `knowledgeBase_<orgId>` (pattern `knowledgeBase_[a-zA-Z0-9_-]+`).
	//
	Kb []string `json:"kb,omitzero"`
}

func (f Filters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *Filters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *Filters) GetApps() []string {
	if f == nil {
		return nil
	}
	return f.Apps
}

func (f *Filters) GetKb() []string {
	if f == nil {
		return nil
	}
	return f.Kb
}
