// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FolderDeleteResponseSchema - Response returned by DELETE /knowledgeBase/{kbId}/folder/{folderId} (deleteFolder).
type FolderDeleteResponseSchema struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (f *FolderDeleteResponseSchema) GetSuccess() bool {
	if f == nil {
		return false
	}
	return f.Success
}

func (f *FolderDeleteResponseSchema) GetMessage() string {
	if f == nil {
		return ""
	}
	return f.Message
}
