// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FolderUpdateResponseSchema - Response returned by PUT /knowledgeBase/{kbId}/folder/{folderId} (updateFolder).
type FolderUpdateResponseSchema struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (f *FolderUpdateResponseSchema) GetSuccess() bool {
	if f == nil {
		return false
	}
	return f.Success
}

func (f *FolderUpdateResponseSchema) GetMessage() string {
	if f == nil {
		return ""
	}
	return f.Message
}
