// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// FollowUpQuestion - AI-suggested follow-up question
type FollowUpQuestion struct {
	// The suggested question text
	Question *string `json:"question,omitzero"`
	// Confidence level for this suggestion
	Confidence *string `json:"confidence,omitzero"`
	// Why this question might be relevant
	Reasoning *string `json:"reasoning,omitzero"`
}

func (f FollowUpQuestion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FollowUpQuestion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FollowUpQuestion) GetQuestion() *string {
	if f == nil {
		return nil
	}
	return f.Question
}

func (f *FollowUpQuestion) GetConfidence() *string {
	if f == nil {
		return nil
	}
	return f.Confidence
}

func (f *FollowUpQuestion) GetReasoning() *string {
	if f == nil {
		return nil
	}
	return f.Reasoning
}
