// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetAgentResponse - Success envelope returned by `GET /agents/{agentKey}`.
//
// The Node gateway forwards the backend response as an envelope with a
// top-level status/message and the detailed agent projection nested under
// `agent`.
type GetAgentResponse struct {
	Status  string `json:"status"`
	Message string `json:"message"`
	// Detailed agent projection returned by agent detail-style endpoints such
	// as `GET /agents/{agentKey}`.
	//
	Agent Agent `json:"agent"`
}

func (g *GetAgentResponse) GetStatus() string {
	if g == nil {
		return ""
	}
	return g.Status
}

func (g *GetAgentResponse) GetMessage() string {
	if g == nil {
		return ""
	}
	return g.Message
}

func (g *GetAgentResponse) GetAgent() Agent {
	if g == nil {
		return Agent{}
	}
	return g.Agent
}
