// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type GetAllKnowledgeBaseResponseSchemaUserRole string

const (
	GetAllKnowledgeBaseResponseSchemaUserRoleOwner  GetAllKnowledgeBaseResponseSchemaUserRole = "OWNER"
	GetAllKnowledgeBaseResponseSchemaUserRoleWriter GetAllKnowledgeBaseResponseSchemaUserRole = "WRITER"
	GetAllKnowledgeBaseResponseSchemaUserRoleReader GetAllKnowledgeBaseResponseSchemaUserRole = "READER"
)

func (e GetAllKnowledgeBaseResponseSchemaUserRole) ToPointer() *GetAllKnowledgeBaseResponseSchemaUserRole {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *GetAllKnowledgeBaseResponseSchemaUserRole) IsExact() bool {
	if e != nil {
		switch *e {
		case "OWNER", "WRITER", "READER":
			return true
		}
	}
	return false
}

type GetAllKnowledgeBaseResponseSchemaFolder struct {
	ID                 string  `json:"id"`
	Name               string  `json:"name"`
	CreatedAtTimestamp *int64  `json:"createdAtTimestamp,omitzero"`
	Path               *string `json:"path,omitzero"`
}

func (g *GetAllKnowledgeBaseResponseSchemaFolder) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetAllKnowledgeBaseResponseSchemaFolder) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetAllKnowledgeBaseResponseSchemaFolder) GetCreatedAtTimestamp() *int64 {
	if g == nil {
		return nil
	}
	return g.CreatedAtTimestamp
}

func (g *GetAllKnowledgeBaseResponseSchemaFolder) GetPath() *string {
	if g == nil {
		return nil
	}
	return g.Path
}

type GetAllKnowledgeBaseResponseSchemaKnowledgeBase struct {
	ID                 string                                    `json:"id"`
	Name               string                                    `json:"name"`
	ConnectorID        *string                                   `json:"connectorId"`
	CreatedAtTimestamp int64                                     `json:"createdAtTimestamp"`
	UpdatedAtTimestamp int64                                     `json:"updatedAtTimestamp"`
	CreatedBy          string                                    `json:"createdBy"`
	UserRole           GetAllKnowledgeBaseResponseSchemaUserRole `json:"userRole"`
	Folders            []GetAllKnowledgeBaseResponseSchemaFolder `json:"folders"`
}

func (g *GetAllKnowledgeBaseResponseSchemaKnowledgeBase) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetAllKnowledgeBaseResponseSchemaKnowledgeBase) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetAllKnowledgeBaseResponseSchemaKnowledgeBase) GetConnectorID() *string {
	if g == nil {
		return nil
	}
	return g.ConnectorID
}

func (g *GetAllKnowledgeBaseResponseSchemaKnowledgeBase) GetCreatedAtTimestamp() int64 {
	if g == nil {
		return 0
	}
	return g.CreatedAtTimestamp
}

func (g *GetAllKnowledgeBaseResponseSchemaKnowledgeBase) GetUpdatedAtTimestamp() int64 {
	if g == nil {
		return 0
	}
	return g.UpdatedAtTimestamp
}

func (g *GetAllKnowledgeBaseResponseSchemaKnowledgeBase) GetCreatedBy() string {
	if g == nil {
		return ""
	}
	return g.CreatedBy
}

func (g *GetAllKnowledgeBaseResponseSchemaKnowledgeBase) GetUserRole() GetAllKnowledgeBaseResponseSchemaUserRole {
	if g == nil {
		return GetAllKnowledgeBaseResponseSchemaUserRole("")
	}
	return g.UserRole
}

func (g *GetAllKnowledgeBaseResponseSchemaKnowledgeBase) GetFolders() []GetAllKnowledgeBaseResponseSchemaFolder {
	if g == nil {
		return []GetAllKnowledgeBaseResponseSchemaFolder{}
	}
	return g.Folders
}

type GetAllKnowledgeBaseResponseSchemaPagination struct {
	Page       int64 `json:"page"`
	Limit      int64 `json:"limit"`
	TotalCount int64 `json:"totalCount"`
	TotalPages int64 `json:"totalPages"`
	HasNext    bool  `json:"hasNext"`
	HasPrev    bool  `json:"hasPrev"`
}

func (g *GetAllKnowledgeBaseResponseSchemaPagination) GetPage() int64 {
	if g == nil {
		return 0
	}
	return g.Page
}

func (g *GetAllKnowledgeBaseResponseSchemaPagination) GetLimit() int64 {
	if g == nil {
		return 0
	}
	return g.Limit
}

func (g *GetAllKnowledgeBaseResponseSchemaPagination) GetTotalCount() int64 {
	if g == nil {
		return 0
	}
	return g.TotalCount
}

func (g *GetAllKnowledgeBaseResponseSchemaPagination) GetTotalPages() int64 {
	if g == nil {
		return 0
	}
	return g.TotalPages
}

func (g *GetAllKnowledgeBaseResponseSchemaPagination) GetHasNext() bool {
	if g == nil {
		return false
	}
	return g.HasNext
}

func (g *GetAllKnowledgeBaseResponseSchemaPagination) GetHasPrev() bool {
	if g == nil {
		return false
	}
	return g.HasPrev
}

type AppliedPermission string

const (
	AppliedPermissionOwner  AppliedPermission = "OWNER"
	AppliedPermissionWriter AppliedPermission = "WRITER"
	AppliedPermissionReader AppliedPermission = "READER"
)

func (e AppliedPermission) ToPointer() *AppliedPermission {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AppliedPermission) IsExact() bool {
	if e != nil {
		switch *e {
		case "OWNER", "WRITER", "READER":
			return true
		}
	}
	return false
}

type SortBy string

const (
	SortByName               SortBy = "name"
	SortByCreatedAtTimestamp SortBy = "createdAtTimestamp"
	SortByUpdatedAtTimestamp SortBy = "updatedAtTimestamp"
	SortByUserRole           SortBy = "userRole"
)

func (e SortBy) ToPointer() *SortBy {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SortBy) IsExact() bool {
	if e != nil {
		switch *e {
		case "name", "createdAtTimestamp", "updatedAtTimestamp", "userRole":
			return true
		}
	}
	return false
}

type AppliedSortOrder string

const (
	AppliedSortOrderAsc  AppliedSortOrder = "asc"
	AppliedSortOrderDesc AppliedSortOrder = "desc"
)

func (e AppliedSortOrder) ToPointer() *AppliedSortOrder {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AppliedSortOrder) IsExact() bool {
	if e != nil {
		switch *e {
		case "asc", "desc":
			return true
		}
	}
	return false
}

// GetAllKnowledgeBaseResponseSchemaApplied - Active filters. Empty `{}` when defaults. Keys use snake_case for sort
// fields (backend convention in kb_service.py).
type GetAllKnowledgeBaseResponseSchemaApplied struct {
	Search      *string             `json:"search,omitzero"`
	Permissions []AppliedPermission `json:"permissions,omitzero"`
	SortBy      *SortBy             `json:"sort_by,omitzero"`
	SortOrder   *AppliedSortOrder   `json:"sort_order,omitzero"`
}

func (g GetAllKnowledgeBaseResponseSchemaApplied) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAllKnowledgeBaseResponseSchemaApplied) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAllKnowledgeBaseResponseSchemaApplied) GetSearch() *string {
	if g == nil {
		return nil
	}
	return g.Search
}

func (g *GetAllKnowledgeBaseResponseSchemaApplied) GetPermissions() []AppliedPermission {
	if g == nil {
		return nil
	}
	return g.Permissions
}

func (g *GetAllKnowledgeBaseResponseSchemaApplied) GetSortBy() *SortBy {
	if g == nil {
		return nil
	}
	return g.SortBy
}

func (g *GetAllKnowledgeBaseResponseSchemaApplied) GetSortOrder() *AppliedSortOrder {
	if g == nil {
		return nil
	}
	return g.SortOrder
}

type AvailablePermission string

const (
	AvailablePermissionOwner  AvailablePermission = "OWNER"
	AvailablePermissionWriter AvailablePermission = "WRITER"
	AvailablePermissionReader AvailablePermission = "READER"
)

func (e AvailablePermission) ToPointer() *AvailablePermission {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AvailablePermission) IsExact() bool {
	if e != nil {
		switch *e {
		case "OWNER", "WRITER", "READER":
			return true
		}
	}
	return false
}

type SortField string

const (
	SortFieldName               SortField = "name"
	SortFieldCreatedAtTimestamp SortField = "createdAtTimestamp"
	SortFieldUpdatedAtTimestamp SortField = "updatedAtTimestamp"
	SortFieldUserRole           SortField = "userRole"
)

func (e SortField) ToPointer() *SortField {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SortField) IsExact() bool {
	if e != nil {
		switch *e {
		case "name", "createdAtTimestamp", "updatedAtTimestamp", "userRole":
			return true
		}
	}
	return false
}

type AvailableSortOrder string

const (
	AvailableSortOrderAsc  AvailableSortOrder = "asc"
	AvailableSortOrderDesc AvailableSortOrder = "desc"
)

func (e AvailableSortOrder) ToPointer() *AvailableSortOrder {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AvailableSortOrder) IsExact() bool {
	if e != nil {
		switch *e {
		case "asc", "desc":
			return true
		}
	}
	return false
}

type GetAllKnowledgeBaseResponseSchemaAvailable struct {
	Permissions []AvailablePermission `json:"permissions"`
	SortFields  []SortField           `json:"sortFields"`
	SortOrders  []AvailableSortOrder  `json:"sortOrders"`
}

func (g *GetAllKnowledgeBaseResponseSchemaAvailable) GetPermissions() []AvailablePermission {
	if g == nil {
		return []AvailablePermission{}
	}
	return g.Permissions
}

func (g *GetAllKnowledgeBaseResponseSchemaAvailable) GetSortFields() []SortField {
	if g == nil {
		return []SortField{}
	}
	return g.SortFields
}

func (g *GetAllKnowledgeBaseResponseSchemaAvailable) GetSortOrders() []AvailableSortOrder {
	if g == nil {
		return []AvailableSortOrder{}
	}
	return g.SortOrders
}

type GetAllKnowledgeBaseResponseSchemaFilters struct {
	// Active filters. Empty `{}` when defaults. Keys use snake_case for sort
	// fields (backend convention in kb_service.py).
	//
	Applied   GetAllKnowledgeBaseResponseSchemaApplied   `json:"applied"`
	Available GetAllKnowledgeBaseResponseSchemaAvailable `json:"available"`
}

func (g *GetAllKnowledgeBaseResponseSchemaFilters) GetApplied() GetAllKnowledgeBaseResponseSchemaApplied {
	if g == nil {
		return GetAllKnowledgeBaseResponseSchemaApplied{}
	}
	return g.Applied
}

func (g *GetAllKnowledgeBaseResponseSchemaFilters) GetAvailable() GetAllKnowledgeBaseResponseSchemaAvailable {
	if g == nil {
		return GetAllKnowledgeBaseResponseSchemaAvailable{}
	}
	return g.Available
}

// GetAllKnowledgeBaseResponseSchema - Response returned by GET /knowledgeBase (listKnowledgeBases).
type GetAllKnowledgeBaseResponseSchema struct {
	KnowledgeBases []GetAllKnowledgeBaseResponseSchemaKnowledgeBase `json:"knowledgeBases"`
	Pagination     GetAllKnowledgeBaseResponseSchemaPagination      `json:"pagination"`
	Filters        GetAllKnowledgeBaseResponseSchemaFilters         `json:"filters"`
}

func (g *GetAllKnowledgeBaseResponseSchema) GetKnowledgeBases() []GetAllKnowledgeBaseResponseSchemaKnowledgeBase {
	if g == nil {
		return []GetAllKnowledgeBaseResponseSchemaKnowledgeBase{}
	}
	return g.KnowledgeBases
}

func (g *GetAllKnowledgeBaseResponseSchema) GetPagination() GetAllKnowledgeBaseResponseSchemaPagination {
	if g == nil {
		return GetAllKnowledgeBaseResponseSchemaPagination{}
	}
	return g.Pagination
}

func (g *GetAllKnowledgeBaseResponseSchema) GetFilters() GetAllKnowledgeBaseResponseSchemaFilters {
	if g == nil {
		return GetAllKnowledgeBaseResponseSchemaFilters{}
	}
	return g.Filters
}
