// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

type GetRecordByIDResponseSchemaFileRecord struct {
	ID                  string                                    `json:"id"`
	OrgID               string                                    `json:"orgId"`
	Name                string                                    `json:"name"`
	Extension           string                                    `json:"extension"`
	Etag                optionalnullable.OptionalNullable[string] `json:"etag,omitzero"`
	Ctag                optionalnullable.OptionalNullable[string] `json:"ctag,omitzero"`
	Md5Checksum         optionalnullable.OptionalNullable[string] `json:"md5Checksum,omitzero"`
	QuickXorHash        optionalnullable.OptionalNullable[string] `json:"quickXorHash,omitzero"`
	Crc32Hash           optionalnullable.OptionalNullable[string] `json:"crc32Hash,omitzero"`
	Sha1Hash            optionalnullable.OptionalNullable[string] `json:"sha1Hash,omitzero"`
	Sha256Hash          optionalnullable.OptionalNullable[string] `json:"sha256Hash,omitzero"`
	MimeType            optionalnullable.OptionalNullable[string] `json:"mimeType,omitzero"`
	SizeInBytes         optionalnullable.OptionalNullable[int64]  `json:"sizeInBytes,omitzero"`
	IsFile              bool                                      `json:"isFile"`
	WebURL              optionalnullable.OptionalNullable[string] `json:"webUrl,omitzero"`
	Path                optionalnullable.OptionalNullable[string] `json:"path,omitzero"`
	LocalFsRelativePath optionalnullable.OptionalNullable[string] `json:"localFsRelativePath,omitzero"`
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetOrgID() string {
	if g == nil {
		return ""
	}
	return g.OrgID
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetExtension() string {
	if g == nil {
		return ""
	}
	return g.Extension
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetEtag() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Etag
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetCtag() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Ctag
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetMd5Checksum() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Md5Checksum
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetQuickXorHash() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.QuickXorHash
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetCrc32Hash() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Crc32Hash
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetSha1Hash() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Sha1Hash
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetSha256Hash() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Sha256Hash
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetMimeType() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.MimeType
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetSizeInBytes() optionalnullable.OptionalNullable[int64] {
	if g == nil {
		return nil
	}
	return g.SizeInBytes
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetIsFile() bool {
	if g == nil {
		return false
	}
	return g.IsFile
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetWebURL() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.WebURL
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetPath() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Path
}

func (g *GetRecordByIDResponseSchemaFileRecord) GetLocalFsRelativePath() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.LocalFsRelativePath
}

type GetRecordByIDResponseSchemaMailRecord struct {
}

type TicketRecord struct {
}

type GetRecordByIDResponseSchemaRecord struct {
	ID                  string                                    `json:"id"`
	OrgID               string                                    `json:"orgId"`
	RecordName          string                                    `json:"recordName"`
	ExternalRecordID    string                                    `json:"externalRecordId"`
	ExternalRootGroupID optionalnullable.OptionalNullable[string] `json:"externalRootGroupId,omitzero"`
	ExternalGroupID     optionalnullable.OptionalNullable[string] `json:"externalGroupId,omitzero"`
	ExternalParentID    optionalnullable.OptionalNullable[string] `json:"externalParentId,omitzero"`
	ExternalRevisionID  optionalnullable.OptionalNullable[string] `json:"externalRevisionId,omitzero"`
	RecordGroupID       optionalnullable.OptionalNullable[string] `json:"recordGroupId,omitzero"`
	ConnectorID         string                                    `json:"connectorId"`
	// Name of the source connector. Mirrors the values of the backend
	// `Connectors` enum (`backend/python/app/config/constants/arangodb.py`);
	// records store the enum value (e.g. Google Drive is `DRIVE`,
	// SharePoint Online is `SHAREPOINT ONLINE`), not the enum member name.
	//
	ConnectorName ConnectorNameEnum `json:"connectorName"`
	// Type of content. Mirrors the backend `RecordType` enum
	// (`backend/python/app/models/entities.py`); connector-sourced records
	// may use any of the connector-specific types below.
	// - FILE: Uploaded or synced documents (PDF, DOCX, etc.)
	// - DRIVE: Drive/folder container (Google Drive, OneDrive, etc.)
	// - WEBPAGE: Web pages crawled or bookmarked
	// - DATABASE: Database object (e.g. Notion database)
	// - DATASOURCE: Data source object
	// - MESSAGE: Chat/messaging content (Slack, Teams)
	// - MAIL: Email messages (Gmail, Outlook)
	// - GROUP_MAIL: Group/shared mailbox email messages
	// - TICKET: Support/issue tickets (Jira, ServiceNow)
	// - COMMENT: Comments from collaboration tools
	// - INLINE_COMMENT: Inline comments anchored to content (e.g. Confluence)
	// - CONFLUENCE_PAGE: Confluence page
	// - CONFLUENCE_BLOGPOST: Confluence blog post
	// - SHAREPOINT_PAGE: SharePoint page
	// - SHAREPOINT_LIST: SharePoint list
	// - SHAREPOINT_LIST_ITEM: SharePoint list item
	// - SHAREPOINT_DOCUMENT_LIBRARY: SharePoint document library
	// - LINK: Web link / bookmark
	// - PROJECT: Project entity (e.g. Jira project)
	// - PULL_REQUEST: Source-control pull request
	// - MEETING: Meeting record (e.g. Zoom)
	// - PRODUCT: Product entity (CRM)
	// - DEAL: Deal/opportunity entity (CRM)
	// - CASE: Case entity (CRM/support)
	// - TASK: Task entity
	// - ARTIFACT: Generated/derived artifact
	// - CODE_FILE: Source-code file
	// - SQL_TABLE: SQL table object
	// - SQL_VIEW: SQL view object
	// - OTHERS: Miscellaneous content types
	//
	RecordType                  RecordTypeEnum                            `json:"recordType"`
	Origin                      string                                    `json:"origin"`
	Version                     int64                                     `json:"version"`
	IsLatestVersion             optionalnullable.OptionalNullable[bool]   `json:"isLatestVersion,omitzero"`
	CreatedAtTimestamp          int64                                     `json:"createdAtTimestamp"`
	UpdatedAtTimestamp          int64                                     `json:"updatedAtTimestamp"`
	SourceCreatedAtTimestamp    int64                                     `json:"sourceCreatedAtTimestamp"`
	SourceLastModifiedTimestamp int64                                     `json:"sourceLastModifiedTimestamp"`
	LastSyncTimestamp           optionalnullable.OptionalNullable[int64]  `json:"lastSyncTimestamp,omitzero"`
	LastIndexTimestamp          *int64                                    `json:"lastIndexTimestamp,omitzero"`
	LastExtractionTimestamp     *int64                                    `json:"lastExtractionTimestamp,omitzero"`
	ProcessingStartedAt         optionalnullable.OptionalNullable[int64]  `json:"processingStartedAt,omitzero"`
	ParsingStatus               optionalnullable.OptionalNullable[string] `json:"parsingStatus,omitzero"`
	IndexingStatus              string                                    `json:"indexingStatus"`
	ExtractionStatus            string                                    `json:"extractionStatus"`
	Reason                      optionalnullable.OptionalNullable[string] `json:"reason,omitzero"`
	IsDeleted                   bool                                      `json:"isDeleted"`
	IsArchived                  bool                                      `json:"isArchived"`
	DeletedByUserID             optionalnullable.OptionalNullable[string] `json:"deletedByUserId,omitzero"`
	IsDirty                     optionalnullable.OptionalNullable[bool]   `json:"isDirty,omitzero"`
	IsVLMOcrProcessed           *bool                                     `json:"isVLMOcrProcessed"`
	MimeType                    *string                                   `json:"mimeType"`
	SizeInBytes                 *int64                                    `json:"sizeInBytes"`
	Md5Checksum                 optionalnullable.OptionalNullable[string] `json:"md5Checksum,omitzero"`
	VirtualRecordID             optionalnullable.OptionalNullable[string] `json:"virtualRecordId,omitzero"`
	SummaryDocumentID           optionalnullable.OptionalNullable[string] `json:"summaryDocumentId,omitzero"`
	StorageDocumentID           optionalnullable.OptionalNullable[string] `json:"storageDocumentId,omitzero"`
	WebURL                      *string                                   `json:"webUrl"`
	PreviewRenderable           optionalnullable.OptionalNullable[bool]   `json:"previewRenderable,omitzero"`
	IsShared                    optionalnullable.OptionalNullable[bool]   `json:"isShared,omitzero"`
	IsDependentNode             optionalnullable.OptionalNullable[bool]   `json:"isDependentNode,omitzero"`
	ParentNodeID                optionalnullable.OptionalNullable[string] `json:"parentNodeId,omitzero"`
	HideWeburl                  optionalnullable.OptionalNullable[bool]   `json:"hideWeburl,omitzero"`
	IsInternal                  optionalnullable.OptionalNullable[bool]   `json:"isInternal,omitzero"`
	// True for placeholder/stub records standing in for an out-of-scope ancestor (rendered read-only, no content actions; excluded from search and indexing).
	IsPlaceholder optionalnullable.OptionalNullable[bool] `json:"isPlaceholder,omitzero"`
	FileRecord    *GetRecordByIDResponseSchemaFileRecord  `json:"fileRecord"`
	MailRecord    *GetRecordByIDResponseSchemaMailRecord  `json:"mailRecord"`
	TicketRecord  *TicketRecord                           `json:"ticketRecord"`
}

func (g *GetRecordByIDResponseSchemaRecord) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRecordByIDResponseSchemaRecord) GetOrgID() string {
	if g == nil {
		return ""
	}
	return g.OrgID
}

func (g *GetRecordByIDResponseSchemaRecord) GetRecordName() string {
	if g == nil {
		return ""
	}
	return g.RecordName
}

func (g *GetRecordByIDResponseSchemaRecord) GetExternalRecordID() string {
	if g == nil {
		return ""
	}
	return g.ExternalRecordID
}

func (g *GetRecordByIDResponseSchemaRecord) GetExternalRootGroupID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.ExternalRootGroupID
}

func (g *GetRecordByIDResponseSchemaRecord) GetExternalGroupID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.ExternalGroupID
}

func (g *GetRecordByIDResponseSchemaRecord) GetExternalParentID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.ExternalParentID
}

func (g *GetRecordByIDResponseSchemaRecord) GetExternalRevisionID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.ExternalRevisionID
}

func (g *GetRecordByIDResponseSchemaRecord) GetRecordGroupID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.RecordGroupID
}

func (g *GetRecordByIDResponseSchemaRecord) GetConnectorID() string {
	if g == nil {
		return ""
	}
	return g.ConnectorID
}

func (g *GetRecordByIDResponseSchemaRecord) GetConnectorName() ConnectorNameEnum {
	if g == nil {
		return ConnectorNameEnum("")
	}
	return g.ConnectorName
}

func (g *GetRecordByIDResponseSchemaRecord) GetRecordType() RecordTypeEnum {
	if g == nil {
		return RecordTypeEnum("")
	}
	return g.RecordType
}

func (g *GetRecordByIDResponseSchemaRecord) GetOrigin() string {
	if g == nil {
		return ""
	}
	return g.Origin
}

func (g *GetRecordByIDResponseSchemaRecord) GetVersion() int64 {
	if g == nil {
		return 0
	}
	return g.Version
}

func (g *GetRecordByIDResponseSchemaRecord) GetIsLatestVersion() optionalnullable.OptionalNullable[bool] {
	if g == nil {
		return nil
	}
	return g.IsLatestVersion
}

func (g *GetRecordByIDResponseSchemaRecord) GetCreatedAtTimestamp() int64 {
	if g == nil {
		return 0
	}
	return g.CreatedAtTimestamp
}

func (g *GetRecordByIDResponseSchemaRecord) GetUpdatedAtTimestamp() int64 {
	if g == nil {
		return 0
	}
	return g.UpdatedAtTimestamp
}

func (g *GetRecordByIDResponseSchemaRecord) GetSourceCreatedAtTimestamp() int64 {
	if g == nil {
		return 0
	}
	return g.SourceCreatedAtTimestamp
}

func (g *GetRecordByIDResponseSchemaRecord) GetSourceLastModifiedTimestamp() int64 {
	if g == nil {
		return 0
	}
	return g.SourceLastModifiedTimestamp
}

func (g *GetRecordByIDResponseSchemaRecord) GetLastSyncTimestamp() optionalnullable.OptionalNullable[int64] {
	if g == nil {
		return nil
	}
	return g.LastSyncTimestamp
}

func (g *GetRecordByIDResponseSchemaRecord) GetLastIndexTimestamp() *int64 {
	if g == nil {
		return nil
	}
	return g.LastIndexTimestamp
}

func (g *GetRecordByIDResponseSchemaRecord) GetLastExtractionTimestamp() *int64 {
	if g == nil {
		return nil
	}
	return g.LastExtractionTimestamp
}

func (g *GetRecordByIDResponseSchemaRecord) GetProcessingStartedAt() optionalnullable.OptionalNullable[int64] {
	if g == nil {
		return nil
	}
	return g.ProcessingStartedAt
}

func (g *GetRecordByIDResponseSchemaRecord) GetParsingStatus() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.ParsingStatus
}

func (g *GetRecordByIDResponseSchemaRecord) GetIndexingStatus() string {
	if g == nil {
		return ""
	}
	return g.IndexingStatus
}

func (g *GetRecordByIDResponseSchemaRecord) GetExtractionStatus() string {
	if g == nil {
		return ""
	}
	return g.ExtractionStatus
}

func (g *GetRecordByIDResponseSchemaRecord) GetReason() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Reason
}

func (g *GetRecordByIDResponseSchemaRecord) GetIsDeleted() bool {
	if g == nil {
		return false
	}
	return g.IsDeleted
}

func (g *GetRecordByIDResponseSchemaRecord) GetIsArchived() bool {
	if g == nil {
		return false
	}
	return g.IsArchived
}

func (g *GetRecordByIDResponseSchemaRecord) GetDeletedByUserID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.DeletedByUserID
}

func (g *GetRecordByIDResponseSchemaRecord) GetIsDirty() optionalnullable.OptionalNullable[bool] {
	if g == nil {
		return nil
	}
	return g.IsDirty
}

func (g *GetRecordByIDResponseSchemaRecord) GetIsVLMOcrProcessed() *bool {
	if g == nil {
		return nil
	}
	return g.IsVLMOcrProcessed
}

func (g *GetRecordByIDResponseSchemaRecord) GetMimeType() *string {
	if g == nil {
		return nil
	}
	return g.MimeType
}

func (g *GetRecordByIDResponseSchemaRecord) GetSizeInBytes() *int64 {
	if g == nil {
		return nil
	}
	return g.SizeInBytes
}

func (g *GetRecordByIDResponseSchemaRecord) GetMd5Checksum() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.Md5Checksum
}

func (g *GetRecordByIDResponseSchemaRecord) GetVirtualRecordID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.VirtualRecordID
}

func (g *GetRecordByIDResponseSchemaRecord) GetSummaryDocumentID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.SummaryDocumentID
}

func (g *GetRecordByIDResponseSchemaRecord) GetStorageDocumentID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.StorageDocumentID
}

func (g *GetRecordByIDResponseSchemaRecord) GetWebURL() *string {
	if g == nil {
		return nil
	}
	return g.WebURL
}

func (g *GetRecordByIDResponseSchemaRecord) GetPreviewRenderable() optionalnullable.OptionalNullable[bool] {
	if g == nil {
		return nil
	}
	return g.PreviewRenderable
}

func (g *GetRecordByIDResponseSchemaRecord) GetIsShared() optionalnullable.OptionalNullable[bool] {
	if g == nil {
		return nil
	}
	return g.IsShared
}

func (g *GetRecordByIDResponseSchemaRecord) GetIsDependentNode() optionalnullable.OptionalNullable[bool] {
	if g == nil {
		return nil
	}
	return g.IsDependentNode
}

func (g *GetRecordByIDResponseSchemaRecord) GetParentNodeID() optionalnullable.OptionalNullable[string] {
	if g == nil {
		return nil
	}
	return g.ParentNodeID
}

func (g *GetRecordByIDResponseSchemaRecord) GetHideWeburl() optionalnullable.OptionalNullable[bool] {
	if g == nil {
		return nil
	}
	return g.HideWeburl
}

func (g *GetRecordByIDResponseSchemaRecord) GetIsInternal() optionalnullable.OptionalNullable[bool] {
	if g == nil {
		return nil
	}
	return g.IsInternal
}

func (g *GetRecordByIDResponseSchemaRecord) GetIsPlaceholder() optionalnullable.OptionalNullable[bool] {
	if g == nil {
		return nil
	}
	return g.IsPlaceholder
}

func (g *GetRecordByIDResponseSchemaRecord) GetFileRecord() *GetRecordByIDResponseSchemaFileRecord {
	if g == nil {
		return nil
	}
	return g.FileRecord
}

func (g *GetRecordByIDResponseSchemaRecord) GetMailRecord() *GetRecordByIDResponseSchemaMailRecord {
	if g == nil {
		return nil
	}
	return g.MailRecord
}

func (g *GetRecordByIDResponseSchemaRecord) GetTicketRecord() *TicketRecord {
	if g == nil {
		return nil
	}
	return g.TicketRecord
}

type GetRecordByIDResponseSchemaKnowledgeBase struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	OrgID string `json:"orgId"`
}

func (g *GetRecordByIDResponseSchemaKnowledgeBase) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRecordByIDResponseSchemaKnowledgeBase) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetRecordByIDResponseSchemaKnowledgeBase) GetOrgID() string {
	if g == nil {
		return ""
	}
	return g.OrgID
}

type GetRecordByIDResponseSchemaFolder struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (g *GetRecordByIDResponseSchemaFolder) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRecordByIDResponseSchemaFolder) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

type Language struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (l *Language) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *Language) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

type Topic struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (t *Topic) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *Topic) GetName() string {
	if t == nil {
		return ""
	}
	return t.Name
}

type Subcategories1 struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (s *Subcategories1) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Subcategories1) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

type Subcategories2 struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (s *Subcategories2) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Subcategories2) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

type Subcategories3 struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (s *Subcategories3) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *Subcategories3) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

type Department struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (d *Department) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

func (d *Department) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

type GetRecordByIDResponseSchemaCategory struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (g *GetRecordByIDResponseSchemaCategory) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRecordByIDResponseSchemaCategory) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

type GetRecordByIDResponseSchemaMetadata struct {
	Languages      []Language                            `json:"languages"`
	Topics         []Topic                               `json:"topics"`
	Subcategories1 []Subcategories1                      `json:"subcategories1"`
	Subcategories2 []Subcategories2                      `json:"subcategories2"`
	Subcategories3 []Subcategories3                      `json:"subcategories3"`
	Departments    []Department                          `json:"departments"`
	Categories     []GetRecordByIDResponseSchemaCategory `json:"categories"`
}

func (g *GetRecordByIDResponseSchemaMetadata) GetLanguages() []Language {
	if g == nil {
		return []Language{}
	}
	return g.Languages
}

func (g *GetRecordByIDResponseSchemaMetadata) GetTopics() []Topic {
	if g == nil {
		return []Topic{}
	}
	return g.Topics
}

func (g *GetRecordByIDResponseSchemaMetadata) GetSubcategories1() []Subcategories1 {
	if g == nil {
		return []Subcategories1{}
	}
	return g.Subcategories1
}

func (g *GetRecordByIDResponseSchemaMetadata) GetSubcategories2() []Subcategories2 {
	if g == nil {
		return []Subcategories2{}
	}
	return g.Subcategories2
}

func (g *GetRecordByIDResponseSchemaMetadata) GetSubcategories3() []Subcategories3 {
	if g == nil {
		return []Subcategories3{}
	}
	return g.Subcategories3
}

func (g *GetRecordByIDResponseSchemaMetadata) GetDepartments() []Department {
	if g == nil {
		return []Department{}
	}
	return g.Departments
}

func (g *GetRecordByIDResponseSchemaMetadata) GetCategories() []GetRecordByIDResponseSchemaCategory {
	if g == nil {
		return []GetRecordByIDResponseSchemaCategory{}
	}
	return g.Categories
}

type Relationship string

const (
	RelationshipOwner  Relationship = "OWNER"
	RelationshipWriter Relationship = "WRITER"
	RelationshipReader Relationship = "READER"
)

func (e Relationship) ToPointer() *Relationship {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Relationship) IsExact() bool {
	if e != nil {
		switch *e {
		case "OWNER", "WRITER", "READER":
			return true
		}
	}
	return false
}

type GetRecordByIDResponseSchemaPermission struct {
	ID           string       `json:"id"`
	Name         string       `json:"name"`
	Type         string       `json:"type"`
	Relationship Relationship `json:"relationship"`
	AccessType   string       `json:"accessType"`
}

func (g *GetRecordByIDResponseSchemaPermission) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetRecordByIDResponseSchemaPermission) GetName() string {
	if g == nil {
		return ""
	}
	return g.Name
}

func (g *GetRecordByIDResponseSchemaPermission) GetType() string {
	if g == nil {
		return ""
	}
	return g.Type
}

func (g *GetRecordByIDResponseSchemaPermission) GetRelationship() Relationship {
	if g == nil {
		return Relationship("")
	}
	return g.Relationship
}

func (g *GetRecordByIDResponseSchemaPermission) GetAccessType() string {
	if g == nil {
		return ""
	}
	return g.AccessType
}

// GetRecordByIDResponseSchema - Response returned by GET /knowledgeBase/record/{recordId}.
type GetRecordByIDResponseSchema struct {
	Record        GetRecordByIDResponseSchemaRecord         `json:"record"`
	KnowledgeBase *GetRecordByIDResponseSchemaKnowledgeBase `json:"knowledgeBase"`
	Folder        *GetRecordByIDResponseSchemaFolder        `json:"folder"`
	Metadata      GetRecordByIDResponseSchemaMetadata       `json:"metadata"`
	Permissions   []GetRecordByIDResponseSchemaPermission   `json:"permissions"`
}

func (g *GetRecordByIDResponseSchema) GetRecord() GetRecordByIDResponseSchemaRecord {
	if g == nil {
		return GetRecordByIDResponseSchemaRecord{}
	}
	return g.Record
}

func (g *GetRecordByIDResponseSchema) GetKnowledgeBase() *GetRecordByIDResponseSchemaKnowledgeBase {
	if g == nil {
		return nil
	}
	return g.KnowledgeBase
}

func (g *GetRecordByIDResponseSchema) GetFolder() *GetRecordByIDResponseSchemaFolder {
	if g == nil {
		return nil
	}
	return g.Folder
}

func (g *GetRecordByIDResponseSchema) GetMetadata() GetRecordByIDResponseSchemaMetadata {
	if g == nil {
		return GetRecordByIDResponseSchemaMetadata{}
	}
	return g.Metadata
}

func (g *GetRecordByIDResponseSchema) GetPermissions() []GetRecordByIDResponseSchemaPermission {
	if g == nil {
		return []GetRecordByIDResponseSchemaPermission{}
	}
	return g.Permissions
}
