// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// KnowledgeBaseCreateResponseUserRole - User's role in this knowledge base
type KnowledgeBaseCreateResponseUserRole string

const (
	KnowledgeBaseCreateResponseUserRoleOwner  KnowledgeBaseCreateResponseUserRole = "OWNER"
	KnowledgeBaseCreateResponseUserRoleWriter KnowledgeBaseCreateResponseUserRole = "WRITER"
	KnowledgeBaseCreateResponseUserRoleReader KnowledgeBaseCreateResponseUserRole = "READER"
)

func (e KnowledgeBaseCreateResponseUserRole) ToPointer() *KnowledgeBaseCreateResponseUserRole {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *KnowledgeBaseCreateResponseUserRole) IsExact() bool {
	if e != nil {
		switch *e {
		case "OWNER", "WRITER", "READER":
			return true
		}
	}
	return false
}

// KnowledgeBaseCreateResponse - Response returned when a knowledge base is created
type KnowledgeBaseCreateResponse struct {
	// Knowledge base ID
	ID string `json:"id"`
	// Knowledge base name
	Name string `json:"name"`
	// Creation timestamp in milliseconds
	CreatedAtTimestamp int64 `json:"createdAtTimestamp"`
	// Last update timestamp in milliseconds
	UpdatedAtTimestamp int64 `json:"updatedAtTimestamp"`
	// User's role in this knowledge base
	UserRole KnowledgeBaseCreateResponseUserRole `json:"userRole"`
}

func (k *KnowledgeBaseCreateResponse) GetID() string {
	if k == nil {
		return ""
	}
	return k.ID
}

func (k *KnowledgeBaseCreateResponse) GetName() string {
	if k == nil {
		return ""
	}
	return k.Name
}

func (k *KnowledgeBaseCreateResponse) GetCreatedAtTimestamp() int64 {
	if k == nil {
		return 0
	}
	return k.CreatedAtTimestamp
}

func (k *KnowledgeBaseCreateResponse) GetUpdatedAtTimestamp() int64 {
	if k == nil {
		return 0
	}
	return k.UpdatedAtTimestamp
}

func (k *KnowledgeBaseCreateResponse) GetUserRole() KnowledgeBaseCreateResponseUserRole {
	if k == nil {
		return KnowledgeBaseCreateResponseUserRole("")
	}
	return k.UserRole
}
