// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

// KnowledgeGraphNodeRowSchema - One row in a navigate listing. Carries the identity fields of
// KnowledgeGraphNodeRefSchema (inlined rather than composed, so this
// object can stay closed) plus display detail.
type KnowledgeGraphNodeRowSchema struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	// One of `recordGroup`, `folder`, `record`. Listings never contain `app` nodes.
	NodeType string  `json:"node_type"`
	SubType  *string `json:"sub_type"`
	IsRecord bool    `json:"is_record"`
	// Whether this node can itself be opened with `nodeId`.
	HasChildren bool `json:"has_children"`
	// e.g. size, indexing status, or relationship type.
	Detail *string `json:"detail"`
	// Link to the record in its source system. Records that carry a relative URL (uploaded/KB records) are resolved against the configured frontend public URL (see POST /configurationManager/frontendPublicUrl). The value is null when that host is not configured.
	WebURL         optionalnullable.OptionalNullable[string] `json:"web_url,omitzero"`
	IndexingStatus optionalnullable.OptionalNullable[string] `json:"indexing_status,omitzero"`
	// Creation time in the source system, epoch milliseconds. Null when the underlying node did not carry one.
	SourceCreatedAt  optionalnullable.OptionalNullable[int64] `json:"source_created_at,omitzero"`
	SourceModifiedAt optionalnullable.OptionalNullable[int64] `json:"source_modified_at,omitzero"`
	// 1-based nesting depth from the navigated parent. Always 1 for a `depth=1` listing; 2 or 3 for deeper rows when `depth` > 1.
	Level          *int64                                    `json:"level,omitzero"`
	ContextSummary optionalnullable.OptionalNullable[string] `json:"context_summary,omitzero"`
}

func (k *KnowledgeGraphNodeRowSchema) GetID() string {
	if k == nil {
		return ""
	}
	return k.ID
}

func (k *KnowledgeGraphNodeRowSchema) GetName() string {
	if k == nil {
		return ""
	}
	return k.Name
}

func (k *KnowledgeGraphNodeRowSchema) GetNodeType() string {
	if k == nil {
		return ""
	}
	return k.NodeType
}

func (k *KnowledgeGraphNodeRowSchema) GetSubType() *string {
	if k == nil {
		return nil
	}
	return k.SubType
}

func (k *KnowledgeGraphNodeRowSchema) GetIsRecord() bool {
	if k == nil {
		return false
	}
	return k.IsRecord
}

func (k *KnowledgeGraphNodeRowSchema) GetHasChildren() bool {
	if k == nil {
		return false
	}
	return k.HasChildren
}

func (k *KnowledgeGraphNodeRowSchema) GetDetail() *string {
	if k == nil {
		return nil
	}
	return k.Detail
}

func (k *KnowledgeGraphNodeRowSchema) GetWebURL() optionalnullable.OptionalNullable[string] {
	if k == nil {
		return nil
	}
	return k.WebURL
}

func (k *KnowledgeGraphNodeRowSchema) GetIndexingStatus() optionalnullable.OptionalNullable[string] {
	if k == nil {
		return nil
	}
	return k.IndexingStatus
}

func (k *KnowledgeGraphNodeRowSchema) GetSourceCreatedAt() optionalnullable.OptionalNullable[int64] {
	if k == nil {
		return nil
	}
	return k.SourceCreatedAt
}

func (k *KnowledgeGraphNodeRowSchema) GetSourceModifiedAt() optionalnullable.OptionalNullable[int64] {
	if k == nil {
		return nil
	}
	return k.SourceModifiedAt
}

func (k *KnowledgeGraphNodeRowSchema) GetLevel() *int64 {
	if k == nil {
		return nil
	}
	return k.Level
}

func (k *KnowledgeGraphNodeRowSchema) GetContextSummary() optionalnullable.OptionalNullable[string] {
	if k == nil {
		return nil
	}
	return k.ContextSummary
}
