// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

// KnowledgeGraphLookupMatchSchema - A single record resolved from an identifier.
type KnowledgeGraphLookupMatchSchema struct {
	// The Record ID. Pass it to GET /connectors/record/{recordId}/content to read the record, or as `nodeId` to GET /connectors/navigate to list what is under it.
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	RecordType     *string `json:"record_type"`
	ConnectorName  *string `json:"connector_name"`
	WebURL         *string `json:"web_url"`
	IndexingStatus *string `json:"indexing_status"`
	// Which of the supplied identifiers produced this match.
	IdentifierUsed string `json:"identifier_used"`
	// e.g. `PA-1787`, a Confluence page id, a Drive file id.
	ExternalID optionalnullable.OptionalNullable[string] `json:"external_id,omitzero"`
	// Type-specific metadata for the record — for a ticket, status, assignee, priority and dates.
	ContextBlock optionalnullable.OptionalNullable[string] `json:"context_block,omitzero"`
}

func (k *KnowledgeGraphLookupMatchSchema) GetID() string {
	if k == nil {
		return ""
	}
	return k.ID
}

func (k *KnowledgeGraphLookupMatchSchema) GetName() string {
	if k == nil {
		return ""
	}
	return k.Name
}

func (k *KnowledgeGraphLookupMatchSchema) GetRecordType() *string {
	if k == nil {
		return nil
	}
	return k.RecordType
}

func (k *KnowledgeGraphLookupMatchSchema) GetConnectorName() *string {
	if k == nil {
		return nil
	}
	return k.ConnectorName
}

func (k *KnowledgeGraphLookupMatchSchema) GetWebURL() *string {
	if k == nil {
		return nil
	}
	return k.WebURL
}

func (k *KnowledgeGraphLookupMatchSchema) GetIndexingStatus() *string {
	if k == nil {
		return nil
	}
	return k.IndexingStatus
}

func (k *KnowledgeGraphLookupMatchSchema) GetIdentifierUsed() string {
	if k == nil {
		return ""
	}
	return k.IdentifierUsed
}

func (k *KnowledgeGraphLookupMatchSchema) GetExternalID() optionalnullable.OptionalNullable[string] {
	if k == nil {
		return nil
	}
	return k.ExternalID
}

func (k *KnowledgeGraphLookupMatchSchema) GetContextBlock() optionalnullable.OptionalNullable[string] {
	if k == nil {
		return nil
	}
	return k.ContextBlock
}
