// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// KnowledgeGraphNodeRefSchema - Minimal identity reference for a node in the knowledge graph.
type KnowledgeGraphNodeRefSchema struct {
	// Node identifier. Pass it back as `nodeId` to open this node. When `is_record` is true it is also the Record ID accepted by GET /connectors/record/{recordId}/content.
	ID   string `json:"id"`
	Name string `json:"name"`
	// One of `app`, `recordGroup`, `folder`, `record`.
	NodeType string `json:"node_type"`
	// e.g. `TICKET`, `CONFLUENCE_PAGE`, `PROJECT`, `COLLECTION`.
	SubType *string `json:"sub_type"`
	// True for record and folder nodes — the nodes whose content can be read via GET /connectors/record/{recordId}/content.
	IsRecord bool `json:"is_record"`
}

func (k *KnowledgeGraphNodeRefSchema) GetID() string {
	if k == nil {
		return ""
	}
	return k.ID
}

func (k *KnowledgeGraphNodeRefSchema) GetName() string {
	if k == nil {
		return ""
	}
	return k.Name
}

func (k *KnowledgeGraphNodeRefSchema) GetNodeType() string {
	if k == nil {
		return ""
	}
	return k.NodeType
}

func (k *KnowledgeGraphNodeRefSchema) GetSubType() *string {
	if k == nil {
		return nil
	}
	return k.SubType
}

func (k *KnowledgeGraphNodeRefSchema) GetIsRecord() bool {
	if k == nil {
		return false
	}
	return k.IsRecord
}
