// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// NodeType - Type of the node (app, recordGroup, folder, or record).
type NodeType string

const (
	NodeTypeApp         NodeType = "app"
	NodeTypeRecordGroup NodeType = "recordGroup"
	NodeTypeFolder      NodeType = "folder"
	NodeTypeRecord      NodeType = "record"
)

func (e NodeType) ToPointer() *NodeType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *NodeType) IsExact() bool {
	if e != nil {
		switch *e {
		case "app", "recordGroup", "folder", "record":
			return true
		}
	}
	return false
}

// KnowledgeHubNodeOrigin - Origin type.
type KnowledgeHubNodeOrigin string

const (
	KnowledgeHubNodeOriginCollection KnowledgeHubNodeOrigin = "COLLECTION"
	KnowledgeHubNodeOriginConnector  KnowledgeHubNodeOrigin = "CONNECTOR"
)

func (e KnowledgeHubNodeOrigin) ToPointer() *KnowledgeHubNodeOrigin {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *KnowledgeHubNodeOrigin) IsExact() bool {
	if e != nil {
		switch *e {
		case "COLLECTION", "CONNECTOR":
			return true
		}
	}
	return false
}

// KnowledgeHubNodePermission - Per-item permission when `include=permissions` is requested; otherwise `null`.
type KnowledgeHubNodePermission struct {
	Role      string `json:"role"`
	CanEdit   bool   `json:"canEdit"`
	CanDelete bool   `json:"canDelete"`
}

func (k *KnowledgeHubNodePermission) GetRole() string {
	if k == nil {
		return ""
	}
	return k.Role
}

func (k *KnowledgeHubNodePermission) GetCanEdit() bool {
	if k == nil {
		return false
	}
	return k.CanEdit
}

func (k *KnowledgeHubNodePermission) GetCanDelete() bool {
	if k == nil {
		return false
	}
	return k.CanDelete
}

// KnowledgeHubNode - One element of `items`. The live API keeps keys stable and sets
// inapplicable values to JSON `null` (not omitted).
type KnowledgeHubNode struct {
	// Unique identifier for the node.
	ID string `json:"id"`
	// Display name of the node.
	Name string `json:"name"`
	// Type of the node (app, recordGroup, folder, or record).
	NodeType NodeType `json:"nodeType"`
	// Parent node ID, or `null` at the root browse level.
	ParentID *string `json:"parentId"`
	// Origin type.
	Origin KnowledgeHubNodeOrigin `json:"origin"`
	// Connector display name / key when applicable; otherwise `null`.
	Connector *string `json:"connector"`
	// Record type when `nodeType` is `record`; otherwise `null`.
	RecordType *string `json:"recordType"`
	// Record group type when `nodeType` is `recordGroup`; otherwise `null`.
	RecordGroupType *string `json:"recordGroupType"`
	// Indexing status when `nodeType` is `record`; otherwise `null`.
	IndexingStatus *string `json:"indexingStatus"`
	// Failure or status reason when set; otherwise `null`.
	Reason *string `json:"reason"`
	// True for internal/system nodes that do not originate from a source.
	IsInternal bool `json:"isInternal"`
	// Creation timestamp (epoch ms).
	CreatedAt int64 `json:"createdAt"`
	// Update timestamp (epoch ms).
	UpdatedAt int64 `json:"updatedAt"`
	// File size in bytes for file records; otherwise `null`.
	SizeInBytes *int64  `json:"sizeInBytes"`
	MimeType    *string `json:"mimeType"`
	Extension   *string `json:"extension"`
	WebURL      *string `json:"webUrl"`
	// Whether the node has children (sidebar / tree).
	HasChildren       bool  `json:"hasChildren"`
	PreviewRenderable *bool `json:"previewRenderable"`
	// Per-item permission when `include=permissions` is requested; otherwise `null`.
	Permission *KnowledgeHubNodePermission `json:"permission"`
	// Sharing status (e.g. `private`, `shared`, `team`, `workspace`) when
	// applicable; otherwise `null`.
	//
	SharingStatus *string `json:"sharingStatus"`
}

func (k *KnowledgeHubNode) GetID() string {
	if k == nil {
		return ""
	}
	return k.ID
}

func (k *KnowledgeHubNode) GetName() string {
	if k == nil {
		return ""
	}
	return k.Name
}

func (k *KnowledgeHubNode) GetNodeType() NodeType {
	if k == nil {
		return NodeType("")
	}
	return k.NodeType
}

func (k *KnowledgeHubNode) GetParentID() *string {
	if k == nil {
		return nil
	}
	return k.ParentID
}

func (k *KnowledgeHubNode) GetOrigin() KnowledgeHubNodeOrigin {
	if k == nil {
		return KnowledgeHubNodeOrigin("")
	}
	return k.Origin
}

func (k *KnowledgeHubNode) GetConnector() *string {
	if k == nil {
		return nil
	}
	return k.Connector
}

func (k *KnowledgeHubNode) GetRecordType() *string {
	if k == nil {
		return nil
	}
	return k.RecordType
}

func (k *KnowledgeHubNode) GetRecordGroupType() *string {
	if k == nil {
		return nil
	}
	return k.RecordGroupType
}

func (k *KnowledgeHubNode) GetIndexingStatus() *string {
	if k == nil {
		return nil
	}
	return k.IndexingStatus
}

func (k *KnowledgeHubNode) GetReason() *string {
	if k == nil {
		return nil
	}
	return k.Reason
}

func (k *KnowledgeHubNode) GetIsInternal() bool {
	if k == nil {
		return false
	}
	return k.IsInternal
}

func (k *KnowledgeHubNode) GetCreatedAt() int64 {
	if k == nil {
		return 0
	}
	return k.CreatedAt
}

func (k *KnowledgeHubNode) GetUpdatedAt() int64 {
	if k == nil {
		return 0
	}
	return k.UpdatedAt
}

func (k *KnowledgeHubNode) GetSizeInBytes() *int64 {
	if k == nil {
		return nil
	}
	return k.SizeInBytes
}

func (k *KnowledgeHubNode) GetMimeType() *string {
	if k == nil {
		return nil
	}
	return k.MimeType
}

func (k *KnowledgeHubNode) GetExtension() *string {
	if k == nil {
		return nil
	}
	return k.Extension
}

func (k *KnowledgeHubNode) GetWebURL() *string {
	if k == nil {
		return nil
	}
	return k.WebURL
}

func (k *KnowledgeHubNode) GetHasChildren() bool {
	if k == nil {
		return false
	}
	return k.HasChildren
}

func (k *KnowledgeHubNode) GetPreviewRenderable() *bool {
	if k == nil {
		return nil
	}
	return k.PreviewRenderable
}

func (k *KnowledgeHubNode) GetPermission() *KnowledgeHubNodePermission {
	if k == nil {
		return nil
	}
	return k.Permission
}

func (k *KnowledgeHubNode) GetSharingStatus() *string {
	if k == nil {
		return nil
	}
	return k.SharingStatus
}
