// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// FiltersParsed - Server-derived read-only object parsed from the stored
// `filters` JSON by the graph provider on GET (Neo4j / Arango).
// Empty object when `filters` is missing or invalid JSON.
type FiltersParsed struct {
	// Record-group ids (e.g. knowledge-base roots) in scope.
	RecordGroups []string `json:"recordGroups,omitzero"`
	// Individual record ids in scope.
	Records []string `json:"records,omitzero"`
}

func (f FiltersParsed) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FiltersParsed) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FiltersParsed) GetRecordGroups() []string {
	if f == nil {
		return nil
	}
	return f.RecordGroups
}

func (f *FiltersParsed) GetRecords() []string {
	if f == nil {
		return nil
	}
	return f.Records
}

// Knowledge connector / indexed scope linked to an agent, as projected by
// the graph store on `GET /agents/{agentKey}` and `GET /agents`.
type Knowledge struct {
	Key         *string `json:"_key,omitzero"`
	ConnectorID *string `json:"connectorId,omitzero"`
	Name        *string `json:"name,omitzero"`
	Type        *string `json:"type,omitzero"`
	DisplayName *string `json:"displayName,omitzero"`
	// Knowledge scope filter as stored on the graph edge. The Node `getAgent`
	// handler proxies this field unchanged from the AI service (only `agent.id`
	// is stripped). May be a JSON string (typical graph storage) or an object.
	// Prefer `filtersParsed` on GET for a guaranteed parsed object with the
	// same keys as the object branch below.
	//
	Filters *AgentFilters `json:"filters,omitzero"`
	// Server-derived read-only object parsed from the stored
	// `filters` JSON by the graph provider on GET (Neo4j / Arango).
	// Empty object when `filters` is missing or invalid JSON.
	//
	FiltersParsed *FiltersParsed `json:"filtersParsed,omitzero"`
}

func (k Knowledge) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *Knowledge) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *Knowledge) GetKey() *string {
	if k == nil {
		return nil
	}
	return k.Key
}

func (k *Knowledge) GetConnectorID() *string {
	if k == nil {
		return nil
	}
	return k.ConnectorID
}

func (k *Knowledge) GetName() *string {
	if k == nil {
		return nil
	}
	return k.Name
}

func (k *Knowledge) GetType() *string {
	if k == nil {
		return nil
	}
	return k.Type
}

func (k *Knowledge) GetDisplayName() *string {
	if k == nil {
		return nil
	}
	return k.DisplayName
}

func (k *Knowledge) GetFilters() *AgentFilters {
	if k == nil {
		return nil
	}
	return k.Filters
}

func (k *Knowledge) GetFiltersParsed() *FiltersParsed {
	if k == nil {
		return nil
	}
	return k.FiltersParsed
}
