// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// LookupRecordResponseSchema - Response returned by GET /connectors/record/lookup.
//
// Field names are snake_case, matching the knowledge graph's internal
// view models. A miss is a 200 with an empty `matches` and the input
// echoed in `not_found_identifiers` — see the endpoint description.
type LookupRecordResponseSchema struct {
	Matches []KnowledgeGraphLookupMatchSchema `json:"matches"`
	// True when one identifier resolved to more than one accessible record. Present the choice rather than taking the first, or retry with `connectorName`.
	Ambiguous bool `json:"ambiguous"`
	// Identifiers that resolved to nothing the caller can access.
	NotFoundIdentifiers []string `json:"not_found_identifiers"`
	// Per-identifier list of the connector types that were searched, so a miss can be retried against a different `connectorName`. Keys are the identifiers exactly as supplied.
	SearchedConnectors map[string][]string `json:"searched_connectors,omitzero"`
	// Flat-text rendering of the matches — each match's metadata block followed by a `Next:` line naming a follow-up call — and a line per miss naming the connectors that were searched. Capped at 25,000 bytes.
	Text string `json:"text"`
}

func (l LookupRecordResponseSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LookupRecordResponseSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LookupRecordResponseSchema) GetMatches() []KnowledgeGraphLookupMatchSchema {
	if l == nil {
		return []KnowledgeGraphLookupMatchSchema{}
	}
	return l.Matches
}

func (l *LookupRecordResponseSchema) GetAmbiguous() bool {
	if l == nil {
		return false
	}
	return l.Ambiguous
}

func (l *LookupRecordResponseSchema) GetNotFoundIdentifiers() []string {
	if l == nil {
		return []string{}
	}
	return l.NotFoundIdentifiers
}

func (l *LookupRecordResponseSchema) GetSearchedConnectors() map[string][]string {
	if l == nil {
		return nil
	}
	return l.SearchedConnectors
}

func (l *LookupRecordResponseSchema) GetText() string {
	if l == nil {
		return ""
	}
	return l.Text
}
