// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type McpServerTool struct {
	// Tool node key in the backing graph store.
	Key         *string `json:"_key,omitzero"`
	Name        *string `json:"name,omitzero"`
	FullName    *string `json:"fullName,omitzero"`
	Description *string `json:"description,omitzero"`
}

func (m *McpServerTool) GetKey() *string {
	if m == nil {
		return nil
	}
	return m.Key
}

func (m *McpServerTool) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *McpServerTool) GetFullName() *string {
	if m == nil {
		return nil
	}
	return m.FullName
}

func (m *McpServerTool) GetDescription() *string {
	if m == nil {
		return nil
	}
	return m.Description
}

// McpServer - MCP server instance linked to an agent, as projected by the graph
// store on `GET /agents/{agentKey}` and `GET /agents` — same shape as
// `Toolset`. MCP server nodes carry no secrets, only the attach-time
// snapshot of `instanceId`/`typeId`/`name`.
type McpServer struct {
	// MCP server instance node key in the backing graph store.
	Key *string `json:"_key,omitzero"`
	// MCP server attachment name (attach-time snapshot).
	Name *string `json:"name,omitzero"`
	// Human-readable MCP server product label (for example `Jira MCP`).
	DisplayName *string `json:"displayName,omitzero"`
	// Catalog server type id, when this instance came from a registered template.
	TypeID *string `json:"typeId,omitzero"`
	// Admin-created MCP server instance id.
	InstanceID *string         `json:"instanceId,omitzero"`
	Tools      []McpServerTool `json:"tools,omitzero"`
}

func (m McpServer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *McpServer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *McpServer) GetKey() *string {
	if m == nil {
		return nil
	}
	return m.Key
}

func (m *McpServer) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *McpServer) GetDisplayName() *string {
	if m == nil {
		return nil
	}
	return m.DisplayName
}

func (m *McpServer) GetTypeID() *string {
	if m == nil {
		return nil
	}
	return m.TypeID
}

func (m *McpServer) GetInstanceID() *string {
	if m == nil {
		return nil
	}
	return m.InstanceID
}

func (m *McpServer) GetTools() []McpServerTool {
	if m == nil {
		return nil
	}
	return m.Tools
}
