// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type MessagePartType string

const (
	MessagePartTypeText      MessagePartType = "text"
	MessagePartTypeReasoning MessagePartType = "reasoning"
	MessagePartTypeToolCall  MessagePartType = "tool_call"
	MessagePartTypeSubAgent  MessagePartType = "sub_agent"
)

func (e MessagePartType) ToPointer() *MessagePartType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MessagePartType) IsExact() bool {
	if e != nil {
		switch *e {
		case "text", "reasoning", "tool_call", "sub_agent":
			return true
		}
	}
	return false
}

type MessagePartStatus string

const (
	MessagePartStatusRunning   MessagePartStatus = "running"
	MessagePartStatusCompleted MessagePartStatus = "completed"
	MessagePartStatusFailed    MessagePartStatus = "failed"
	MessagePartStatusBlocked   MessagePartStatus = "blocked"
)

func (e MessagePartStatus) ToPointer() *MessagePartStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MessagePartStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "running", "completed", "failed", "blocked":
			return true
		}
	}
	return false
}

// MessagePart - One entry in the ordered agent-activity transcript for a message turn.
// Every field beyond `type` is optional and depends on the part kind, and
// `sub_agent` nests this same shape recursively under `parts`.
//
// Tool results here are always a bounded preview, never the full payload —
// `artifactId` points at the complete result.
type MessagePart struct {
	Type        *MessagePartType `json:"type,omitzero"`
	Content     *string          `json:"content,omitzero"`
	ToolCallID  *string          `json:"toolCallId,omitzero"`
	ToolName    *string          `json:"toolName,omitzero"`
	DisplayName *string          `json:"displayName,omitzero"`
	Args        *string          `json:"args,omitzero"`
	// Human-readable summary of `args`, computed server-side.
	ArgsSummary   *string            `json:"argsSummary,omitzero"`
	Status        *MessagePartStatus `json:"status,omitzero"`
	ResultPreview *string            `json:"resultPreview,omitzero"`
	// Human-readable summary of the tool result, computed server-side from
	// the full untruncated output.
	//
	ResultSummary *string `json:"resultSummary,omitzero"`
	// Blob-backed artifact id for the full tool result.
	ArtifactID *string `json:"artifactId,omitzero"`
	RunID      *string `json:"runId,omitzero"`
	RoleName   *string `json:"roleName,omitzero"`
	// Set on the single root-level `text` part carrying the answer. Every
	// other root `text` part is an abandoned preamble turn. Never set on
	// child parts nested under a `sub_agent`.
	//
	IsFinal *bool `json:"isFinal,omitzero"`
	// Nested transcript of a `sub_agent` part.
	Parts []MessagePart `json:"parts,omitzero"`
}

func (m MessagePart) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MessagePart) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MessagePart) GetType() *MessagePartType {
	if m == nil {
		return nil
	}
	return m.Type
}

func (m *MessagePart) GetContent() *string {
	if m == nil {
		return nil
	}
	return m.Content
}

func (m *MessagePart) GetToolCallID() *string {
	if m == nil {
		return nil
	}
	return m.ToolCallID
}

func (m *MessagePart) GetToolName() *string {
	if m == nil {
		return nil
	}
	return m.ToolName
}

func (m *MessagePart) GetDisplayName() *string {
	if m == nil {
		return nil
	}
	return m.DisplayName
}

func (m *MessagePart) GetArgs() *string {
	if m == nil {
		return nil
	}
	return m.Args
}

func (m *MessagePart) GetArgsSummary() *string {
	if m == nil {
		return nil
	}
	return m.ArgsSummary
}

func (m *MessagePart) GetStatus() *MessagePartStatus {
	if m == nil {
		return nil
	}
	return m.Status
}

func (m *MessagePart) GetResultPreview() *string {
	if m == nil {
		return nil
	}
	return m.ResultPreview
}

func (m *MessagePart) GetResultSummary() *string {
	if m == nil {
		return nil
	}
	return m.ResultSummary
}

func (m *MessagePart) GetArtifactID() *string {
	if m == nil {
		return nil
	}
	return m.ArtifactID
}

func (m *MessagePart) GetRunID() *string {
	if m == nil {
		return nil
	}
	return m.RunID
}

func (m *MessagePart) GetRoleName() *string {
	if m == nil {
		return nil
	}
	return m.RoleName
}

func (m *MessagePart) GetIsFinal() *bool {
	if m == nil {
		return nil
	}
	return m.IsFinal
}

func (m *MessagePart) GetParts() []MessagePart {
	if m == nil {
		return nil
	}
	return m.Parts
}
