// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// MessageMessageType - Type of message:
// <ul>
// <li><code>user_query</code> - User's question or input</li>
// <li><code>bot_response</code> - AI-generated response</li>
// <li><code>error</code> - Error message from the system</li>
// <li><code>feedback</code> - User feedback on a response</li>
// <li><code>system</code> - System notification or status</li>
// </ul>
type MessageMessageType string

const (
	MessageMessageTypeUserQuery   MessageMessageType = "user_query"
	MessageMessageTypeBotResponse MessageMessageType = "bot_response"
	MessageMessageTypeError       MessageMessageType = "error"
	MessageMessageTypeFeedback    MessageMessageType = "feedback"
	MessageMessageTypeSystem      MessageMessageType = "system"
)

func (e MessageMessageType) ToPointer() *MessageMessageType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MessageMessageType) IsExact() bool {
	if e != nil {
		switch *e {
		case "user_query", "bot_response", "error", "feedback", "system":
			return true
		}
	}
	return false
}

// MessageContentFormat - Format of the content for rendering
type MessageContentFormat string

const (
	MessageContentFormatMarkdown MessageContentFormat = "MARKDOWN"
	MessageContentFormatJSON     MessageContentFormat = "JSON"
	MessageContentFormatHTML     MessageContentFormat = "HTML"
)

func (e MessageContentFormat) ToPointer() *MessageContentFormat {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MessageContentFormat) IsExact() bool {
	if e != nil {
		switch *e {
		case "MARKDOWN", "JSON", "HTML":
			return true
		}
	}
	return false
}

type MessageMetadata struct {
	// Time taken to generate response in milliseconds
	ProcessingTimeMs *float64 `json:"processingTimeMs,omitzero"`
	// Version of the AI model used
	ModelVersion *string `json:"modelVersion,omitzero"`
	// Transaction ID for tracking in AI backend
	AiTransactionID *string `json:"aiTransactionId,omitzero"`
	// Additional context or reasoning
	Reason *string `json:"reason,omitzero"`
}

func (m *MessageMetadata) GetProcessingTimeMs() *float64 {
	if m == nil {
		return nil
	}
	return m.ProcessingTimeMs
}

func (m *MessageMetadata) GetModelVersion() *string {
	if m == nil {
		return nil
	}
	return m.ModelVersion
}

func (m *MessageMetadata) GetAiTransactionID() *string {
	if m == nil {
		return nil
	}
	return m.AiTransactionID
}

func (m *MessageMetadata) GetReason() *string {
	if m == nil {
		return nil
	}
	return m.Reason
}

type MessageReferenceDatum struct {
	// Display name shown to the user.
	Name *string `json:"name,omitzero"`
	// Technical identifier (numeric ID, UUID, etc.).
	ID *string `json:"id,omitzero"`
	// Item type (e.g. `project`, `issue`, `file`, `notebook`, `page`).
	Type *string `json:"type,omitzero"`
	// Source application (e.g. `jira`, `confluence`, `sharepoint`,
	// `slack`, `drive`, `gmail`).
	//
	App *string `json:"app,omitzero"`
	// URL to open the item in a browser.
	WebURL *string `json:"webUrl,omitzero"`
	// App-specific fields keyed by name (e.g. `key` for a Jira project,
	// `siteId` for a SharePoint document).
	//
	Metadata map[string]string `json:"metadata,omitzero"`
}

func (m MessageReferenceDatum) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MessageReferenceDatum) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MessageReferenceDatum) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MessageReferenceDatum) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *MessageReferenceDatum) GetType() *string {
	if m == nil {
		return nil
	}
	return m.Type
}

func (m *MessageReferenceDatum) GetApp() *string {
	if m == nil {
		return nil
	}
	return m.App
}

func (m *MessageReferenceDatum) GetWebURL() *string {
	if m == nil {
		return nil
	}
	return m.WebURL
}

func (m *MessageReferenceDatum) GetMetadata() map[string]string {
	if m == nil {
		return nil
	}
	return m.Metadata
}

// Message - A single message within a conversation. Messages can be user queries,
// AI responses, system messages, or error notifications.
type Message struct {
	// Unique message identifier
	ID *string `json:"_id,omitzero"`
	// Type of message:
	// <ul>
	// <li><code>user_query</code> - User's question or input</li>
	// <li><code>bot_response</code> - AI-generated response</li>
	// <li><code>error</code> - Error message from the system</li>
	// <li><code>feedback</code> - User feedback on a response</li>
	// <li><code>system</code> - System notification or status</li>
	// </ul>
	//
	MessageType *MessageMessageType `json:"messageType,omitzero"`
	// The message text content
	Content *string `json:"content,omitzero"`
	// Format of the content for rendering
	ContentFormat *MessageContentFormat `default:"MARKDOWN" json:"contentFormat"`
	// References to source documents used in the response
	Citations []CitationReference `json:"citations,omitzero"`
	// AI's confidence level in the response
	Confidence *string `json:"confidence,omitzero"`
	// Suggested follow-up questions
	FollowUpQuestions []FollowUpQuestion `json:"followUpQuestions,omitzero"`
	// User feedback on this message
	Feedback []MessageFeedback `json:"feedback,omitzero"`
	Metadata *MessageMetadata  `json:"metadata,omitzero"`
	// AI model configuration recorded against a conversation or message.
	ModelInfo *ConversationModelInfo `json:"modelInfo,omitzero"`
	// Rich filter state selected by the user, used for display and persistence only.
	// This mirrors the active selection shown in the UI and is distinct from the
	// machine-readable `filters` field used for retrieval scoping.
	//
	AppliedFilters *AppliedFilters `json:"appliedFilters,omitzero"`
	// Reference identifiers extracted from tool responses, used to scope
	// follow-up queries (for example Jira project keys or record IDs).
	//
	ReferenceData []MessageReferenceDatum `json:"referenceData,omitzero"`
	// Files uploaded for this message turn (see
	// `POST /conversations/attachments/upload`).
	//
	Attachments []ChatAttachmentRef `json:"attachments,omitzero"`
	CreatedAt   *time.Time          `json:"createdAt,omitzero"`
	UpdatedAt   *time.Time          `json:"updatedAt,omitzero"`
}

func (m Message) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Message) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *Message) GetID() *string {
	if m == nil {
		return nil
	}
	return m.ID
}

func (m *Message) GetMessageType() *MessageMessageType {
	if m == nil {
		return nil
	}
	return m.MessageType
}

func (m *Message) GetContent() *string {
	if m == nil {
		return nil
	}
	return m.Content
}

func (m *Message) GetContentFormat() *MessageContentFormat {
	if m == nil {
		return nil
	}
	return m.ContentFormat
}

func (m *Message) GetCitations() []CitationReference {
	if m == nil {
		return nil
	}
	return m.Citations
}

func (m *Message) GetConfidence() *string {
	if m == nil {
		return nil
	}
	return m.Confidence
}

func (m *Message) GetFollowUpQuestions() []FollowUpQuestion {
	if m == nil {
		return nil
	}
	return m.FollowUpQuestions
}

func (m *Message) GetFeedback() []MessageFeedback {
	if m == nil {
		return nil
	}
	return m.Feedback
}

func (m *Message) GetMetadata() *MessageMetadata {
	if m == nil {
		return nil
	}
	return m.Metadata
}

func (m *Message) GetModelInfo() *ConversationModelInfo {
	if m == nil {
		return nil
	}
	return m.ModelInfo
}

func (m *Message) GetAppliedFilters() *AppliedFilters {
	if m == nil {
		return nil
	}
	return m.AppliedFilters
}

func (m *Message) GetReferenceData() []MessageReferenceDatum {
	if m == nil {
		return nil
	}
	return m.ReferenceData
}

func (m *Message) GetAttachments() []ChatAttachmentRef {
	if m == nil {
		return nil
	}
	return m.Attachments
}

func (m *Message) GetCreatedAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.CreatedAt
}

func (m *Message) GetUpdatedAt() *time.Time {
	if m == nil {
		return nil
	}
	return m.UpdatedAt
}
