// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

type Meta struct {
	// Server-side request identifier. Read from the `X-Request-ID`
	// header when supplied, otherwise auto-generated, so this field
	// is always present.
	//
	RequestID string    `json:"requestId"`
	Timestamp time.Time `json:"timestamp"`
	// Server-side processing time in milliseconds.
	Duration int64 `json:"duration"`
}

func (m Meta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *Meta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *Meta) GetRequestID() string {
	if m == nil {
		return ""
	}
	return m.RequestID
}

func (m *Meta) GetTimestamp() time.Time {
	if m == nil {
		return time.Time{}
	}
	return m.Timestamp
}

func (m *Meta) GetDuration() int64 {
	if m == nil {
		return 0
	}
	return m.Duration
}

// MessageFeedbackUpdateResponse - Gateway response after appending feedback to a bot-response message.
type MessageFeedbackUpdateResponse struct {
	// Conversation the feedback was attached to.
	ConversationID string `json:"conversationId"`
	// Message the feedback was attached to.
	MessageID string `json:"messageId"`
	// The feedback entry just appended to the message. Echoes the fields
	// supplied in the request plus server-stamped `feedbackProvider`,
	// `timestamp`, and `metrics`.
	//
	Feedback MessageFeedbackAppendEntry `json:"feedback"`
	Meta     Meta                       `json:"meta"`
}

func (m *MessageFeedbackUpdateResponse) GetConversationID() string {
	if m == nil {
		return ""
	}
	return m.ConversationID
}

func (m *MessageFeedbackUpdateResponse) GetMessageID() string {
	if m == nil {
		return ""
	}
	return m.MessageID
}

func (m *MessageFeedbackUpdateResponse) GetFeedback() MessageFeedbackAppendEntry {
	if m == nil {
		return MessageFeedbackAppendEntry{}
	}
	return m.Feedback
}

func (m *MessageFeedbackUpdateResponse) GetMeta() Meta {
	if m == nil {
		return Meta{}
	}
	return m.Meta
}
