// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type MessageFeedbackAppendEntryCategory string

const (
	MessageFeedbackAppendEntryCategoryIncorrectInformation  MessageFeedbackAppendEntryCategory = "incorrect_information"
	MessageFeedbackAppendEntryCategoryMissingInformation    MessageFeedbackAppendEntryCategory = "missing_information"
	MessageFeedbackAppendEntryCategoryIrrelevantInformation MessageFeedbackAppendEntryCategory = "irrelevant_information"
	MessageFeedbackAppendEntryCategoryUnclearExplanation    MessageFeedbackAppendEntryCategory = "unclear_explanation"
	MessageFeedbackAppendEntryCategoryPoorCitations         MessageFeedbackAppendEntryCategory = "poor_citations"
	MessageFeedbackAppendEntryCategoryExcellentAnswer       MessageFeedbackAppendEntryCategory = "excellent_answer"
	MessageFeedbackAppendEntryCategoryHelpfulCitations      MessageFeedbackAppendEntryCategory = "helpful_citations"
	MessageFeedbackAppendEntryCategoryWellExplained         MessageFeedbackAppendEntryCategory = "well_explained"
	MessageFeedbackAppendEntryCategoryOther                 MessageFeedbackAppendEntryCategory = "other"
)

func (e MessageFeedbackAppendEntryCategory) ToPointer() *MessageFeedbackAppendEntryCategory {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *MessageFeedbackAppendEntryCategory) IsExact() bool {
	if e != nil {
		switch *e {
		case "incorrect_information", "missing_information", "irrelevant_information", "unclear_explanation", "poor_citations", "excellent_answer", "helpful_citations", "well_explained", "other":
			return true
		}
	}
	return false
}

// MessageFeedbackAppendEntryComments - Echoed free-text comments from the request.
type MessageFeedbackAppendEntryComments struct {
	Positive *string `json:"positive,omitzero"`
	Negative *string `json:"negative,omitzero"`
}

func (m *MessageFeedbackAppendEntryComments) GetPositive() *string {
	if m == nil {
		return nil
	}
	return m.Positive
}

func (m *MessageFeedbackAppendEntryComments) GetNegative() *string {
	if m == nil {
		return nil
	}
	return m.Negative
}

// MessageFeedbackAppendEntry - The feedback entry just appended to the message. Echoes the fields
// supplied in the request plus server-stamped `feedbackProvider`,
// `timestamp`, and `metrics`.
type MessageFeedbackAppendEntry struct {
	// Echoed from the request when supplied.
	IsHelpful *bool `json:"isHelpful,omitzero"`
	// Echoed categories from the request.
	Categories []MessageFeedbackAppendEntryCategory `json:"categories,omitzero"`
	// Echoed free-text comments from the request.
	Comments *MessageFeedbackAppendEntryComments `json:"comments,omitzero"`
	// User who submitted the feedback. Always present.
	FeedbackProvider string `json:"feedbackProvider"`
	// Submission time as epoch milliseconds (not an ISO 8601 datetime).
	// Always present.
	//
	Timestamp int64 `json:"timestamp"`
	// Telemetry recorded server-side alongside the feedback. Always present
	// on append responses.
	//
	Metrics MessageFeedbackAppendMetrics `json:"metrics"`
}

func (m MessageFeedbackAppendEntry) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MessageFeedbackAppendEntry) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MessageFeedbackAppendEntry) GetIsHelpful() *bool {
	if m == nil {
		return nil
	}
	return m.IsHelpful
}

func (m *MessageFeedbackAppendEntry) GetCategories() []MessageFeedbackAppendEntryCategory {
	if m == nil {
		return nil
	}
	return m.Categories
}

func (m *MessageFeedbackAppendEntry) GetComments() *MessageFeedbackAppendEntryComments {
	if m == nil {
		return nil
	}
	return m.Comments
}

func (m *MessageFeedbackAppendEntry) GetFeedbackProvider() string {
	if m == nil {
		return ""
	}
	return m.FeedbackProvider
}

func (m *MessageFeedbackAppendEntry) GetTimestamp() int64 {
	if m == nil {
		return 0
	}
	return m.Timestamp
}

func (m *MessageFeedbackAppendEntry) GetMetrics() MessageFeedbackAppendMetrics {
	if m == nil {
		return MessageFeedbackAppendMetrics{}
	}
	return m.Metrics
}
