// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// OAuthAppResponseStatus - App status
type OAuthAppResponseStatus string

const (
	OAuthAppResponseStatusActive    OAuthAppResponseStatus = "active"
	OAuthAppResponseStatusSuspended OAuthAppResponseStatus = "suspended"
	OAuthAppResponseStatusRevoked   OAuthAppResponseStatus = "revoked"
)

func (e OAuthAppResponseStatus) ToPointer() *OAuthAppResponseStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OAuthAppResponseStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "suspended", "revoked":
			return true
		}
	}
	return false
}

// OAuthAppResponse - OAuth app details (without secret). Fields under `required:` always appear
// in `toAppResponse` (`oauth.app.service.ts`); optional URL/description fields
// are only present when set by the caller.
type OAuthAppResponse struct {
	// App ID
	ID string `json:"id"`
	// URL-friendly app slug
	Slug string `json:"slug"`
	// OAuth client ID
	ClientID string `json:"clientId"`
	// App name
	Name string `json:"name"`
	// App description
	Description *string `json:"description,omitzero"`
	// Allowed redirect URIs (always returned; may be empty)
	RedirectUris []string `json:"redirectUris"`
	// Allowed grant types
	AllowedGrantTypes []string `json:"allowedGrantTypes"`
	// Allowed scopes
	AllowedScopes []string `json:"allowedScopes"`
	// App status
	Status OAuthAppResponseStatus `json:"status"`
	// App homepage
	HomepageURL *string `json:"homepageUrl,omitzero"`
	// Privacy policy URL
	PrivacyPolicyURL *string `json:"privacyPolicyUrl,omitzero"`
	// Terms of service URL
	TermsOfServiceURL *string `json:"termsOfServiceUrl,omitzero"`
	// Whether app is a confidential client
	IsConfidential bool `json:"isConfidential"`
	// Access token lifetime in seconds
	AccessTokenLifetime int64 `json:"accessTokenLifetime"`
	// Refresh token lifetime in seconds
	RefreshTokenLifetime int64 `json:"refreshTokenLifetime"`
	// Creation timestamp
	CreatedAt time.Time `json:"createdAt"`
	// Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

func (o OAuthAppResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OAuthAppResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OAuthAppResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OAuthAppResponse) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *OAuthAppResponse) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *OAuthAppResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OAuthAppResponse) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OAuthAppResponse) GetRedirectUris() []string {
	if o == nil {
		return []string{}
	}
	return o.RedirectUris
}

func (o *OAuthAppResponse) GetAllowedGrantTypes() []string {
	if o == nil {
		return []string{}
	}
	return o.AllowedGrantTypes
}

func (o *OAuthAppResponse) GetAllowedScopes() []string {
	if o == nil {
		return []string{}
	}
	return o.AllowedScopes
}

func (o *OAuthAppResponse) GetStatus() OAuthAppResponseStatus {
	if o == nil {
		return OAuthAppResponseStatus("")
	}
	return o.Status
}

func (o *OAuthAppResponse) GetHomepageURL() *string {
	if o == nil {
		return nil
	}
	return o.HomepageURL
}

func (o *OAuthAppResponse) GetPrivacyPolicyURL() *string {
	if o == nil {
		return nil
	}
	return o.PrivacyPolicyURL
}

func (o *OAuthAppResponse) GetTermsOfServiceURL() *string {
	if o == nil {
		return nil
	}
	return o.TermsOfServiceURL
}

func (o *OAuthAppResponse) GetIsConfidential() bool {
	if o == nil {
		return false
	}
	return o.IsConfidential
}

func (o *OAuthAppResponse) GetAccessTokenLifetime() int64 {
	if o == nil {
		return 0
	}
	return o.AccessTokenLifetime
}

func (o *OAuthAppResponse) GetRefreshTokenLifetime() int64 {
	if o == nil {
		return 0
	}
	return o.RefreshTokenLifetime
}

func (o *OAuthAppResponse) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *OAuthAppResponse) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}
