// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// TokenType - Type of token
type TokenType string

const (
	TokenTypeAccess  TokenType = "access"
	TokenTypeRefresh TokenType = "refresh"
)

func (e TokenType) ToPointer() *TokenType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *TokenType) IsExact() bool {
	if e != nil {
		switch *e {
		case "access", "refresh":
			return true
		}
	}
	return false
}

// OAuthTokenListItem - Information about an issued token (one element returned by `listTokensForApp`
// in `oauth_token.service.ts`). `userId` is omitted for client-credentials access
// tokens; all other fields are always populated.
type OAuthTokenListItem struct {
	// Token ID
	ID string `json:"id"`
	// Type of token
	TokenType TokenType `json:"tokenType"`
	// User ID (omitted for client-credentials access tokens)
	UserID *string `json:"userId,omitzero"`
	// Granted scopes
	Scopes []string `json:"scopes"`
	// Token creation time
	CreatedAt time.Time `json:"createdAt"`
	// Token expiration time
	ExpiresAt time.Time `json:"expiresAt"`
	// Whether token has been revoked
	IsRevoked bool `json:"isRevoked"`
}

func (o OAuthTokenListItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OAuthTokenListItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OAuthTokenListItem) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OAuthTokenListItem) GetTokenType() TokenType {
	if o == nil {
		return TokenType("")
	}
	return o.TokenType
}

func (o *OAuthTokenListItem) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *OAuthTokenListItem) GetScopes() []string {
	if o == nil {
		return []string{}
	}
	return o.Scopes
}

func (o *OAuthTokenListItem) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *OAuthTokenListItem) GetExpiresAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.ExpiresAt
}

func (o *OAuthTokenListItem) GetIsRevoked() bool {
	if o == nil {
		return false
	}
	return o.IsRevoked
}
