// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ErrorEnum - Error code. Common values:
// - `invalid_request` - Missing or invalid parameter
// - `invalid_client` - Client authentication failed
// - `invalid_grant` - Invalid authorization code or refresh token
// - `unauthorized_client` - Client not authorized for this grant type
// - `unsupported_grant_type` - Grant type not supported
// - `invalid_scope` - Requested scope is invalid or exceeds allowed
// - `access_denied` - User denied authorization
type ErrorEnum string

const (
	ErrorEnumInvalidRequest       ErrorEnum = "invalid_request"
	ErrorEnumInvalidClient        ErrorEnum = "invalid_client"
	ErrorEnumInvalidGrant         ErrorEnum = "invalid_grant"
	ErrorEnumUnauthorizedClient   ErrorEnum = "unauthorized_client"
	ErrorEnumUnsupportedGrantType ErrorEnum = "unsupported_grant_type"
	ErrorEnumInvalidScope         ErrorEnum = "invalid_scope"
	ErrorEnumAccessDenied         ErrorEnum = "access_denied"
	ErrorEnumServerError          ErrorEnum = "server_error"
)

func (e ErrorEnum) ToPointer() *ErrorEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ErrorEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "invalid_request", "invalid_client", "invalid_grant", "unauthorized_client", "unsupported_grant_type", "invalid_scope", "access_denied", "server_error":
			return true
		}
	}
	return false
}
