// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

type OAuthClientManagementRateLimitErrorError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	// Seconds until the limit window resets (when `Retry-After` is present); may be null.
	RetryAfter optionalnullable.OptionalNullable[int64] `json:"retryAfter,omitzero"`
}

func (o *OAuthClientManagementRateLimitErrorError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *OAuthClientManagementRateLimitErrorError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *OAuthClientManagementRateLimitErrorError) GetRetryAfter() optionalnullable.OptionalNullable[int64] {
	if o == nil {
		return nil
	}
	return o.RetryAfter
}
