// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// OAuthAppTokensListResponse - Response body for `GET /oauth-clients/{appId}/tokens` (`listAppTokens`).
type OAuthAppTokensListResponse struct {
	// Active access and refresh tokens for the app
	Tokens []OAuthTokenListItem `json:"tokens"`
}

func (o *OAuthAppTokensListResponse) GetTokens() []OAuthTokenListItem {
	if o == nil {
		return []OAuthTokenListItem{}
	}
	return o.Tokens
}
