// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// PatWithSecret - A personal access token as seen by its own creator (one element of
// `GET /personal-access-tokens`'s `tokens` array, or the `token` object
// returned by `POST /personal-access-tokens` before `accessToken` is added).
type PatWithSecret struct {
	// Token ID
	ID string `json:"id"`
	// Token name
	Name string `json:"name"`
	// Granted scopes
	Scopes    []string  `json:"scopes"`
	CreatedAt time.Time `json:"createdAt"`
	// Expiry timestamp. A `"never"`-expiry token is stored as a
	// ~100-year-out date, not a literal null — treat anything decades
	// out as "never" rather than a real deadline.
	//
	ExpiresAt time.Time `json:"expiresAt"`
	// Last time this token successfully authenticated a request.
	// Throttled server-side to update at most once per 5 minutes per
	// token; absent if the token has never been used.
	//
	LastUsedAt *time.Time `json:"lastUsedAt,omitzero"`
	// The raw token, `phpat_`-prefixed. Returned **only** in this
	// creation response — only its hash is stored server-side, so
	// it cannot be retrieved again later.
	//
	AccessToken string `json:"accessToken"`
}

func (p PatWithSecret) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PatWithSecret) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PatWithSecret) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatWithSecret) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *PatWithSecret) GetScopes() []string {
	if p == nil {
		return []string{}
	}
	return p.Scopes
}

func (p *PatWithSecret) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *PatWithSecret) GetExpiresAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.ExpiresAt
}

func (p *PatWithSecret) GetLastUsedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.LastUsedAt
}

func (p *PatWithSecret) GetAccessToken() string {
	if p == nil {
		return ""
	}
	return p.AccessToken
}
