// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// ProjectKnowledgeScope - Retrieval scope (app connector / knowledge-base ids) inherited by
// every conversation in the project when the request itself carries no
// `filters`. Same id shapes as `Filters`.
type ProjectKnowledgeScope struct {
	// Connector instance ids scoping this project's default retrieval.
	Apps []string `json:"apps,omitzero"`
	// Knowledge-base app ids scoping this project's default retrieval.
	Kb []string `json:"kb,omitzero"`
}

func (p ProjectKnowledgeScope) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProjectKnowledgeScope) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *ProjectKnowledgeScope) GetApps() []string {
	if p == nil {
		return nil
	}
	return p.Apps
}

func (p *ProjectKnowledgeScope) GetKb() []string {
	if p == nil {
		return nil
	}
	return p.Kb
}
