// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
	"time"
)

// ProjectListItemVisibility - `org` makes the project (and, per `chatSharing`, its
// `project`-visible conversations) readable by every member of the
// organization, without adding them to `members[]`. Also grants
// the organization's synthetic all-members team `READER` access
// on the linked hidden Collection.
type ProjectListItemVisibility string

const (
	ProjectListItemVisibilityPrivate ProjectListItemVisibility = "private"
	ProjectListItemVisibilityOrg     ProjectListItemVisibility = "org"
)

func (e ProjectListItemVisibility) ToPointer() *ProjectListItemVisibility {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProjectListItemVisibility) IsExact() bool {
	if e != nil {
		switch *e {
		case "private", "org":
			return true
		}
	}
	return false
}

// ProjectListItemChatSharing - Owner-controlled default for new conversations created in this
// project. `private` keeps new chats visible to their own owner
// only; `members` exposes them to every project member
// (`projectVisibility: project`). A conversation's own
// `projectVisibility` can override this default per-chat.
type ProjectListItemChatSharing string

const (
	ProjectListItemChatSharingPrivate ProjectListItemChatSharing = "private"
	ProjectListItemChatSharingMembers ProjectListItemChatSharing = "members"
)

func (e ProjectListItemChatSharing) ToPointer() *ProjectListItemChatSharing {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProjectListItemChatSharing) IsExact() bool {
	if e != nil {
		switch *e {
		case "private", "members":
			return true
		}
	}
	return false
}

// ProjectListItemRole - Caller's effective role on this project (owner, explicit
// member role, or `viewer` via `visibility: org`).
type ProjectListItemRole string

const (
	ProjectListItemRoleOwner  ProjectListItemRole = "owner"
	ProjectListItemRoleEditor ProjectListItemRole = "editor"
	ProjectListItemRoleViewer ProjectListItemRole = "viewer"
)

func (e ProjectListItemRole) ToPointer() *ProjectListItemRole {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ProjectListItemRole) IsExact() bool {
	if e != nil {
		switch *e {
		case "owner", "editor", "viewer":
			return true
		}
	}
	return false
}

// ProjectListItem - Project summary returned by `GET /projects`, enriched with request-computed fields.
type ProjectListItem struct {
	ID    *string `json:"_id,omitzero"`
	OrgID *string `json:"orgId,omitzero"`
	// Owner. Ownership never transfers.
	UserID      *string `json:"userId,omitzero"`
	Name        *string `json:"name,omitzero"`
	Description *string `json:"description,omitzero"`
	Icon        *string `json:"icon,omitzero"`
	Color       *string `json:"color,omitzero"`
	// Injected into every conversation in this project as a dedicated,
	// author-attributed `project_instructions` prompt section — additive,
	// never overrides agent identity or system prompts.
	//
	Instructions *string `json:"instructions,omitzero"`
	// Retrieval scope (app connector / knowledge-base ids) inherited by
	// every conversation in the project when the request itself carries no
	// `filters`. Same id shapes as `Filters`.
	//
	KnowledgeScope *ProjectKnowledgeScope `json:"knowledgeScope,omitzero"`
	// Display-friendly mirror of `knowledgeScope`, for rendering scope chips without a round trip.
	AppliedFilters *ProjectAppliedFilters `json:"appliedFilters,omitzero"`
	// Tool fullNames (toolset + MCP tools, same format as the
	// composer's `agentStreamTools`) this project's agent-mode chats
	// may use. Empty means no tools beyond the project's own files.
	//
	Tools []string `json:"tools,omitzero"`
	// Id of the hidden Collection holding this project's uploaded
	// files, created lazily on first upload via
	// `POST /projects/{projectId}/knowledge-base`. `null` until then.
	//
	LinkedKnowledgeBaseID optionalnullable.OptionalNullable[string] `json:"linkedKnowledgeBaseId,omitzero"`
	// `org` makes the project (and, per `chatSharing`, its
	// `project`-visible conversations) readable by every member of the
	// organization, without adding them to `members[]`. Also grants
	// the organization's synthetic all-members team `READER` access
	// on the linked hidden Collection.
	//
	Visibility *ProjectListItemVisibility `default:"private" json:"visibility"`
	// Owner-controlled default for new conversations created in this
	// project. `private` keeps new chats visible to their own owner
	// only; `members` exposes them to every project member
	// (`projectVisibility: project`). A conversation's own
	// `projectVisibility` can override this default per-chat.
	//
	ChatSharing *ProjectListItemChatSharing `default:"private" json:"chatSharing"`
	Members     []ProjectMember             `json:"members,omitzero"`
	// Owner-scoped pin state in V1 (not per-viewer).
	IsPinned   *bool                                     `default:"false" json:"isPinned"`
	IsArchived *bool                                     `default:"false" json:"isArchived"`
	ArchivedBy optionalnullable.OptionalNullable[string] `json:"archivedBy,omitzero"`
	IsDeleted  *bool                                     `default:"false" json:"isDeleted"`
	DeletedBy  optionalnullable.OptionalNullable[string] `json:"deletedBy,omitzero"`
	// Epoch milliseconds, bumped whenever a linked conversation streams a turn.
	LastActivityAt *int64         `json:"lastActivityAt,omitzero"`
	Metadata       map[string]any `json:"metadata,omitzero"`
	CreatedAt      *time.Time     `json:"createdAt,omitzero"`
	UpdatedAt      *time.Time     `json:"updatedAt,omitzero"`
	// Caller's effective role on this project (owner, explicit
	// member role, or `viewer` via `visibility: org`).
	//
	Role *ProjectListItemRole `json:"role,omitzero"`
	// Count of non-deleted conversations (chat + agent) linked to this project.
	ConversationCount *int64 `json:"conversationCount,omitzero"`
}

func (p ProjectListItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProjectListItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *ProjectListItem) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *ProjectListItem) GetOrgID() *string {
	if p == nil {
		return nil
	}
	return p.OrgID
}

func (p *ProjectListItem) GetUserID() *string {
	if p == nil {
		return nil
	}
	return p.UserID
}

func (p *ProjectListItem) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *ProjectListItem) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *ProjectListItem) GetIcon() *string {
	if p == nil {
		return nil
	}
	return p.Icon
}

func (p *ProjectListItem) GetColor() *string {
	if p == nil {
		return nil
	}
	return p.Color
}

func (p *ProjectListItem) GetInstructions() *string {
	if p == nil {
		return nil
	}
	return p.Instructions
}

func (p *ProjectListItem) GetKnowledgeScope() *ProjectKnowledgeScope {
	if p == nil {
		return nil
	}
	return p.KnowledgeScope
}

func (p *ProjectListItem) GetAppliedFilters() *ProjectAppliedFilters {
	if p == nil {
		return nil
	}
	return p.AppliedFilters
}

func (p *ProjectListItem) GetTools() []string {
	if p == nil {
		return nil
	}
	return p.Tools
}

func (p *ProjectListItem) GetLinkedKnowledgeBaseID() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.LinkedKnowledgeBaseID
}

func (p *ProjectListItem) GetVisibility() *ProjectListItemVisibility {
	if p == nil {
		return nil
	}
	return p.Visibility
}

func (p *ProjectListItem) GetChatSharing() *ProjectListItemChatSharing {
	if p == nil {
		return nil
	}
	return p.ChatSharing
}

func (p *ProjectListItem) GetMembers() []ProjectMember {
	if p == nil {
		return nil
	}
	return p.Members
}

func (p *ProjectListItem) GetIsPinned() *bool {
	if p == nil {
		return nil
	}
	return p.IsPinned
}

func (p *ProjectListItem) GetIsArchived() *bool {
	if p == nil {
		return nil
	}
	return p.IsArchived
}

func (p *ProjectListItem) GetArchivedBy() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.ArchivedBy
}

func (p *ProjectListItem) GetIsDeleted() *bool {
	if p == nil {
		return nil
	}
	return p.IsDeleted
}

func (p *ProjectListItem) GetDeletedBy() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.DeletedBy
}

func (p *ProjectListItem) GetLastActivityAt() *int64 {
	if p == nil {
		return nil
	}
	return p.LastActivityAt
}

func (p *ProjectListItem) GetMetadata() map[string]any {
	if p == nil {
		return nil
	}
	return p.Metadata
}

func (p *ProjectListItem) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *ProjectListItem) GetUpdatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}

func (p *ProjectListItem) GetRole() *ProjectListItemRole {
	if p == nil {
		return nil
	}
	return p.Role
}

func (p *ProjectListItem) GetConversationCount() *int64 {
	if p == nil {
		return nil
	}
	return p.ConversationCount
}
