// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RefreshTokenResponse - Response with new access token
type RefreshTokenResponse struct {
	// User record returned with a refreshed access token
	User RefreshTokenUser `json:"user"`
	// New JWT access token (24 hour default expiry, configurable via ACCESS_TOKEN_EXPIRY)
	AccessToken string `json:"accessToken"`
}

func (r *RefreshTokenResponse) GetUser() RefreshTokenUser {
	if r == nil {
		return RefreshTokenUser{}
	}
	return r.User
}

func (r *RefreshTokenResponse) GetAccessToken() string {
	if r == nil {
		return ""
	}
	return r.AccessToken
}
