// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RefreshTokenUser - User record returned with a refreshed access token
type RefreshTokenUser struct {
	// User ID
	ID string `json:"_id"`
	// Organization ID
	OrgID       string  `json:"orgId"`
	Email       string  `json:"email"`
	FullName    string  `json:"fullName"`
	FirstName   *string `json:"firstName,omitzero"`
	LastName    *string `json:"lastName,omitzero"`
	Designation *string `json:"designation,omitzero"`
	HasLoggedIn bool    `json:"hasLoggedIn"`
	IsDeleted   bool    `json:"isDeleted"`
	Slug        string  `json:"slug"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
	V           int64   `json:"__v"`
}

func (r *RefreshTokenUser) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RefreshTokenUser) GetOrgID() string {
	if r == nil {
		return ""
	}
	return r.OrgID
}

func (r *RefreshTokenUser) GetEmail() string {
	if r == nil {
		return ""
	}
	return r.Email
}

func (r *RefreshTokenUser) GetFullName() string {
	if r == nil {
		return ""
	}
	return r.FullName
}

func (r *RefreshTokenUser) GetFirstName() *string {
	if r == nil {
		return nil
	}
	return r.FirstName
}

func (r *RefreshTokenUser) GetLastName() *string {
	if r == nil {
		return nil
	}
	return r.LastName
}

func (r *RefreshTokenUser) GetDesignation() *string {
	if r == nil {
		return nil
	}
	return r.Designation
}

func (r *RefreshTokenUser) GetHasLoggedIn() bool {
	if r == nil {
		return false
	}
	return r.HasLoggedIn
}

func (r *RefreshTokenUser) GetIsDeleted() bool {
	if r == nil {
		return false
	}
	return r.IsDeleted
}

func (r *RefreshTokenUser) GetSlug() string {
	if r == nil {
		return ""
	}
	return r.Slug
}

func (r *RefreshTokenUser) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *RefreshTokenUser) GetUpdatedAt() string {
	if r == nil {
		return ""
	}
	return r.UpdatedAt
}

func (r *RefreshTokenUser) GetV() int64 {
	if r == nil {
		return 0
	}
	return r.V
}
