// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// ReindexRecordRequestBody - Optional body for single-record reindex.
type ReindexRecordRequestBody struct {
	// Child traversal depth (`0` = record only; higher values include
	// descendants; `100` is used by clients for folder-like reindex).
	//
	Depth *int64 `default:"0" json:"depth"`
	// Force reindex even when the connector considers the record unchanged.
	Force *bool `default:"false" json:"force"`
	// When set, only records whose indexing status matches one of these
	// values are reindexed (applies to the record and its descendants per `depth`).
	//
	StatusFilters []IndexingStatusFilter `json:"statusFilters,omitzero"`
}

func (r ReindexRecordRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReindexRecordRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReindexRecordRequestBody) GetDepth() *int64 {
	if r == nil {
		return nil
	}
	return r.Depth
}

func (r *ReindexRecordRequestBody) GetForce() *bool {
	if r == nil {
		return nil
	}
	return r.Force
}

func (r *ReindexRecordRequestBody) GetStatusFilters() []IndexingStatusFilter {
	if r == nil {
		return nil
	}
	return r.StatusFilters
}
