// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RevokePatRequest - Optional request body for `DELETE /personal-access-tokens/{tokenId}`
// and `DELETE /personal-access-tokens/admin/{tokenId}`. The body itself
// is optional; `reason`, if present, is stored on the revocation for
// auditing.
type RevokePatRequest struct {
	Reason *string `json:"reason,omitzero"`
}

func (r *RevokePatRequest) GetReason() *string {
	if r == nil {
		return nil
	}
	return r.Reason
}
