// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SSEEventEvent string

const (
	SSEEventEventRunStarted              SSEEventEvent = "RUN_STARTED"
	SSEEventEventRunFinished             SSEEventEvent = "RUN_FINISHED"
	SSEEventEventRunError                SSEEventEvent = "RUN_ERROR"
	SSEEventEventStepStarted             SSEEventEvent = "STEP_STARTED"
	SSEEventEventStepFinished            SSEEventEvent = "STEP_FINISHED"
	SSEEventEventTextMessageStart        SSEEventEvent = "TEXT_MESSAGE_START"
	SSEEventEventTextMessageContent      SSEEventEvent = "TEXT_MESSAGE_CONTENT"
	SSEEventEventTextMessageEnd          SSEEventEvent = "TEXT_MESSAGE_END"
	SSEEventEventReasoningStart          SSEEventEvent = "REASONING_START"
	SSEEventEventReasoningMessageStart   SSEEventEvent = "REASONING_MESSAGE_START"
	SSEEventEventReasoningMessageContent SSEEventEvent = "REASONING_MESSAGE_CONTENT"
	SSEEventEventReasoningMessageEnd     SSEEventEvent = "REASONING_MESSAGE_END"
	SSEEventEventReasoningEnd            SSEEventEvent = "REASONING_END"
	SSEEventEventToolCallStart           SSEEventEvent = "TOOL_CALL_START"
	SSEEventEventToolCallArgs            SSEEventEvent = "TOOL_CALL_ARGS"
	SSEEventEventToolCallEnd             SSEEventEvent = "TOOL_CALL_END"
	SSEEventEventToolCallResult          SSEEventEvent = "TOOL_CALL_RESULT"
	SSEEventEventStateDelta              SSEEventEvent = "STATE_DELTA"
	SSEEventEventStateSnapshot           SSEEventEvent = "STATE_SNAPSHOT"
	SSEEventEventCustom                  SSEEventEvent = "CUSTOM"
	SSEEventEventHeartbeat               SSEEventEvent = "HEARTBEAT"
)

func (e SSEEventEvent) ToPointer() *SSEEventEvent {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *SSEEventEvent) IsExact() bool {
	if e != nil {
		switch *e {
		case "RUN_STARTED", "RUN_FINISHED", "RUN_ERROR", "STEP_STARTED", "STEP_FINISHED", "TEXT_MESSAGE_START", "TEXT_MESSAGE_CONTENT", "TEXT_MESSAGE_END", "REASONING_START", "REASONING_MESSAGE_START", "REASONING_MESSAGE_CONTENT", "REASONING_MESSAGE_END", "REASONING_END", "TOOL_CALL_START", "TOOL_CALL_ARGS", "TOOL_CALL_END", "TOOL_CALL_RESULT", "STATE_DELTA", "STATE_SNAPSHOT", "CUSTOM", "HEARTBEAT":
			return true
		}
	}
	return false
}

// SSEEvent - Server-Sent Event envelope for streaming chat responses. AG-UI is
// the sole wire protocol.
//
// `event` carries the AG-UI type name and `data` is a JSON-encoded
// object that includes a `"type"` field matching `event`, plus
// type-specific fields. Stable gateway-generated top-level outcomes:
//
//   - `RUN_FINISHED` — `{ type, result }`; `result` carries the full
//     persisted `conversation` and a `meta` block with `requestId`,
//     `timestamp` and `duration`.
//   - `RUN_ERROR` — `{ type, message, code? }`. The conversation row is
//     marked FAILED before the stream closes.
//
// Forwarded upstream lifecycle or child-run events may contain `runId`,
// `threadId`, and `parentRunId`. Gateway-generated root terminal events
// do not. Clients should ignore unknown event names.
type SSEEvent struct {
	Event *SSEEventEvent `json:"event,omitzero"`
	// JSON-encoded event payload. The decoded JSON includes a `"type"`
	// field matching `event`, plus type-specific fields. Shape depends
	// on `event`.
	//
	Data *string `json:"data,omitzero"`
}

func (s *SSEEvent) GetEvent() *SSEEventEvent {
	if s == nil {
		return nil
	}
	return s.Event
}

func (s *SSEEvent) GetData() *string {
	if s == nil {
		return nil
	}
	return s.Data
}

func (s SSEEvent) GetEventEncoding(event string) (string, error) {
	return "string", nil
}
