// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
	"time"
)

type StoredAgentConversationStatus string

const (
	StoredAgentConversationStatusNone       StoredAgentConversationStatus = "None"
	StoredAgentConversationStatusInprogress StoredAgentConversationStatus = "Inprogress"
	StoredAgentConversationStatusComplete   StoredAgentConversationStatus = "Complete"
	StoredAgentConversationStatusFailed     StoredAgentConversationStatus = "Failed"
)

func (e StoredAgentConversationStatus) ToPointer() *StoredAgentConversationStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StoredAgentConversationStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "None", "Inprogress", "Complete", "Failed":
			return true
		}
	}
	return false
}

type StoredAgentConversationAccessLevel string

const (
	StoredAgentConversationAccessLevelRead  StoredAgentConversationAccessLevel = "read"
	StoredAgentConversationAccessLevelWrite StoredAgentConversationAccessLevel = "write"
)

func (e StoredAgentConversationAccessLevel) ToPointer() *StoredAgentConversationAccessLevel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StoredAgentConversationAccessLevel) IsExact() bool {
	if e != nil {
		switch *e {
		case "read", "write":
			return true
		}
	}
	return false
}

type StoredAgentConversationSharedWith struct {
	UserID      *string                             `json:"userId,omitzero"`
	AccessLevel *StoredAgentConversationAccessLevel `json:"accessLevel,omitzero"`
}

func (s *StoredAgentConversationSharedWith) GetUserID() *string {
	if s == nil {
		return nil
	}
	return s.UserID
}

func (s *StoredAgentConversationSharedWith) GetAccessLevel() *StoredAgentConversationAccessLevel {
	if s == nil {
		return nil
	}
	return s.AccessLevel
}

type StoredAgentConversationConversationError struct {
	ID        *string        `json:"_id,omitzero"`
	Message   *string        `json:"message,omitzero"`
	ErrorType *string        `json:"errorType,omitzero"`
	Timestamp *time.Time     `json:"timestamp,omitzero"`
	MessageID *string        `json:"messageId,omitzero"`
	Stack     *string        `json:"stack,omitzero"`
	Metadata  map[string]any `json:"metadata,omitzero"`
}

func (s StoredAgentConversationConversationError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StoredAgentConversationConversationError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StoredAgentConversationConversationError) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *StoredAgentConversationConversationError) GetMessage() *string {
	if s == nil {
		return nil
	}
	return s.Message
}

func (s *StoredAgentConversationConversationError) GetErrorType() *string {
	if s == nil {
		return nil
	}
	return s.ErrorType
}

func (s *StoredAgentConversationConversationError) GetTimestamp() *time.Time {
	if s == nil {
		return nil
	}
	return s.Timestamp
}

func (s *StoredAgentConversationConversationError) GetMessageID() *string {
	if s == nil {
		return nil
	}
	return s.MessageID
}

func (s *StoredAgentConversationConversationError) GetStack() *string {
	if s == nil {
		return nil
	}
	return s.Stack
}

func (s *StoredAgentConversationConversationError) GetMetadata() map[string]any {
	if s == nil {
		return nil
	}
	return s.Metadata
}

type StoredAgentConversationConversationSource string

const (
	StoredAgentConversationConversationSourceAgentChat StoredAgentConversationConversationSource = "agent_chat"
)

func (e StoredAgentConversationConversationSource) ToPointer() *StoredAgentConversationConversationSource {
	return &e
}
func (e *StoredAgentConversationConversationSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agent_chat":
		*e = StoredAgentConversationConversationSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StoredAgentConversationConversationSource: %v", v)
	}
}

// StoredAgentConversation - Stored agent conversation document returned by non-list endpoints.
type StoredAgentConversation struct {
	ID         *string                        `json:"_id,omitzero"`
	AgentKey   *string                        `json:"agentKey,omitzero"`
	UserID     *string                        `json:"userId,omitzero"`
	OrgID      *string                        `json:"orgId,omitzero"`
	Title      *string                        `json:"title,omitzero"`
	Initiator  *string                        `json:"initiator,omitzero"`
	Messages   []Message                      `json:"messages,omitzero"`
	Status     *StoredAgentConversationStatus `json:"status,omitzero"`
	FailReason *string                        `json:"failReason,omitzero"`
	// AI model configuration recorded against a conversation or message.
	ModelInfo          *ConversationModelInfo                     `json:"modelInfo,omitzero"`
	IsShared           *bool                                      `json:"isShared,omitzero"`
	ShareLink          *string                                    `json:"shareLink,omitzero"`
	SharedWith         []StoredAgentConversationSharedWith        `json:"sharedWith,omitzero"`
	IsArchived         *bool                                      `json:"isArchived,omitzero"`
	ArchivedBy         optionalnullable.OptionalNullable[string]  `json:"archivedBy,omitzero"`
	IsDeleted          *bool                                      `json:"isDeleted,omitzero"`
	DeletedBy          optionalnullable.OptionalNullable[string]  `json:"deletedBy,omitzero"`
	ConversationErrors []StoredAgentConversationConversationError `json:"conversationErrors,omitzero"`
	ConversationSource *StoredAgentConversationConversationSource `json:"conversationSource,omitzero"`
	LastActivityAt     *int64                                     `json:"lastActivityAt,omitzero"`
	CreatedAt          *time.Time                                 `json:"createdAt,omitzero"`
	UpdatedAt          *time.Time                                 `json:"updatedAt,omitzero"`
	V                  *int64                                     `json:"__v,omitzero"`
}

func (s StoredAgentConversation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StoredAgentConversation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StoredAgentConversation) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *StoredAgentConversation) GetAgentKey() *string {
	if s == nil {
		return nil
	}
	return s.AgentKey
}

func (s *StoredAgentConversation) GetUserID() *string {
	if s == nil {
		return nil
	}
	return s.UserID
}

func (s *StoredAgentConversation) GetOrgID() *string {
	if s == nil {
		return nil
	}
	return s.OrgID
}

func (s *StoredAgentConversation) GetTitle() *string {
	if s == nil {
		return nil
	}
	return s.Title
}

func (s *StoredAgentConversation) GetInitiator() *string {
	if s == nil {
		return nil
	}
	return s.Initiator
}

func (s *StoredAgentConversation) GetMessages() []Message {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *StoredAgentConversation) GetStatus() *StoredAgentConversationStatus {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *StoredAgentConversation) GetFailReason() *string {
	if s == nil {
		return nil
	}
	return s.FailReason
}

func (s *StoredAgentConversation) GetModelInfo() *ConversationModelInfo {
	if s == nil {
		return nil
	}
	return s.ModelInfo
}

func (s *StoredAgentConversation) GetIsShared() *bool {
	if s == nil {
		return nil
	}
	return s.IsShared
}

func (s *StoredAgentConversation) GetShareLink() *string {
	if s == nil {
		return nil
	}
	return s.ShareLink
}

func (s *StoredAgentConversation) GetSharedWith() []StoredAgentConversationSharedWith {
	if s == nil {
		return nil
	}
	return s.SharedWith
}

func (s *StoredAgentConversation) GetIsArchived() *bool {
	if s == nil {
		return nil
	}
	return s.IsArchived
}

func (s *StoredAgentConversation) GetArchivedBy() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.ArchivedBy
}

func (s *StoredAgentConversation) GetIsDeleted() *bool {
	if s == nil {
		return nil
	}
	return s.IsDeleted
}

func (s *StoredAgentConversation) GetDeletedBy() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.DeletedBy
}

func (s *StoredAgentConversation) GetConversationErrors() []StoredAgentConversationConversationError {
	if s == nil {
		return nil
	}
	return s.ConversationErrors
}

func (s *StoredAgentConversation) GetConversationSource() *StoredAgentConversationConversationSource {
	if s == nil {
		return nil
	}
	return s.ConversationSource
}

func (s *StoredAgentConversation) GetLastActivityAt() *int64 {
	if s == nil {
		return nil
	}
	return s.LastActivityAt
}

func (s *StoredAgentConversation) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *StoredAgentConversation) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *StoredAgentConversation) GetV() *int64 {
	if s == nil {
		return nil
	}
	return s.V
}
