// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

type ToolsetTool struct {
	// Tool node key in the backing graph store.
	Key      *string `json:"_key,omitzero"`
	Name     *string `json:"name,omitzero"`
	FullName *string `json:"fullName,omitzero"`
	// Toolset type key the tool belongs to.
	ToolsetName *string `json:"toolsetName,omitzero"`
	Description *string `json:"description,omitzero"`
	// Server-stamped on `GET /agents/{agentKey}`: `true` when the
	// tool's `fullName` is no longer in the runtime tool registry
	// (its `@tool` was removed). Read-only; ignored on create/update
	// bodies. Not stamped on the `GET /agents` list projection.
	//
	Deprecated *bool `json:"deprecated,omitzero"`
}

func (t *ToolsetTool) GetKey() *string {
	if t == nil {
		return nil
	}
	return t.Key
}

func (t *ToolsetTool) GetName() *string {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *ToolsetTool) GetFullName() *string {
	if t == nil {
		return nil
	}
	return t.FullName
}

func (t *ToolsetTool) GetToolsetName() *string {
	if t == nil {
		return nil
	}
	return t.ToolsetName
}

func (t *ToolsetTool) GetDescription() *string {
	if t == nil {
		return nil
	}
	return t.Description
}

func (t *ToolsetTool) GetDeprecated() *bool {
	if t == nil {
		return nil
	}
	return t.Deprecated
}

// Toolset instance linked to an agent, as projected by the graph store on
// `GET /agents/{agentKey}` and `GET /agents`. Multiple instances of the
// same integration type are distinguished by `instanceId` and optional
// `instanceName`.
type Toolset struct {
	// Toolset instance node key in the backing graph store.
	Key *string `json:"_key,omitzero"`
	// Integration / toolset type key.
	Name *AgentCreateToolsetName `json:"name,omitzero"`
	// Human-readable toolset product label (for example `Jira` or `Slack`).
	DisplayName *string `json:"displayName,omitzero"`
	Type        *string `json:"type,omitzero"`
	// Admin-created toolset instance id
	InstanceID *string `json:"instanceId,omitzero"`
	// Human-readable instance label (e.g. sidebar instance name)
	InstanceName *string `json:"instanceName,omitzero"`
	// Tool names explicitly selected for this toolset instance, when the
	// instance was created with a subset selection. `null`/absent when the
	// instance exposes all of the toolset's tools.
	//
	SelectedTools optionalnullable.OptionalNullable[[]string] `json:"selectedTools,omitzero"`
	Tools         []ToolsetTool                               `json:"tools,omitzero"`
}

func (t Toolset) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Toolset) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Toolset) GetKey() *string {
	if t == nil {
		return nil
	}
	return t.Key
}

func (t *Toolset) GetName() *AgentCreateToolsetName {
	if t == nil {
		return nil
	}
	return t.Name
}

func (t *Toolset) GetDisplayName() *string {
	if t == nil {
		return nil
	}
	return t.DisplayName
}

func (t *Toolset) GetType() *string {
	if t == nil {
		return nil
	}
	return t.Type
}

func (t *Toolset) GetInstanceID() *string {
	if t == nil {
		return nil
	}
	return t.InstanceID
}

func (t *Toolset) GetInstanceName() *string {
	if t == nil {
		return nil
	}
	return t.InstanceName
}

func (t *Toolset) GetSelectedTools() optionalnullable.OptionalNullable[[]string] {
	if t == nil {
		return nil
	}
	return t.SelectedTools
}

func (t *Toolset) GetTools() []ToolsetTool {
	if t == nil {
		return nil
	}
	return t.Tools
}
