// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UploadLimitsResponseSchema - Upload constraints returned by GET /knowledgeBase/limits.
type UploadLimitsResponseSchema struct {
	// Maximum number of files per upload request
	MaxFilesPerRequest int64 `json:"maxFilesPerRequest"`
	// Maximum file size in bytes (default 30MB when platform settings unavailable)
	MaxFileSizeBytes int64 `json:"maxFileSizeBytes"`
}

func (u *UploadLimitsResponseSchema) GetMaxFilesPerRequest() int64 {
	if u == nil {
		return 0
	}
	return u.MaxFilesPerRequest
}

func (u *UploadLimitsResponseSchema) GetMaxFileSizeBytes() int64 {
	if u == nil {
		return 0
	}
	return u.MaxFileSizeBytes
}
