// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// WebSearchProviderItem - Web search provider configuration item returned by getWebSearchProviders
type WebSearchProviderItem struct {
	// Supported web search provider
	Provider WebSearchProviderType `json:"provider"`
	// Unique key for the provider configuration
	ProviderKey string `json:"providerKey"`
	// Provider-specific configuration as stored and returned by the gateway (open record).
	// Serper, Tavily, and Exa typically include `apiKey`; additional keys may be present.
	//
	Configuration map[string]any `json:"configuration"`
	IsDefault     bool           `json:"isDefault"`
}

func (w *WebSearchProviderItem) GetProvider() WebSearchProviderType {
	if w == nil {
		return WebSearchProviderType("")
	}
	return w.Provider
}

func (w *WebSearchProviderItem) GetProviderKey() string {
	if w == nil {
		return ""
	}
	return w.ProviderKey
}

func (w *WebSearchProviderItem) GetConfiguration() map[string]any {
	if w == nil {
		return map[string]any{}
	}
	return w.Configuration
}

func (w *WebSearchProviderItem) GetIsDefault() bool {
	if w == nil {
		return false
	}
	return w.IsDefault
}
