// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type WebSearchProvidersResponseStatus string

const (
	WebSearchProvidersResponseStatusSuccess WebSearchProvidersResponseStatus = "success"
)

func (e WebSearchProvidersResponseStatus) ToPointer() *WebSearchProvidersResponseStatus {
	return &e
}
func (e *WebSearchProvidersResponseStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		*e = WebSearchProvidersResponseStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebSearchProvidersResponseStatus: %v", v)
	}
}

// WebSearchProvidersResponse - Response for getWebSearchProviders
type WebSearchProvidersResponse struct {
	Status    WebSearchProvidersResponseStatus `json:"status"`
	Providers []WebSearchProviderItem          `json:"providers"`
	// Normalized web search global settings returned by getWebSearchProviders
	Settings WebSearchSettings `json:"settings"`
	// Human-readable status (empty list vs populated providers)
	Message string `json:"message"`
}

func (w *WebSearchProvidersResponse) GetStatus() WebSearchProvidersResponseStatus {
	if w == nil {
		return WebSearchProvidersResponseStatus("")
	}
	return w.Status
}

func (w *WebSearchProvidersResponse) GetProviders() []WebSearchProviderItem {
	if w == nil {
		return []WebSearchProviderItem{}
	}
	return w.Providers
}

func (w *WebSearchProvidersResponse) GetSettings() WebSearchSettings {
	if w == nil {
		return WebSearchSettings{}
	}
	return w.Settings
}

func (w *WebSearchProvidersResponse) GetMessage() string {
	if w == nil {
		return ""
	}
	return w.Message
}
