// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// WebSearchSettings - Normalized web search global settings returned by getWebSearchProviders
type WebSearchSettings struct {
	// Whether to include images in search results
	IncludeImages bool `json:"includeImages"`
	// Maximum number of images to return when includeImages is true
	MaxImages *int64 `json:"maxImages,omitzero"`
}

func (w *WebSearchSettings) GetIncludeImages() bool {
	if w == nil {
		return false
	}
	return w.IncludeImages
}

func (w *WebSearchSettings) GetMaxImages() *int64 {
	if w == nil {
		return nil
	}
	return w.MaxImages
}
