// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"errors"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ForbiddenType string

const (
	ForbiddenTypeErrorResponse             ForbiddenType = "ErrorResponse"
	ForbiddenTypeStreamRecordErrorResponse ForbiddenType = "StreamRecordErrorResponse"
	ForbiddenTypeUnknown                   ForbiddenType = "Unknown"
)

// Forbidden - Forbidden. Returned either when the OAuth token is missing the required
// `kb:read` scope or when the authenticated user does not have access to the record.
type Forbidden struct {
	ErrorResponse             *ErrorResponse             `queryParam:"inline" union:"member"`
	StreamRecordErrorResponse *StreamRecordErrorResponse `queryParam:"inline" union:"member"`
	UnknownRaw                json.RawMessage            `json:"-" union:"unknown"`

	Type ForbiddenType

	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &Forbidden{}

func CreateForbiddenErrorResponse(errorResponse ErrorResponse) Forbidden {
	typ := ForbiddenTypeErrorResponse

	return Forbidden{
		ErrorResponse: &errorResponse,
		Type:          typ,
	}
}

func CreateForbiddenStreamRecordErrorResponse(streamRecordErrorResponse StreamRecordErrorResponse) Forbidden {
	typ := ForbiddenTypeStreamRecordErrorResponse

	return Forbidden{
		StreamRecordErrorResponse: &streamRecordErrorResponse,
		Type:                      typ,
	}
}

func CreateForbiddenUnknown(raw json.RawMessage) Forbidden {
	return Forbidden{
		UnknownRaw: raw,
		Type:       ForbiddenTypeUnknown,
	}
}

func (u Forbidden) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u Forbidden) IsUnknown() bool {
	return u.Type == ForbiddenTypeUnknown
}

func (u *Forbidden) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var errorResponse ErrorResponse = ErrorResponse{}
	if err := utils.UnmarshalJSON(data, &errorResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ForbiddenTypeErrorResponse,
			Value: &errorResponse,
		})
	}

	var streamRecordErrorResponse StreamRecordErrorResponse = StreamRecordErrorResponse{}
	if err := utils.UnmarshalJSON(data, &streamRecordErrorResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  ForbiddenTypeStreamRecordErrorResponse,
			Value: &streamRecordErrorResponse,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ForbiddenTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ForbiddenTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(ForbiddenType)
	switch best.Type {
	case ForbiddenTypeErrorResponse:
		u.ErrorResponse = best.Value.(*ErrorResponse)
		return nil
	case ForbiddenTypeStreamRecordErrorResponse:
		u.StreamRecordErrorResponse = best.Value.(*StreamRecordErrorResponse)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = ForbiddenTypeUnknown
	return nil
}

func (u Forbidden) MarshalJSON() ([]byte, error) {
	if u.ErrorResponse != nil {
		return utils.MarshalJSON(u.ErrorResponse, "", true)
	}

	if u.StreamRecordErrorResponse != nil {
		return utils.MarshalJSON(u.StreamRecordErrorResponse, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type Forbidden: all fields are null")
}

func (u Forbidden) Error() string {
	switch u.Type {
	case ForbiddenTypeErrorResponse:
		data, _ := json.Marshal(u.ErrorResponse)
		return string(data)
	case ForbiddenTypeStreamRecordErrorResponse:
		data, _ := json.Marshal(u.StreamRecordErrorResponse)
		return string(data)
	case ForbiddenTypeUnknown:
		if u.UnknownRaw != nil {
			return string(u.UnknownRaw)
		}
		return "unknown error"
	default:
		return "unknown error"
	}
}
