// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// StreamRecordErrorResponse - Error payload returned by the legacy record-stream proxy when the downstream
// streaming request fails after route middleware has passed.
type StreamRecordErrorResponse struct {
	// Human-readable error message from the gateway or downstream stream service
	Error_   string                  `json:"error"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &StreamRecordErrorResponse{}

func (e *StreamRecordErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
